#!/bin/sh
#
# ---------------------------------------------------------------------------
#
# Copyright (c) 2001-2009 John Graham-Cumming
#
#   This file is part of POPFile
#
# POPFile is free software; you can redistribute it and/or modify it
# under the terms of verion 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# POPFile is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# ---------------------------------------------------------------------------

# ===
#
# popfile
#
# A shell script designed to start and stop POPFile from within
# /etc/init.d on *nix systems.
#
# usage: popfile { start | stop | restart | status }
 
##
# RedHat comment block...
#
# chkconfig: 345 80 20
# description: popfile is a POP3 proxy and mail filter
# pidfile: /var/run/popfile.pid
# processname: popfile
##
 
##
# LSB comment block...
#
# The bogus 345 run-levels are a workround for a buggy RedHat chkconfig which
# reads the LSB comment block (incorrectly) as an undocumented 'feature'.
#
### BEGIN INIT INFO
# Provides: popfile
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 2345 2 3 4 5
# Default-Stop: 016 0 1 6
# Description: POPFile - Automatic Email Classification
### END INIT INFO
##
 
popfile_root=/usr/share/popfile/
popfile_data=/var/lib/popfile/
popfile_piddir=/var/run/
popfile_logdir=/var/log/popfile/

popfile="${popfile_root}popfile.pl" 
cwd=`pwd`
popfile_pid="${popfile_piddir}popfile.pid"
pid=`cat ${popfile_pid} 2> /dev/null` 

RUNNING=0
if [ "${pid}" != "" ] ; then
    if kill -0 "${pid}" >/dev/null 2>&1 ; then
        RUNNING=1
    else
        rm -f ${popfile_pid}
    fi
fi

start() {
    echo -n "Starting POPFile as background process: "
    if [ "${RUNNING}" = "0" ]; then
        export POPFILE_ROOT=${popfile_root}
        export POPFILE_USER=${popfile_data}
        umask 0027
        ${popfile} --set config_piddir=${popfile_piddir} --set logger_logdir=${popfile_logdir} &> ${popfile_logdir}console.log &
        echo " done"
    else
        echo " POPFile already running"
    fi
}
 
stop() {
    echo -n "Stopping POPFile: "
 
    if [ "${RUNNING}" = "0" ] ; then
        echo "POPFile not running"
    else
        kill -s TERM $pid
        echo " done"
    fi
}
 
status() {
    if [ "${RUNNING}" = "0" ] ; then
        echo "down"
    else
        echo "up"
    fi
}
 
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
 
cd $cwd
exit 0
