#!/bin/sh

# Copyright (c) John Graham-Cumming
#
#   This file is part of POPFile
#
#   POPFile is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   POPFile is free software; you can redistribute it and/or modify it
#   under the terms of version 2 of the GNU General Public License as
#   published by the Free Software Foundation.
#
#   You should have received a copy of the GNU General Public License
#   along with POPFile; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

POPFILE_STARTUP=/Library/StartupItems/POPFile/POPFile
POPFILE_DIR=/Library/POPFile
STOPWORDS_PATH="$POPFILE_DIR"/stopwords
POPFILE_DB_PATH="$POPFILE_DIR"/popfile.db
POPFILE_CFG_PATH="$POPFILE_DIR"/popfile.cfg

# stop POPFile
if [ -e "$POPFILE_STARTUP" ]; then
	"$POPFILE_STARTUP" stop
fi

# back up stopwords
if [ -e "$STOPWORDS_PATH" ]; then
	rm "$STOPWORDS_PATH".old
	cp "$STOPWORDS_PATH" "$STOPWORDS_PATH".old
fi

# back up database
if [ -e "$POPFILE_DB_PATH" ]; then
	rm "$POPFILE_DB_PATH".old
	cp "$POPFILE_DB_PATH" "$POPFILE_DB_PATH".old
fi

# back up configuration
if [ -e "$POPFILE_CFG_PATH" ]; then
	rm "$POPFILE_CFG_PATH".old
	cp "$POPFILE_CFG_PATH" "$POPFILE_CFG_PATH".old
fi

exit 0
