Return-Path: <xxxxxx@ezweb.ne.jp>
Delivered-To: xxxx@xxx.ne.jp
Received: from xxxxxxxx.ezweb.ne.jp (xxxxxxxx.ezweb.ne.jp [xx.xxx.x.xxx])	by 
xxxxx.xxx.ne.jp (Postfix) with SMTP id C81CD305BF
    for <xxxx@xxx.ne.jp>; Mon,  6 Sep 2004 10:34:46 +0900 (JST)
From: xxxxxx@ezweb.ne.jp
To: xxxx@xxx.ne.jp
Subject: Subject: €x96€xA2€x8F€xB3€x91€xF8€x8DL€x8D€x90€x81€xA6€x81@€x81€x9A[€x8B€x90€x93€xFB][€x93€x90€x8EB][€x83€x8C€x83C€x83v][€x8F€x97€x8B€xB3€x8Et][€x83i€x81[€x83X]€x8D€xD5€x82€xE8€x8AJ€x8D€xC3€x92€x86€x81I€x81€x9A
Message-ID: <200409060129548590190028CRA1@xxxxxxxx.ezweb.ne.jp>
Date: Mon, 6 Sep 2004 10:29:54 +0900
Mime-Version: 1.0
Content-Type: text/plain; charset="iso-2022-jp"
Content-Transfer-Encoding: 7bit
X-UIDL: gDQ"!H!""!J+n!!-4^"!
X-EdMax-Uidl: gDQ"!H!""!J+n!!-4^"!

$B$"$j$,$H$&