Received: from great-babes-online.com ([209.189.84.42])
        by xxx.xxx.net (Merak 6.0.5) with SMTP id FIR37786
        for <xxx@xxx.net>; Thu, 23 Oct 2003 03:05:56 -0500
To: xxx@xxx.net
From: "Becky"  <81355329526@mail2.great-babes-online.com>
Return-Path: <81355329526@mail2.great-babes-online.com>
Date: Thu, 23 Oct 2003 01:05:54 -0700
Subject: Luscious Black Nymphos!
MIME-Version: 1.0
Content-type: multipart/alternative; boundary="BoundryStart--3330353135333832393035323036--BoundryEnd"


--BoundryStart--3330353135333832393035323036--BoundryEnd
Content-type:text/plain

We've got all the HOT BLACK PUSSY you can handle!
http://great-babes-online.com/sites/30515382905206/txt/279

See real Black Beauties getting off!
http://great-babes-online.com/sites/30515382905206/txt/279



FREE 30 Minute ALL ACCESS trial!
http://great-babes-online.com/sites/30515382905206/txt/279







====================================================================================
Unsubscribe
http://www.great-babes-online.com/process/30515382905206/txt/

If you are having problems with the link above, you can email your request directly to: mailto: remove@great-babes-online.com
====================================================================================

--BoundryStart--3330353135333832393035323036--BoundryEnd
Content-type: text/html

<HTML>
<table border=0 cellpadding=0 cellspacing=0>
<tr>
<td><a href="http://great-babes-online.com/sites/30515382905206/html/279"><img src="http://great-babes-online.com/images/431/sista_700x400_left_top_001.jpg" width=366 height=49 border="0"></a></td>
<td><a href="http://great-babes-online.com/sites/30515382905206/html/279"><img src="http://great-babes-online.com/images/431/sista_700x400_rt_topa_001.gif" width=334 height=49 border="0"></a></td>
</tr>    
<tr><td><a href="http://great-babes-online.com/sites/30515382905206/html/279"><img src="http://great-babes-online.com/images/431/sista_700x400_model_001.jpg" width=366 height=300 border="0"></a></td>
<td><a href="http://great-babes-online.com/sites/30515382905206/html/279"><img src="http://great-babes-online.com/images/431/sista_700x400_text_001.gif" width=334 height=300 border="0"></a></td>
</tr>    
<tr>
<td><a href="http://great-babes-online.com/sites/30515382905206/html/279"><img src="http://great-babes-online.com/images/431/sista_700x400_left_bot_001.jpg" width=366 height=51 border="0"></a></td>
<td><a href="http://great-babes-online.com/sites/30515382905206/html/279"><img src="http://great-babes-online.com/images/431/sista_700x400_bot_rt_001.gif" width=334 height=51 border="0"></a></td>
</tr>
</table>
</HTML>
<TABLE><TR COLSPAN=4>
<TD WIDTH=62><FONT FACE='ARIAL'SIZE=1>&nbsp;</FONT></TD>
<TD WIDTH=59><FONT FACE='ARIAL'SIZE=1>&nbsp;</FONT></TD>
<TD WIDTH=23><FONT FACE='ARIAL'SIZE=1>&nbsp;</FONT></TD>
<TD WIDTH=55><FONT FACE='ARIAL'SIZE=1>&nbsp;</FONT></TD>
</TR></TABLE>

<br><br><br><br><br><br><div align=center><table cellspacing=5 cellpadding=5><tr><td bgcolor=white>
<br>
<a href=http://www.great-babes-online.com/process/30515382905206/html/>
<img src=http://www.great-babes-online.com/images/30515382905206/html/spacer.gif border=0>
</a>
<br>
</td></tr></table></div></body></html> 
.
To: xxx@xxx.net
From: "Becky"  <81355329526@mail2.great-babes-online.com>
Return-Path: <81355329526@mail2.great-babes-online.com>
Date: Thu, 23 Oct 2003 01:05:54 -0700
Subject: Luscious Black Nymphos!
MIME-Version: 1.0
Content-type: multipart/alternative; boundary="BoundryStart--3330353135333832393035323036--BoundryEnd"


--BoundryStart--3330353135333832393035323036--BoundryEnd
Content-type:text/plain

We've got all the HOT BLACK PUSSY you can handle!
http://great-babes-online.com/sites/30515382905206/txt/279

See real Black Beauties getting off!
http://great-babes-online.com/sites/30515382905206/txt/279



FREE 30 Minute ALL ACCESS trial!
http://great-babes-online.com/sites/30515382905206/txt/279







====================================================================================
Unsubscribe
http://www.great-babes-online.com/process/30515382905206/txt/

If you are having problems with the link above, you can email your request directly to: mailto: remove@great-babes-online.com
====================================================================================

--BoundryStart--3330353135333832393035323036--BoundryEnd
Content-type: text/html

<HTML>
<table border=0 cellpadding=0 cellspacing=0>
<tr>
<td><a href="http://great-babes-online.com/sites/30515382905206/html/279"><img src="http://great-babes-online.com/images/431/sista_700x400_left_top_001.jpg" width=366 height=49 border="0"></a></td>
<td><a href="http://great-babes-online.com/sites/30515382905206/html/279"><img src="http://great-babes-online.com/images/431/sista_700x400_rt_topa_001.gif" width=334 height=49 border="0"></a></td>
</tr>    
<tr><td><a href="http://great-babes-online.com/sites/30515382905206/html/279"><img src="http://great-babes-online.com/images/431/sista_700x400_model_001.jpg" width=366 height=300 border="0"></a></td>
<td><a href="http://great-babes-online.com/sites/30515382905206/html/279"><img src="http://great-babes-online.com/images/431/sista_700x400_text_001.gif" width=334 height=300 border="0"></a></td>
</tr>    
<tr>
<td><a href="http://great-babes-online.com/sites/30515382905206/html/279"><img src="http://great-babes-online.com/images/431/sista_700x400_left_bot_001.jpg" width=366 height=51 border="0"></a></td>
<td><a href="http://great-babes-online.com/sites/30515382905206/html/279"><img src="http://great-babes-online.com/images/431/sista_700x400_bot_rt_001.gif" width=334 height=51 border="0"></a></td>
</tr>
</table>
</HTML>
<TABLE><TR COLSPAN=4>
<TD WIDTH=62><FONT FACE='ARIAL'SIZE=1>&nbsp;</FONT></TD>
<TD WIDTH=59><FONT FACE='ARIAL'SIZE=1>&nbsp;</FONT></TD>
<TD WIDTH=23><FONT FACE='ARIAL'SIZE=1>&nbsp;</FONT></TD>
<TD WIDTH=55><FONT FACE='ARIAL'SIZE=1>&nbsp;</FONT></TD>
</TR></TABLE>

<br><br><br><br><br><br><div align=center><table cellspacing=5 cellpadding=5><tr><td bgcolor=white>
<br>
<a href=http://www.great-babes-online.com/process/30515382905206/html/>
<img src=http://www.great-babes-online.com/images/30515382905206/html/spacer.gif border=0>
</a>
<br>
</td></tr></table></div></body></html> 
.
