Return-path: <delmail@18kin.jp>
Date: Fri, 06 Feb 2004 19:54:26 +0900 (JST)
From: =?ISO-2022-JP?B?GyRCIzEjODZYGyhCSkFQQU4=?= <delmail@18kin.jp>
Subject: test
To: test@example.com
Reply-to: delmail@18kin.jp
Message-id: <30377211.1076064866745.JavaMail.root@news3.e-dm.jp>
MIME-version: 1.0
Content-type: multipart/alternative;
 boundary="----=_Part_165258_6893572.1076064866744"

------=_Part_165258_6893572.1076064866744
Content-Type: text/plain; charset=ISO-2022-JP
Content-Transfer-Encoding: 7bit

<事業者>１８禁ＪＡＰＡＮ
<e-mail>delmail@18kin.jp
メール配信停止は下記アドレスより配信の停止をお願い致します。
■配信停止アドレス： http://e-dm.org/news/e-news
メールで拒否は件名に「停止希望」で本文に停止希望アドレスを記載下さい。
(※そのまま返信では削除がされません。WEBからの停止の方が処理が早いです）
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
夫婦・恋人と大人の時間を楽しめる
アダルトグッズやインディーズDVDも勢揃い！
また欲しいものなどご要望がありましたら
ドンドン教えてくださいネ！
18禁JAPAN入り口
http://18kin.jp
------=_Part_165258_6893572.1076064866744
Content-Type: text/html; charset=ISO-2022-JP
Content-Transfer-Encoding: quoted-printable

<font size=3D"2">&lt;=1B$B;v6H<T=1B(B&gt;=1B$B#1#86X#J#A#P#A#N=1B(B<br>
&lt;e-mail&gt;delmail@18kin.jp<br>
=1B$B%a!<%kG[?.Dd;_$O2<5-%"%I%l%9$h$jG[?.$NDd;_$r$*4j$$CW$7$^$9!#=1B(B<br>
=1B$B"#G[?.Dd;_%"%I%l%9!'=1B(B http://e-dm.org/news/e-news<br>
=1B$B%a!<%k$G5qH]$O7oL>$K!VDd;_4uK>!W$GK\J8$KDd;_4uK>%"%I%l%9$r5-:\2<$5$$!#=
=1B(B<br>
(=1B$B"($=3D$N$^$^JV?.$G$O:o=3D|$,$5$l$^$;$s!#=1B(BWEB=1B$B$+$i$NDd;_$NJ}$,=
=3DhM}$,Aa$$$G$9!K=1B(B</font><hr color=3D"#000000" width=3D"630" align=3D"=
left"><table id=3D"AutoNumber1" style=3D"BORDER-COLLAPSE: collapse" cellPad=
ding=3D"2" width=3D"630" border=3D"0">
<tr>
<td width=3D"100%" colSpan=3D"2"><a href=3D"http://18kin.jp">
<img src=3D"http://av.18kin.jp/mail/20040121/img/bt_title.gif" border=3D"0"=
 width=3D"630" height=3D"113"><br>
<img src=3D"http://av.18kin.jp/mail/20040121/img/ban.gif" border=3D"0" widt=
h=3D"630" height=3D"212"></a></td>
</tr>
<tr>
<td width=3D"100%" colSpan=3D"2"><hr color=3D"#000000" SIZE=3D"1"></td>
</tr>
<tr>
<td align=3D"middle" width=3D"100%" colSpan=3D"2"><font color=3D"#000080"><=
b>
=1B$B$*;E;v!&JY3X$*Hh$lMM$G$9!A!#:G6a!"$4L5:;BA$JCK@-$NJ}$K%*%9%9%a$N%[!<%k=
$r=1B(B<br>
=1B$BD6FCJL%W%i%$%9$K$FBgJt;E!*Ib5$$O$$$1$^$;$s$,!"$3$l$J$i1|MMJ}!&Nx?M$b=
=1B(B<br>
=1B$B5v$7$F$$$?$@$1$k$N$G$O!*!)!J!0!0!6!K=1B(B<br>
24=1B$B;~4V=1B(B</b></font><b><font color=3D"#ff0000">=1B$B$$$D$G$bH4$-J|Bj=
=1B(B</font><font color=3D"#000080">=1B$B!*=1B(B</font></b><strong><u><font=
 color=3D"#ff00ff">=1B$B?M9)HiIf$GCi<B$K:F8=3D$7$?=3Dw$N;R$N%"%=3D%3$r0B$/$=
4Ds6!=1B(B</font></u><font color=3D"#000080">=1B$B!*=1B(B<br>
=1B$BK\J*0J>e$N%j%"%k$JBN83$r;n6!2A3J$G@'Hs!"$40&MQ$/$@$5$$!#=1B(B<br>
</font><font color=3D"#ff0000" size=3D"5">=1B$B"#:#2s$N%*%9%9%aIJ=1B(B6=1B$=
BE@!*A4$F?tNL8BDj$G$9!*"#=1B(B<br>
</font><font color=3D"#0000ff">=1B$BCQ$:$+$7$J$,$i!"0l@87|L?%3%a%s%H$7$^$7$=
?$N$G:G8e$^$GFI$s$G%M!#=1B(B</font></strong><font color=3D"#0000ff"><b>(*=
=3D^^=3D*)</b></font></td>
</tr>
<tr>
<td width=3D"100%" colSpan=3D"2"><hr color=3D"#000000" SIZE=3D"1"></td>
</tr>
<tr>
<td width=3D"250" rowSpan=3D"5">
<img src=3D"http://av.18kin.jp/mail/20040121/3.jpg" border=3D"0" width=3D"2=
50" height=3D"250"></td>
<td width=3D"380" bgColor=3D"#ff9900"><b>=1B$B%d%s%0%P!<%8%s#N=1B(Bo.4</b><=
/td>
</tr>
<tr>
<td width=3D"380"><font color=3D"#000000">=1B$B!ZDj2A=1B(B12000=1B$B1_!["M=
=1B(B</font><b><font color=3D"#ff0000" size=3D"5">7</font></b><font color=
=3D"#ff0000" size=3D"5"><b>,800=1B$B1_=1B(B</b></font><b><font color=3D"#ff=
0000">=1B$B!Z=1B(B35%OFF=1B$B![=1B(B10=1B$B8D8BDj=1B(B</font></b></td>
</tr>
<tr>
<td width=3D"380"><font color=3D"#0000ff"><b>
=1B$B$3$l$O<B$K$*Gc$$F@$G$9$h!#8+$F%j%"%k!&BN46$7$F$^$?$^$?D6%j%"%k!*%W%C%7=
!<!u%"%J%k!"$I$A$i$+$i96$a$F$b$?$^$i$J$$2w46$rLsB+$7$^$9!#IUB0%m!<%?!<$G$5$=
i$J$k2w46$r!*;d$N<g?M$b$*5$$KF~$j$G$9!#=1B(B</b></font><br>
=1B$B>&IJ%5%$%:=1B(B/=1B$B1|9T=1B(B16.0=1B$B#x2#I}=1B(B12.0=1B$B#x9b$5=1B(B=
7.5cm<br>
=1B$B=3DENL=1B(B/=1B$B#0!%#6#k#g=1B(B</td>
</tr>
<tr>
<td width=3D"380"><font color=3D"#000000">&nbsp;</font>=1B$B%Q%C%1!<%8%5%$%=
:=1B(B/21.5x9.5x31.0cm</td>
</tr>
<tr>
<td width=3D"380"><font color=3D"#000000" size=3D"2">
<img src=3D"http://av.18kin.jp/image/kago2.gif" border=3D"0" width=3D"150" =
height=3D"40"></font></td>
</tr>
<tr>
<td width=3D"100%" colSpan=3D"2"><hr color=3D"#000000" SIZE=3D"1"></td>
</tr>
<tr>
<td width=3D"250" rowSpan=3D"5">
<a href=3D"http://av.18kin.jp/18kin/goodsprev.cgi?gno=3D1064">
<img src=3D"http://av.18kin.jp/mail/20040121/1.jpg" border=3D"0" width=3D"2=
50" height=3D"250"></a></td>
<td width=3D"380" bgColor=3D"#ff9900"><b>=1B$B<BO?!*#1=1B(B/=1B$B#4LZEg=3Dc=
;R!!Le=1B(B</b></td>
</tr>
<tr>
<td width=3D"380"><font color=3D"#000000">=1B$B!ZDj2A=1B(B20000=1B$B1_!["M=
=1B(B</font><b><font color=3D"#ff0000" size=3D"5">13,800=1B$B1_=1B(B</font>=
<font color=3D"#ff0000">=1B$B!Z=1B(B31%OFF=1B$B![=1B(B5=1B$B8D8BDj=1B(B</fo=
nt></b></td>
</tr>
<tr>
<td width=3D"380"><b><font color=3D"#0000ff">
1/4=1B$B%5%$%:$G$3$N2A3J$O%*%9%9%a$G$9!#=1B(B!=1B$BM6OG$r$=3D$=3D$k%;%/%7!<=
$J%]!<%:!*;d$b4iIi$1$NH472$J%9%?%$%k$G$9!#CV$$$F;H$($k$N$G<BA)$5$J$,$i$N5?;=
wBN83$,$G$-$kK\3JGI%U%#%.%e%"%[!<%k!*!*5.J}$N%O!<%I$J96$a$KMg?H$,%W%k%W%kLe=
$($^$9!*=1B(B</font></b><br>
=1B$B=3DENL!'#1!%#7=1B(Bkg<br>
=1B$B>&IJ%5%$%:!'D9$5=1B(B 22.5x=1B$BB@$5=1B(B 14.0cm</td>
</tr>
<tr>
<td width=3D"380">=1B$B%Q%C%1!<%8%5%$%:!(=1B(B25x15x16.5cm</td>
</tr>
<tr>
<td width=3D"380"><font color=3D"#000000" size=3D"2">
<a href=3D"http://av.18kin.jp/18kin/goodsprev.cgi?gno=3D1064">
<img src=3D"http://av.18kin.jp/image/kago2.gif" border=3D"0" width=3D"150" =
height=3D"40"></a></font></td>
</tr>
<tr>
<td width=3D"630" colSpan=3D"2"><hr color=3D"#000000" SIZE=3D"1"></td>
</tr>
<tr>
<td width=3D"250" rowSpan=3D"5">
<a href=3D"http://av.18kin.jp/18kin/goodsprev.cgi?gno=3D1066">
<img src=3D"http://av.18kin.jp/mail/20040121/2.jpg" border=3D"0" width=3D"2=
50" height=3D"250"></a></td>
<td width=3D"380" bgColor=3D"#ff9900"><b>=1B$B<BO?!*#1=1B(B/=1B$B#4LZEg=3Dc=
;R!!@d=1B(B</b></td>
</tr>
<tr>
<td width=3D"380"><font color=3D"#000000">=1B$B!ZDj2A=1B(B18,000=1B$B1_!["M=
=1B(B</font><b><font color=3D"#ff0000" size=3D"5">13,800=1B$B1_=1B(B</font>=
<font color=3D"#ff0000">=1B$B!Z=1B(B23%OFF=1B$B![=1B(B5=1B$B8D8BDj=1B(B</fo=
nt></b></td>
</tr>
<tr>
<td width=3D"380"><font color=3D"#0000ff"><b>
=1B$B$3$A$i$b=1B(B1/4=1B$B%5%$%:$H%*%9%9%a$G$9=1B(B!=1B$B%=3D%U%!!<$KMg?H$r=
4s$;$?M6OG$r$=3D$=3D$k%;%/%7!<$J%]!<%:!*@5>o0L9%$-$J5.J}$K$O:G9b$N%U%#%.%"%=
[!<%k$G$9!#K-K~$J%P%9%H$r0&Io$9$k$b%b%_%b%_$9$k$b5.J}$N$d$j$?$$J|Bj!*5.J}$N=
%O!<%I$J96$a$KMg?H$,%W%k%W%kLe$($^$9!*=1B(B</b></font><br>
=1B$B=3DENL!'#1!%#6=1B(Bkg<br>
=1B$B>&IJ%5%$%:!'D9$5=1B(B 23.0x=1B$BB@$5=1B(B 13.0cm</td>
</tr>
<tr>
<td width=3D"380">=1B$B%Q%C%1!<%8%5%$%:!(=1B(B24.5x10.5x19.5cm</td>
</tr>
<tr>
<td width=3D"380"><font color=3D"#000000" size=3D"2">
<a href=3D"http://av.18kin.jp/18kin/goodsprev.cgi?gno=3D1066">
<img src=3D"http://av.18kin.jp/image/kago2.gif" border=3D"0" width=3D"150" =
height=3D"40"></a></font></td>
</tr>
<tr>
<td width=3D"630" colSpan=3D"2"><hr color=3D"#000000" SIZE=3D"1"></td>
</tr>
<tr>
<td align=3D"middle" width=3D"630" colSpan=3D"2"><b><font color=3D"#ff0000"=
>
=1B$B%-%e!<%H$G%;%/%7!<$J%_%K%Z%C%H$J$i!"7HBS@-$K$bHs>o$KJXMx$G!"FC$KC1?H%5=
%i%j!<%^%s!&N>?FF15o$N3X@8$NJ}$NHhO+$rL~$7$F$/$l$k%"%$%F%`$H$7$FBg?M5$!*9%$=
_$N%?%$%W$O!)=1B(B</font></b>
</td>
</tr>
<tr>
<td width=3D"630" colSpan=3D"2">
<table id=3D"AutoNumber2" style=3D"BORDER-COLLAPSE: collapse" cellSpacing=
=3D"3" cellPadding=3D"2" width=3D"100%" border=3D"0">
<tr>
<td align=3D"middle" width=3D"210" bgColor=3D"#ff9900"><b>
<font color=3D"#000000" size=3D"2">=1B$B$_$k$-$#%,!<%k%:!*!!%"%f%_=1B(B</fo=
nt></b></td>
<td align=3D"middle" width=3D"210" bgColor=3D"#ff9900"><b><font size=3D"2">
=1B$B=3DO=3Dw!A?M:J!&>.Lk;R!A=1B(B</font></b></td>
<td align=3D"middle" width=3D"210" bgColor=3D"#ff9900"><b><font size=3D"2">
=1B$B<c:J!A<c:J!&M3H~!A=1B(B</font></b></td>
</tr>
<tr>
<td align=3D"middle" width=3D"210">
<a href=3D"http://av.18kin.jp/18kin/goodsprev.cgi?gno=3D705">
<img src=3D"http://av.18kin.jp/mail/20040121/4.jpg" border=3D"0" width=3D"2=
00" height=3D"200"></a></td>
<td align=3D"middle" width=3D"210">
<a href=3D"http://av.18kin.jp/18kin/goodsprev.cgi?gno=3D726">
<img src=3D"http://av.18kin.jp/mail/20040121/5.jpg" border=3D"0" width=3D"2=
00" height=3D"200"></a></td>
<td align=3D"middle" width=3D"210">
<a href=3D"http://av.18kin.jp/18kin/goodsprev.cgi?gno=3D725">
<img src=3D"http://av.18kin.jp/mail/20040121/6.jpg" border=3D"0" width=3D"2=
00" height=3D"200"></a></td>
</tr>
<tr>
<td align=3D"middle" width=3D"210"><font color=3D"#000000" size=3D"2">=1B$B=
!ZDj2A=1B(B4500=1B$B1_!["M=1B(B</font><b><font color=3D"#ff0000" size=3D"5"=
>3,480=1B$B1_=1B(B</font></b></td>
<td align=3D"middle" width=3D"210"><font color=3D"#000000" size=3D"2">=1B$B=
!ZDj2A=1B(B4500=1B$B1_!["M=1B(B</font><b><font color=3D"#ff0000" size=3D"5"=
>3,480=1B$B1_=1B(B</font></b></td>
<td align=3D"middle" width=3D"210"><font color=3D"#000000" size=3D"2">=1B$B=
!ZDj2A=1B(B4500=1B$B1_!["M=1B(B</font><b><font color=3D"#ff0000" size=3D"5"=
>3,480=1B$B1_=1B(B</font></b></td>
</tr>
<tr>
<td width=3D"210"><font color=3D"#000000" size=3D"2">=1B$B%5%i%5%i$N$*H)$N4=
63P!"$5$o$j?4CO$bK\J*$=3D$C$/$j!*=1B(B<br>
=1B$B%W%i%1!<%9=1B(B/18=1B$B#x=1B(B13=1B$B#x=1B(B6.9cm</font></td>
<td width=3D"210"><font color=3D"#000000" size=3D"2">
=1B$B1|MM%7%j!<%:!*%5%i%5%i$N$*H)$N463P!"$5$o$j?4CO$bK\J*$=3D$C$/$j!*=1B(B<=
br>
=1B$B%1!<%9%5%$%:=1B(B/=1B$B!!=1B(B165x110x57mm </font></td>
<td width=3D"210"><font color=3D"#000000" size=3D"2">
=1B$B1|MM%7%j!<%:!*%5%i%5%i$N$*H)$N463P!"$5$o$j?4CO$bK\J*$=3D$C$/$j!*=1B(B<=
br>
=1B$B%1!<%9%5%$%:=1B(B/=1B$B!!=1B(B165x110x57mm</font></td>
</tr>
<tr>
<td align=3D"middle" width=3D"210"><font color=3D"#000000" size=3D"2">
<a href=3D"http://av.18kin.jp/18kin/goodsprev.cgi?gno=3D705">
<img src=3D"http://av.18kin.jp/image/kago2.gif" border=3D"0" width=3D"150" =
height=3D"40"></a></font></td>
<td align=3D"middle" width=3D"210"><font color=3D"#000000" size=3D"2">
<a href=3D"http://av.18kin.jp/18kin/goodsprev.cgi?gno=3D726">
<img src=3D"http://av.18kin.jp/image/kago2.gif" border=3D"0" width=3D"150" =
height=3D"40"></a></font></td>
<td align=3D"middle" width=3D"210"><font color=3D"#000000" size=3D"2">
<a href=3D"http://av.18kin.jp/18kin/goodsprev.cgi?gno=3D725">
<img src=3D"http://av.18kin.jp/image/kago2.gif" border=3D"0" width=3D"150" =
height=3D"40"></a></font></td>
</tr>
</table>
</td>
</tr>
<tr>
<td width=3D"630" colSpan=3D"2"><hr color=3D"#000000" SIZE=3D"1"></td>
</tr>
<tr>
<td align=3D"middle" width=3D"630" colSpan=3D"2"><font size=3D"6">
=1B$B$=3D$NB>!"IWIX!&Nx?M$HBg?M$N;~4V$r3Z$7$a$k=1B(B<br>
=1B$B%"%@%k%H%0%C%:$d%$%s%G%#!<%:=1B(BDVD=1B$B$b@*B7$$!*=1B(B<b><br>
=1B$B$^$?M_$7$$$b$N$J$I$4MWK>$,$"$j$^$7$?$i=1B(B<br>
=1B$B%I%s%I%s65$($F$/$@$5$$%M!*=1B(B<br>
<a href=3D"http://18kin.jp"><font color=3D"#ff0000">18=1B$B6X=1B(BJAPAN=1B$=
BF~$j8}=1B(B</font></a></b></font></td>
</tr>
</table>
------=_Part_165258_6893572.1076064866744--

