Return-path: <bigtrail777@yahoo.co.jp>
From: bigtrail777@yahoo.co.jp
Subject: =?ISO-2022-JP?B?GyRCMysbKEobJEI2SBsoShskQjxUGyhKGyRCJCwbKEo=?=
 =?ISO-2022-JP?B?GyRCQjMbKEobJEI9UBsoShskQiQ3GyhKGyRCJEYbKEo=?=
 =?ISO-2022-JP?B?GyRCJCQbKEobJEIkXhsoShskQiQ5GyhKGyRCISobKEo=?=
Sender: bigtrail777@yahoo.co.jp
To: test@example.com
Reply-to: bigtrail777@yahoo.co.jp
Message-id: <VICTORYSbh29cM3oryK00000412@SMTP>
MIME-version: 1.0
X-Mailer: <WinNT's Blat ver 1.7J>
Content-type: text/plain; charset=iso-2022-jp
X-OriginalArrivalTime: 28 Aug 2004 05:15:35.0281 (UTC)
 FILETIME=[0C649610:01C48CBE]



 未承諾広告※ ご迷惑な方は削除してください。
受信拒否(購読解除）の方は下記のURLか又はホームページ本文
　　　　よりお願いいたします 　
http://bestmail.mydns.jp/scripts/deleteform.html
http://beingmail.dyndns.dk/scripts/deleteform.html
販売者　メディア　
   所在地　京都府城陽市寺田８−２
   代表者　山本しおり　　
　　TEL  0774-55-6699
　8月中に収集した30万メール＋50万メールをサービス中！
こんなに簡単に独立できる仕事は他にありません！　
ビジネスの鉄則です。１番電車に乗り遅れても２番電車には乗り遅れるな！!
資本金の要らないビジネスです！
情報化の時代,情報ビジネスは創造の泉です。溢れんばかりのエネルギー
です。百聞は一見に如かずです。一度見てください！

       http://bestmail.mydns.jp/
     
       http://beingmail.dyndns.dk/
         
     

     





　　　　
      
