From: =?iso-2022-jp?q?=83N=83=8C=83A_<rtn@rtn.mydns.jp>?=
To: test@example.com
Reply-To: rtn@rtn.mydns.jp
Subject: =?iso-2022-jp?q?=81y=92=B4=83}=83j=83A=81z=8C=83=88=C0=81=9A=97=A0=83r=83f=83I=81=9A=94=CC=94=84?=
Date: Mon, 22 Mar 2004 07:47:43 +0900
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="cf49d7a3-0d53-4c67-83a7-c85ea0e5cfe1"
Status: RO


This is a multi-part message in MIME format
--cf49d7a3-0d53-4c67-83a7-c85ea0e5cfe1
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
    filename="=?iso-2022-jp?B?XxskQjYoTk8ycTxSTVcwdzhEP00lOSUtJWs+cEpzGyhCXzM5MDcueGxz?="

--cf49d7a3-0d53-4c67-83a7-c85ea0e5cfe1
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
    filename="=?iso-2022-jp?B?XyAgICAgICAkQjZOTzJxUk1XMHc4RE0lOSUtJWtwSnNCXzM5MDcueGxz?="

--cf49d7a3-0d53-4c67-83a7-c85ea0e5cfe1--
