From: test@example.com
To: test@example.com
Subject: =?iso-2022-jp?B?GyRCIXpOKTJxMzBKLEdkPHVJVUNmISolKCE8ISYlIiVzGyhK?=
 =?iso-2022-jp?B?GyRCJUkhJiUiJSQhISU3JTklRiVgGyhKKDQ3NzMbJEIhSyFaGyhKRRskQiF2GyhK?=
 =?iso-2022-jp?B?GyRCJUglbCE8JUk+Wjd0IVsbKEoA?=
Reply-To: test@example.com
MIME-Version: 1.0
Content-Type: text/plain; charset=iso-2022-jp
Content-Transfer-Encoding: 7bit
Date: Mon, 13 Sep 2004 20:42:37 +0900 (JST)


