Return-path: <bigtrail2000@yahoo.co.jp>
Date: Sun, 18 Apr 2004 03:45:14 +0900
From: =?ISO-2022-JP?B?GyRCJU0lQyVIJVMlOCVNJTkbKEIg?= <bigtrail2000@yahoo.co.jp>
Subject: =?ISO-2022-JP?B?GyRCTCQ+NUJ6OS05cCIoIzFLfDFfJEczKxsoQg==?=
 =?ISO-2022-JP?B?GyRCNkgkNyReJDskcyQrISobKEI=?=
To: test@example.com
Message-id: <20040417.1845140296@bigtrail2000-yahoo.co.jp>
MIME-version: 1.0
X-Mailer: Eudora 5.12
Content-type: text/plain; charset=ISO-2022-JP
X-OriginalArrivalTime: 17 Apr 2004 18:45:14.0484 (UTC)
 FILETIME=[1EE9F340:01C424AC]


 販売者　　　　ネットビジネス　
 代表者　　　　鈴木　沙世
 所在地　　　　京都市西京区下津林番条１００−１
 電話          0774-55-7505        
未承諾広告※　　　　　　　　
　このメールを受信拒否の方は次のメール宛に受信拒否として
  ご送信ください　gomennasai79@yahoo.co.jp
　
    現代は情報の時代です。
　大量販売で価格が超安値です！時価15万円以上はします！　
　貴方も大飛躍してみませんか！
　その気になれば足元にお金が落ちていますよ！！
   
           http://redsun.ddo.jp/
           

     
