From: test@test.com
To: someone@somewhere.com
Subject: test for various HTML parts

<html>

<head>
<meta content="charset=characters">
<title>This is the title</title>
</head>

<body background="http://www.bodybackground.com/foo.gif" bgsound="http://www.bodysound.com/noise.mp3">

<img alt="image tag ALT string"><img width="123"><img height="456">

<table background="http://www.tablebackground.com/bar.gif"><tr><td background="http://www.tdbackground.com/baz.gif"></td></tr></table>

<form action="mailto:someone@outthere.com"></form>

</body>
</html>