# ---------------------------------------------------------------------------------------------
#
# Test script for the HTML interface, loaded by TestHTML.tst
#
# Copyright (c) 2003 John Graham-Cumming
#
#   This file is part of POPFile
#
#   POPFile is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   POPFile is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with POPFile; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# ---------------------------------------------------------------------------------------------

# To simplify testing the POPFile HTML UI this file contains a script
# that is read by TestHTML.tst and executed.  The script consists of instructions
# for specific URLs that are to be hit and instructions for how to match the
# result that comes back
#
# The commands are as follows
#
# URL <url>         Set the URL that is to be fetched
# GET               Gets the last set URL
# MATCH <data>      Match the return from last URL fetch against the data
# MATCH/ENDMATCH    Encloses a block of test to find in the return from the last URL fetch
# CODE/ENDCODE      Arbitrary code that should be executed
# INPUTIS a b       Assert that form item a has value b
# SETINPUT a b      Sets the form item a to value b
# SUBMIT a          Finds the form with input a and submits it
# SETSUBMIT a b     Just like doing SETINPUT a b followed by SUBMIT a
# CONFIGIS a b      Verify that config item a has value b
#
# Expect that the following are available to you within the MATCH/ENDMATCH block
#
# $port             The port on which the HTML interface is running
# $url              URL object for the last URL specified
# $content          String containing the return from the last URL fetch
# $sk               The current HTML UI session key
# $version          Same as $h->version()

# Test the simplest functionality of the HTML interface

# Look for elements that should appear at the TOP and BOTTOM
# of every page

URL http://127.0.0.1:$port
GET

# Common TOP parts

MATCH <title>POPFile Control Center</title>
MATCH <html lang="en">
MATCH <meta http-equiv="Pragma" content="no-cache">
MATCH <meta http-equiv="Expires" content="0">
MATCH <meta http-equiv="Cache-Control" content="no-cache">
MATCH <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
MATCH <link rel="stylesheet" type="text/css" href="skins/SimplyBlue.css" title="SimplyBlue">
MATCH <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
MATCH <link rel="icon" href="popfile.ico" type="image/ico">

# Common MIDDLE parts (i.e. the tabs)

MATCH <a class="menuLink" href="/history?session=$sk&amp;setfilter=">
MATCH History</a>
MATCH <a class="menuLink" href="/buckets?session=$sk">
MATCH Buckets</a>
MATCH <a class="menuLink" href="/magnets?session=$sk&amp;start_magnet=0">
MATCH Magnets</a>
MATCH <a class="menuLink" href="/configuration?session=$sk">
MATCH Configuration</a>
MATCH <a class="menuLink" href="/security?session=$sk">
MATCH Security</a>
MATCH <a class="menuLink" href="/advanced?session=$sk">
MATCH Advanced</a>

# Common BOTTOM parts

MATCH <a class="bottomLink" href="manual/en/manual.html">
MATCH <br>$version<br>

# Verify that each of the pages highlights the correct item on
# the tab bar and hence the simplest level of page serving is working
# correctly

URL http://127.0.0.1:$port/history
GET
MATCH
<td class="menuSelected" align="center">
<a class="menuLink" href="/history?session=$sk&amp;setfilter=">
ENDMATCH

URL http://127.0.0.1:$port/buckets
GET
MATCH
<td class="menuSelected" align="center">
<a class="menuLink" href="/buckets?session=$sk">
ENDMATCH

URL http://127.0.0.1:$port/magnets
GET
MATCH
<td class="menuSelected" align="center">
<a class="menuLink" href="/magnets?session=$sk&amp;start_magnet=0">
ENDMATCH

URL http://127.0.0.1:$port/configuration
GET
MATCH
<td class="menuSelected" align="center">
<a class="menuLink" href="/configuration?session=$sk">
ENDMATCH

URL http://127.0.0.1:$port/security
GET
MATCH 
<td class="menuSelected" align="center">
<a class="menuLink" href="/security?session=$sk">
ENDMATCH

URL http://127.0.0.1:$port/advanced
GET
MATCH
<td class="menuSelected" align="center">
<a class="menuLink" href="/advanced?session=$sk">
ENDMATCH

# TODO History Page

# TODO Check for existence of messages
# TODO Check the page navigator
# TODO Check refresh
# TODO Check search
# TODO Check filter
# TODO Check reclassification
# TODO Check delete some messages
# TODO Check delete page of messages
# TODO Check delete all messages
# TODO Check sorting
# TODO Check click through from bucket name

# TODO single message view for accuracy
# TODO reclassify from single message view

# TODO Buckets Page

# TODO Basic bucket test to verify that the buckets in the test corpus
# are present on the bucket page with the right numbers
# TODO Check statistics displayed correctly
# TODO Check operation of Subject Modification
# TODO Check operation of Quarantine
# TODO Check operation of color change
# TODO Check Reset Statistics
# TODO Check bucket creation
# TODO Check bucket rename
# TODO Check bucket delete
# TODO Check word lookup

# TODO Check individual bucket page for accuracy
# TODO Check clearing of individual bucket

# TODO Magnets Page

# TODO Check that predefined magnets are presetn
# TODO Check magnet creation
# TODO Check magnet change value
# TODO Check magnet change type
# TODO Check magnet change bucket
# TODO Check magnet deletion

# TODO Configuration Page

URL http://127.0.0.1:$port/configuration
GET

# TODO Check skin change
# TODO Check language change
# TODO Check logger change
# TODO Check history lines change
# TODO Check history days change
# TODO Check change timeout

# Check change POP3 port

INPUTIS   pop3_port 110
CONFIGIS  pop3_port 110
SETSUBMIT pop3_port 111
INPUTIS   pop3_port 111
CONFIGIS  pop3_port 111
SETSUBMIT pop3_port 0
MATCH The POP3 listen port must be a number between 1 and 65535
INPUTIS   pop3_port 111

# TODO Check change separator
# TODO Check Subject Line Modification
# TODO Check XTC
# TODO Check XPL
# TODO Check XMLRPC port
# TODO Check UI port

INPUTIS ui_port $port

# TODO Check SMTP port
# TODO Check NNTP port
# TODO Check NNTP separator
# TODO Check Windows icon

# TODO Security Page

# TODO Check POP3 stealth
# TODO Check SMTP stealth
# TODO Check NNTP stealth
# TODO Check XMLRPC stealth
# TODO Check UI stealth
# TODO Check POP3 AUTH options
# TODO Check SMTP chain options
# TODO Check autoupdate
# TODO Check stastitics sending
# TODO Check password

# TODO Advanced Page

# TODO Check presence of ignore words
# TODO Check add ignore word
# TODO Check remove ignore word
# TODO Check change arbitrary parameter

# TODO Check shutdown operation
# TODO Check bad session key