# ---------------------------------------------------------------------------------------------
#
# Test script for the HTML interface, loaded by TestHTML.tst
#
# Copyright (c) 2003 John Graham-Cumming
#
#   This file is part of POPFile
#
#   POPFile is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   POPFile is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with POPFile; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# ---------------------------------------------------------------------------------------------

# To simplify testing the POPFile HTML UI this file contains a script
# that is read by TestHTML.tst and executed.  The script consists of instructions
# for specific URLs that are to be hit and instructions for how to match the
# result that comes back
#
# The commands are as follows
#
# GET <url>         Get the URL (note the host and port will be added for you)
# MATCH <data>      Match the return from last URL fetch against the data
# NOTMATCH <data>   Must not match the return from last URL fetch against the data
# MATCH/ENDMATCH    Encloses a block of test to find in the return from the last URL fetch
# CODE/ENDCODE      Arbitrary code that should be executed
# INPUTIS a b       Assert that form item a has value b
# SETINPUT a b      Sets the form item a to value b
# SETINPUTN a b c   Sets the bth input named a to c
# SUBMIT a          Finds the form with input a and submits it
# SETSUBMIT a b     Just like doing SETINPUT a b followed by SUBMIT a
# CONFIGIS a b      Verify that config item a has value b
# SETCONFIG a b     Set config item a to b
# MAGNETIS a b c    Checks that magnet c exists in bucket a with type b
# PARAMETERIS a b c Check that parameter b in bucket a has value c
# CLICK a           Click the button called a
# SENDMSG a b       Send a message through the POPFile MQ (message a with parameter b)
#
# Expect that the following are available to you within the MATCH/ENDMATCH block
#
# $port             The port on which the HTML interface is running
# $url              URL object for the last URL specified
# $content          String containing the return from the last URL fetch
# $sk               The current HTML UI session key
# $version          Same as $h->version()

# Test the simplest functionality of the HTML interface

# Look for elements that should appear at the TOP and BOTTOM
# of every page

GET /

# Common TOP parts

MATCH <title>POPFile Control Center</title>
MATCH <html lang="en">
MATCH <meta http-equiv="Pragma" content="no-cache">
MATCH <meta http-equiv="Expires" content="0">
MATCH <meta http-equiv="Cache-Control" content="no-cache">
MATCH <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
MATCH <link rel="stylesheet" type="text/css" href="skins/SimplyBlue.css" title="SimplyBlue">
MATCH <link rel="icon" href="favicon.ico">

# Common MIDDLE parts (i.e. the tabs)

MATCH <a class="menuLink" href="/history?session=$sk&amp;setfilter=">
MATCH History</a>
MATCH <a class="menuLink" href="/buckets?session=$sk">
MATCH Buckets</a>
MATCH <a class="menuLink" href="/magnets?session=$sk&amp;start_magnet=0">
MATCH Magnets</a>
MATCH <a class="menuLink" href="/configuration?session=$sk">
MATCH Configuration</a>
MATCH <a class="menuLink" href="/security?session=$sk">
MATCH Security</a>
MATCH <a class="menuLink" href="/advanced?session=$sk">
MATCH Advanced</a>

# Common BOTTOM parts

MATCH <a class="bottomLink" href="manual/en/manual.html">
MATCH <br>$version<br>

# Verify that each of the pages highlights the correct item on
# the tab bar and hence the simplest level of page serving is working
# correctly

GET /history
MATCH
<td class="menuSelected" align="center">
<a class="menuLink" href="/history?session=$sk&amp;setfilter=">
ENDMATCH

GET /buckets
MATCH
<td class="menuSelected" align="center">
<a class="menuLink" href="/buckets?session=$sk">
ENDMATCH

GET /magnets
MATCH
<td class="menuSelected" align="center">
<a class="menuLink" href="/magnets?session=$sk&amp;start_magnet=0">
ENDMATCH

GET /configuration
MATCH
<td class="menuSelected" align="center">
<a class="menuLink" href="/configuration?session=$sk">
ENDMATCH

GET /security
MATCH
<td class="menuSelected" align="center">
<a class="menuLink" href="/security?session=$sk">
ENDMATCH

GET /advanced
MATCH
<td class="menuSelected" align="center">
<a class="menuLink" href="/advanced?session=$sk">
ENDMATCH

# History Page

GET /history

# Check for existence of messages, check that there
# are links from the bucket names, check that the basic
# sort options are present

MATCH &lt;no subject line&gt;
MATCH <a title="test\@test.com">test\@test.com</a>
MATCH Enlarge your package Doctor ApprovedNHOB...
MATCH &lt;no from line&gt;
MATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
MATCH VI ID: 24052  Status: Open  Sev: 2
MATCH <a href="buckets?session=$sk&amp;showbucket=spam"><font color="blue">spam</font></a>
MATCH &gt;ID
MATCH <a href="/history?session=$sk&amp;setsort=from">From</a>

# Check the page navigator

MATCH Jump to message: <b>1</b> [<a href="/history?start_message=20&amp;session=$sk">21</a>] [<a href="/history?start_message=20&amp;session=$sk">Next ></a>]
NOTMATCH XoSeXyGoDdEsSm\@hotmail.com
GET /history?start_message=20&amp;session=$sk
MATCH Jump to message: [<a href="/history?start_message=0&amp;session=$sk">< Previous</a>] [<a href="/history?start_message=0&amp;session=$sk">1</a>] <b>21</b>
MATCH XoSeXyGoDdEsSm\@hotmail.com
MATCH from: Leandro
NOTMATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
GET /history

# Check refresh

NOTMATCH Testing Refresh
MATCH (<a class="history" href="/history?session=$sk&amp;setfilter=">Refresh</a>)
CODE
open NEWMSG, ">messages/popfile10000=1.msg";
print NEWMSG <<EOM;
From: John
Subject: Testing Refresh

Body would go here

EOM
close NEWMSG;
open NEWCLS, ">messages/popfile10000=1.cls";
print NEWCLS "personal\n";
close NEWCLS;
ENDCODE
SENDMSG NEWFL popfile10000=1.msg
GET /history?session=$sk&amp;setfilter=
MATCH John
MATCH Testing Refresh
MATCH personal
MATCH popfile10000=1

# Check magnet classified mails

NOTMATCH Magnetic Attraction for Ferrous Females
MATCH (<a class="history" href="/history?session=$sk&amp;setfilter=">Refresh</a>)
CODE
open NEWMSG, ">messages/popfile10002=1.msg";
print NEWMSG <<EOM;
From: foo-magnet\@magnetmania.com
Subject: Magnetic Attraction for Ferrous Females

Align your pole to magnetic north
EOM
close NEWMSG;
open NEWCLS, ">messages/popfile10002=1.cls";
print NEWCLS "personal MAGNET from: foo\n";
close NEWCLS;
ENDCODE
SENDMSG NEWFL popfile10002=1.msg
GET /history?session=$sk&amp;setfilter=
MATCH foo-magnet\@magnetmania.com
MATCH Magnetic Attraction for Ferrous Females
MATCH personal
MATCH popfile10002=1
MATCH Magnet used: from: foo

GET /view?view=popfile10002=1.msg&amp;start_message=0&amp;session=$sk
MATCH Single Message View
MATCH foo-magnet\@magnetmania.com
MATCH Magnetic Attraction for Ferrous Females
MATCH Magnet used: from: foo
MATCH <font color="green">foo</font>

# Check search

SETSUBMIT search isnotpresent
MATCH searched for from/subject isnotpresent
MATCH No messages.
NOTMATCH Jump to message
CLICK reset_filter_search
NOTMATCH searched for from/subject
NOTMATCH No messages.
MATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
MATCH Jump to message

SETSUBMIT search test.com
MATCH searched for from/subject test.com
MATCH test\@test.com
NOTMATCH Enlarge your package Doctor ApprovedNHOB...
NOTMATCH Jump to message
CLICK reset_filter_search
NOTMATCH searched for from/subject
NOTMATCH No messages.
MATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
MATCH Jump to message

SETSUBMIT search Doctor
MATCH searched for from/subject Doctor
NOTMATCH test\@test.com
MATCH Enlarge your package Doctor ApprovedNHOB...
NOTMATCH Jump to message
CLICK reset_filter_search
NOTMATCH searched for from/subject
NOTMATCH No messages.
MATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
MATCH Jump to message

# Check filter

SETINPUT filter personal 
CLICK setfilter
MATCH (just showing bucket <font color="green">personal</font>)
NOTMATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
MATCH Testing Refresh
CLICK reset_filter_search
SETINPUT filter spam
CLICK setfilter
MATCH (just showing bucket <font color="blue">spam</font>)
MATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
NOTMATCH Testing Refresh
MATCH Jump to message: <b>1</b> [<a href="/history?start_message=20&amp;session=$sk&amp;filter=spam">21</a>] [<a href="/history?start_message=20&amp;session=$sk&amp;filter=spam">Next ></a>]
GET /history?start_message=20&amp;session=$sk&amp;filter=spam
NOTMATCH Testing Refresh
SETINPUT filter other 
CLICK setfilter
MATCH (just showing bucket <font color="red">other</font>)
MATCH No messages.
SETINPUT filter __filter__magnet
CLICK setfilter
MATCH (just showing magnet classified messages)
MATCH Magnetic Attraction for Ferrous Females
NOTMATCH Testing Refresh
SETINPUT filter __filter__no__magnet
CLICK setfilter
MATCH (just showing non-magnet classified messages)
NOTMATCH Magnetic Attraction for Ferrous Females
MATCH Testing Refresh
CLICK reset_filter_search

# Check sorting

MATCH <a href="/history?session=$sk&amp;setsort=bucket">Classification</a>
GET /history?session=$sk&amp;setsort=bucket
MATCH <a href="buckets?session=$sk&amp;showbucket=personal"><font color="green">personal</font></a>
MATCH <a href="/history?session=$sk&amp;setsort=-bucket"><em class="historyLabelSort">&gt;Classification</em></a>
GET /history?session=$sk&amp;setsort=-bucket
MATCH <a href="/history?session=$sk&amp;setsort=bucket"><em class="historyLabelSort">&lt;Classification</em></a>
NOTMATCH <a href="buckets?session=$sk&showbucket=personal"><font color="green">personal</font></a>
GET /history?session=$sk&amp;setsort=

# Check reclassification

GET /history
MATCH Testing Refresh
SETINPUT 1 spam
CLICK change
MATCH Changed to <font color="blue">spam</font>
MATCH Reclassified as <font color="blue">spam</font>

# Check undo

CLICK undo_1
MATCH Changed to <font color="green">personal</font>

# Check click through from bucket name

MATCH <a href="buckets?session=$sk&amp;showbucket=spam"><font color="blue">spam</font></a>
GET /buckets?session=$sk&showbucket=spam
MATCH Detail for <font color="blue">spam</font>
GET /history

# Single message view for accuracy

MATCH <a class="messageLink" title="Testing Refresh" href="/view?view=popfile10000=1.msg&amp;start_message=0&amp;session=$sk">Testing Refresh</a>
GET /view?view=popfile10000=1.msg&amp;start_message=0&amp;session=$sk
MATCH Single Message View
MATCH Testing Refresh
MATCH John
MATCH <font color=\"green\">personal</font>
MATCH Scores
MATCH 0.769209
MATCH 0.230763
MATCH 2.829186e-05
MATCH <font color="red">here</font>
NOTMATCH 0.3289
NOTMATCH 0.6697
MATCH <font color="black">John</font>
MATCH <font color="red">here</font>
MATCH Body would
GET /view?view=popfile10000=1.msg&amp;start_message=0&amp;session=$sk&amp;format=prob
MATCH showing word probabilities
MATCH 0.3289
MATCH 0.6697
GET /view?view=popfile10000=1.msg&amp;start_message=0&amp;session=$sk&amp;format=freq
MATCH showing word frequencies
MATCH 0.00165
MATCH 0.00336
GET /view?view=popfile10000=1.msg&amp;start_message=0&amp;session=$sk&amp;format=score
MATCH showing word scores
MATCH 2.3639
MATCH 2.6727

# Jump to message

GET /jump_to_message?view=popfile10000=1.msg
MATCH Single Message View
MATCH Testing Refresh
MATCH John
MATCH <font color=\"green\">personal</font>
MATCH Scores
MATCH 0.769209
MATCH 0.230763
MATCH 2.829186e-05
MATCH <font color="red">here</font>
NOTMATCH 0.3289
NOTMATCH 0.6697
MATCH <font color="black">John</font>
MATCH <font color="red">here</font>
# MATCH Body would

GET /jump_to_message?view=popfile10001=1.msg
NOTMATCH Single Message View
MATCH Recent Messages

# jump_to_message and a password

#GET /security
#INPUTIS password
#CONFIGIS html_password
#SETSUBMIT password secret
#GET /jump_to_message?view=popfile10000=1.msg
#MATCH Enter password:
#SETSUBMIT password secret
#MATCH Single Message View
#MATCH Testing Refresh
#SETCONFIG html_password
#GET /security
#SETSUBMIT password
#MATCH Updated password to

# Quick Magnets

GET /jump_to_message?view=popfile10000=1.msg
MATCH Single Message View
MATCH <option value="Testing">Testing</option>
MATCH <option value="Refresh">Refresh</option>
MATCH <option value="John">John</option>
SETINPUT text2 John
SETINPUT bucket2 other
CLICK create
MATCH Current Magnets
MATCH <input type="text" name="text1" value="John" size="50" />
SETINPUT remove1 on
CLICK delete

# Reclassify from single message view

GET /view?view=popfile10000=1.msg&amp;start_message=0&amp;session=$sk
MATCH Single Message View
MATCH Testing Refresh
SETINPUT 1 spam
CLICK change
MATCH Changed to <font color="blue">spam</font>
MATCH Reclassified as <font color="blue">spam</font>

# Undo on single message view

GET /view?view=popfile10000=1.msg&amp;start_message=0&amp;session=$sk
MATCH Single Message View
CLICK undo_1
MATCH Changed to <font color="green">personal</font>

# Check delete one message

GET /history
MATCH Testing Refresh
SETINPUT remove_2 on
CLICK deletemessage
MATCH Recent Messages
NOTMATCH Testing Refresh

# Check delete some messages

MATCH test for various HTML parts
MATCH Enlarge your package Doctor ApprovedNHOB
SETINPUT remove_7 on
SETINPUT remove_8 on
CLICK deletemessage
NOTMATCH test for various HTML parts
NOTMATCH Enlarge your package Doctor ApprovedNHOB

# Check delete page of messages

GET /history
CLICK clearpage
MATCH <a href="buckets?session=$sk&amp;showbucket=spam"><font color="blue">spam</font></a>
NOTMATCH Jump to message: <b>1</b> [<a href="/history?start_message=20&amp;session=$sk">21</a>] [<a href="/history?start_message=20&amp;session=$sk">Next ></a>]

# Check delete all messages

CLICK clearall
MATCH No messages.

# Magnets Page

GET /magnets

# Check that predefined magnets are present

INPUTIS text1 foo
INPUTIS bucket1 personal
INPUTIS type1 from
INPUTIS text2 oldstyle
INPUTIS bucket2 personal
INPUTIS type2 from
INPUTIS text3 bar
INPUTIS bucket3 personal
INPUTIS type3 subject
INPUTIS text4 baz\@baz.com
INPUTIS bucket4 personal
INPUTIS type4 to

# Check magnet creation

SETINPUT  text0 newmagnet
SETINPUT  type0 subject
SETSUBMIT bucket0 spam
INPUTIS   text5 newmagnet
INPUTIS   type5 subject
INPUTIS   bucket5 spam
MAGNETIS  spam subject newmagnet

SETINPUT text0 foo
SETINPUT type0 from
SETSUBMIT bucket0 personal
MATCH Magnet 'from: foo' already exists in bucket 'personal' 

SETINPUT text0 fo
SETINPUT type0 from
SETSUBMIT bucket0 personal
MATCH New magnet 'from: fo' clashes with magnet 'from: foo' in bucket 'personal' and could cause ambiguous results.

# Check magnet change value

SETSUBMIT text5 newmagnetvalue
INPUTIS   text5 newmagnetvalue
INPUTIS   type5 subject
INPUTIS   bucket5 spam
MAGNETIS  spam subject newmagnetvalue
INPUTIS text1 foo
INPUTIS bucket1 personal
INPUTIS type1 from
INPUTIS text2 oldstyle
INPUTIS bucket2 personal
INPUTIS type2 from
INPUTIS text3 bar
INPUTIS bucket3 personal
INPUTIS type3 subject
INPUTIS text4 baz\@baz.com
INPUTIS bucket4 personal
INPUTIS type4 to

# Check magnet change type

SETSUBMIT type5 to
INPUTIS   type5 to
INPUTIS   text5 newmagnetvalue
INPUTIS   bucket5 spam
MAGNETIS  spam to newmagnetvalue
INPUTIS text1 foo
INPUTIS bucket1 personal
INPUTIS type1 from
INPUTIS text2 oldstyle
INPUTIS bucket2 personal
INPUTIS type2 from
INPUTIS text3 bar
INPUTIS bucket3 personal
INPUTIS type3 subject
INPUTIS text4 baz\@baz.com
INPUTIS bucket4 personal
INPUTIS type4 to

# Check magnet change bucket

SETSUBMIT bucket5 personal
INPUTIS   bucket5 personal
INPUTIS   text5 newmagnetvalue
INPUTIS   type5 to
MAGNETIS  personal to newmagnetvalue
INPUTIS text1 foo
INPUTIS bucket1 personal
INPUTIS type1 from
INPUTIS text2 oldstyle
INPUTIS bucket2 personal
INPUTIS type2 from
INPUTIS text3 bar
INPUTIS bucket3 personal
INPUTIS type3 subject
INPUTIS text4 baz\@baz.com
INPUTIS bucket4 personal
INPUTIS type4 to

# Check the magnet navigator

GET /configuration
SETSUBMIT page_size 3
GET /magnets
MATCH Jump to magnet page: <b>1</b> [<a href="/magnets?start_magnet=3&amp;session=$sk">2</a>] [<a href="/magnets?start_magnet=3&amp;session=$sk">Next ></a>]
GET /magnets?start_magnet=3&amp;session=$sk
MATCH Jump to magnet page: [<a href="/magnets?start_magnet=0&amp;session=$sk">< Previous</a>] [<a href="/magnets?start_magnet=0&amp;session=$sk">1</a>] <b>2</b> 
GET /configuration
SETSUBMIT page_size 20

# Check magnet deletion

GET /magnets
SETINPUT remove5 on
CLICK delete
NOTMATCH newmagnetvalue
NOTMATCH type5

SETINPUT remove1 on
SETINPUT remove3 on
CLICK delete
NOTMATCH "foo"
NOTMATCH bar
INPUTIS text1 oldstyle
INPUTIS bucket1 personal
INPUTIS type1 from
INPUTIS text2 baz\@baz.com
INPUTIS bucket2 personal
INPUTIS type2 to
NOTMATCH type3

# Configuration Page

GET /configuration

# Check skin change

MATCH <link rel="stylesheet" type="text/css" href="skins/SimplyBlue.css" title="SimplyBlue">
CONFIGIS html_skin SimplyBlue
SETSUBMIT skin default
MATCH <link rel="stylesheet" type="text/css" href="skins/default.css" title="default">
CONFIGIS html_skin default


# Check language change

MATCH <html lang="en">
CONFIGIS html_language English
SETSUBMIT language Francais
MATCH <html lang="fr">
CONFIGIS html_language Francais
SETSUBMIT language English
MATCH <html lang="en">
CONFIGIS html_language English

# Check logger change

INPUTIS   debug 2
CONFIGIS  GLOBAL_debug 1
SETSUBMIT debug 3
INPUTIS   debug 3
CONFIGIS  GLOBAL_debug 2
SETSUBMIT debug 4
INPUTIS   debug 4
CONFIGIS  GLOBAL_debug 3
SETSUBMIT debug 1
INPUTIS   debug 1
CONFIGIS  GLOBAL_debug 0

# Check history lines change

INPUTIS   page_size 20
CONFIGIS  html_page_size 20
SETSUBMIT page_size 30
INPUTIS   page_size 30
CONFIGIS  html_page_size 30
MATCH Updated number of messages per page to 30
SETSUBMIT page_size 0
MATCH The page size must be a number between 1 and 1000
INPUTIS   page_size 30

# Check history days change

INPUTIS   history_days 2
CONFIGIS  html_history_days 2
SETSUBMIT history_days 3
INPUTIS   history_days 3
CONFIGIS  html_history_days 3
MATCH Updated number of days of history to 3
SETSUBMIT history_days 0
MATCH The number of days in the history must be a number between 1 and 366
INPUTIS   history_days 3

# Check change timeout

INPUTIS   timeout 60
CONFIGIS  GLOBAL_timeout 60
SETSUBMIT timeout 61
INPUTIS   timeout 61
CONFIGIS  GLOBAL_timeout 61
MATCH Updated connection timeout to 61
SETSUBMIT timeout 0
MATCH The TCP timeout must be a number between 10 and 300
INPUTIS   timeout 61

# Check change POP3 port

INPUTIS   pop3_port 9110
CONFIGIS  pop3_port 9110
SETSUBMIT pop3_port 111
INPUTIS   pop3_port 111
CONFIGIS  pop3_port 111
MATCH Updated POP3 port to 111; this change will not take affect until you restart POPFile
SETSUBMIT pop3_port 0
MATCH The POP3 listen port must be a number between 1 and 65535
INPUTIS   pop3_port 111

# Check change separator

INPUTIS   pop3_separator :
CONFIGIS  pop3_separator :
SETSUBMIT pop3_separator ;
INPUTIS   pop3_separator ;
CONFIGIS  pop3_separator ;
MATCH Updated POP3 separator to ;
SETSUBMIT pop3_separator gg
MATCH The separator character must be a single character
INPUTIS   pop3_separator ;

# Check fork for POP3

INPUTIS   pop3_force_fork 1
CONFIGIS  pop3_force_fork 0
SETSUBMIT pop3_force_fork 0
INPUTIS   pop3_force_fork 1
CONFIGIS  pop3_force_fork 0
SETSUBMIT pop3_force_fork 1
INPUTIS   pop3_force_fork 0

# Check Subject Line Modification

INPUTIS subject 1
CONFIGIS GLOBAL_subject 1
SETSUBMIT subject 1
INPUTIS subject 2
CONFIGIS GLOBAL_subject 0

GET /buckets
MATCH Disabled globally

GET /configuration
SETSUBMIT subject 2
INPUTIS subject 1
CONFIGIS GLOBAL_subject 1

# Check XTC

INPUTIS xtc 1
CONFIGIS GLOBAL_xtc 1
SETSUBMIT xtc 1
INPUTIS xtc 2
CONFIGIS GLOBAL_xtc 0
SETSUBMIT xtc 2
INPUTIS xtc 1
CONFIGIS GLOBAL_xtc 1

# Check XPL

INPUTIS xpl 1
CONFIGIS GLOBAL_xpl 1
SETSUBMIT xpl 1
INPUTIS xpl 2
CONFIGIS GLOBAL_xpl 0
SETSUBMIT xpl 2
INPUTIS xpl 1
CONFIGIS GLOBAL_xpl 1

# Check UI port

INPUTIS   ui_port $port
CONFIGIS  html_port $port
SETSUBMIT ui_port 8081
INPUTIS   ui_port 8081
CONFIGIS  html_port 8081
MATCH Updated user interface web port to 8081; this change will not take affect until you restart POPFile
SETSUBMIT ui_port 0
MATCH The user interface port must be a number between 1 and 65535
INPUTIS   ui_port 8081

# Security Page

GET /security

# Check POP3 stealth

INPUTIS pop3_local 1
CONFIGIS pop3_local 1
SETSUBMIT pop3_local 1
INPUTIS pop3_local 2
CONFIGIS pop3_local 0
SETSUBMIT pop3_local 2
INPUTIS pop3_local 1
CONFIGIS pop3_local 1

# Check UI stealth

INPUTIS localui 1
CONFIGIS html_local 1
SETSUBMIT localui 1
INPUTIS localui 2
CONFIGIS html_local 0
SETSUBMIT localui 2
INPUTIS localui 1
CONFIGIS html_local 1

# Check POP3 AUTH options

INPUTIS   server
CONFIGIS  pop3_secure_server
SETSUBMIT server secure.com
INPUTIS   server secure.com
CONFIGIS  pop3_secure_server secure.com
MATCH Updated POP3 SPA/AUTH secure server to secure.com; this change will not take affect until you restart POPFile

INPUTIS   sport 110
CONFIGIS  pop3_secure_port 110
SETSUBMIT sport 111
INPUTIS   sport 111
CONFIGIS  pop3_secure_port 111
MATCH Updated POP3 SPA/AUTH port to 111; this change will not take affect until you restart POPFile
SETSUBMIT sport 0
INPUTIS   sport 111
CONFIGIS  pop3_secure_port 111
MATCH The port must be a number between 1 and 65535

# Check autoupdate

INPUTIS update_check 2
CONFIGIS html_update_check 0
SETSUBMIT update_check 1
INPUTIS update_check 2
CONFIGIS html_update_check 0
SETSUBMIT update_check 2
INPUTIS update_check 1
CONFIGIS html_update_check 1

# Check statistics sending

INPUTIS send_stats 2
CONFIGIS html_send_stats 0
SETSUBMIT send_stats 1
INPUTIS send_stats 2
CONFIGIS html_send_stats 0
SETSUBMIT send_stats 2
INPUTIS send_stats 1
CONFIGIS html_send_stats 1

# Check password

INPUTIS password
CONFIGIS html_password
SETSUBMIT password secret
CONFIGIS html_password secret
MATCH Updated password to secret
SETSUBMIT password
INPUTIS password
CONFIGIS html_password
MATCH Updated password to 

# Advanced Page

GET /advanced

# Check presence of ignore words

MATCH address
MATCH localhost
MATCH smtp

# Check add ignore word

CONFIGIS newword
SETSUBMIT newword four11@.-_
MATCH four11@.-_
SETSUBMIT newword ba"d
MATCH Ignored words can only contain alphanumeric, ., _, -, or @ characters

# Check remove ignore word

CONFIGIS word
SETSUBMIT word four11@.-_
NOTMATCH four11@.-_
SETSUBMIT word ba"d
MATCH Ignored words can only contain alphanumeric, ., _, -, or @ characters

# TODO Write better tests for stop words in Japanese
# and Korean

GET /configuration
SETSUBMIT language Nihongo
GET /advanced
MATCH address
MATCH localhost
MATCH smtp

GET /configuration
SETSUBMIT language Korean
GET /advanced
MATCH address
MATCH localhost
MATCH smtp

GET /configuration
SETSUBMIT language English

# Check change arbitrary parameter

GET /advanced
SETSUBMIT parameter_bayes_hostname testhostname
CONFIGIS bayes_hostname testhostname
INPUTIS parameter_bayes_hostname testhostname

# Buckets Page

GET /buckets

# Basic bucket test to verify that the buckets in the test corpus
# are present on the bucket page with the right numbers
#
#     Checks bucket names are present and the word and unique word
#     counts

MATCH spam
MATCH personal
MATCH other

MATCH <a href="/buckets?session=$sk&amp;showbucket=spam">
MATCH <a href="/buckets?session=$sk&amp;showbucket=personal">
MATCH <a href="/buckets?session=$sk&amp;showbucket=other">

MATCH >1,785<
MATCH >656<
MATCH >103<
MATCH >3<
MATCH >12,114<
MATCH >3,353<

MATCH >14,002<

# Check statistics displayed correctly

MATCH >1,785 (12.74%)<
MATCH >103 (0.73%)<
MATCH >12,114 (86.51%)<

MATCH <td bgcolor="red" title="other (12.74%)" width="12%"><img src="pix.gif" alt="" height="20" width="1" /></td>
MATCH <td bgcolor="green" title="personal (0.73%)" width="1%"><img src="pix.gif" alt="" height="20" width="1" /></td>
MATCH <td bgcolor="blue" title="spam (86.51%)" width="86%"><img src="pix.gif" alt="" height="20" width="1" /></td>

# Check Reset Statistics

MATCH <td align="right">132</td>
MATCH <td align="right">3</td>
MATCH <td align="right">97.72%</td>
CLICK reset_stats
MATCH >Not enough data<
MATCH >0 (  0.00%)<

# Check bucket creation

NOTMATCH newbucket0-_
SETSUBMIT cname newbucket0-_
MATCH newbucket0-_
MATCH Created bucket named newbucket0-_
MATCH newbucket0-_ current color is red

SETSUBMIT cname bu%cket
MATCH Bucket names can only contain the letters a to z in lower case
SETSUBMIT cname BUCKET
MATCH Bucket names can only contain the letters a to z in lower case

SETSUBMIT cname spam
MATCH Bucket named spam already exists

MATCH spam
MATCH personal
MATCH other

# Check bucket rename

SETINPUT oname newbucket0-_
SETSUBMIT newname sens%ible
MATCH Bucket names can only contain the letters a to z in lower case
SETINPUT oname newbucket0-_
SETSUBMIT newname sensible
MATCH Renamed bucket newbucket0-_ to sensible
MATCH sensible current color is blue

MATCH spam
MATCH personal
MATCH other

# Check bucket delete

SETSUBMIT name sensible
MATCH Deleted bucket sensible

GET /buckets

NOTMATCH sensible
MATCH spam
MATCH personal
MATCH other

# Check word lookup

SETSUBMIT word xxxxxx
MATCH <b>xxxxxx</b> does not appear in any of the buckets 
SETSUBMIT word used
MATCH <b>used</b> is most likely to appear in <font color="red">other</font>
MATCH 0.0005602241
MATCH 0.6873803233
MATCH 1.8945518529
MATCH Frequency

# Check operation of Subject Modification

SETSUBMIT name personal
MATCH Deleted bucket personal
SETSUBMIT name other
MATCH Deleted bucket other

INPUTIS subject 1
PARAMETERIS spam subject 1
SETSUBMIT subject 1
INPUTIS subject 2
PARAMETERIS spam subject 0
SETSUBMIT subject 2
INPUTIS subject 1
PARAMETERIS spam subject 1

# Check operation of Quarantine

INPUTIS quarantine 2
PARAMETERIS spam quarantine 0
SETSUBMIT quarantine 2
INPUTIS quarantine 1
PARAMETERIS spam quarantine 1
SETSUBMIT quarantine 1
INPUTIS quarantine 2
PARAMETERIS spam quarantine 0

# Check operation of color change

MATCH /buckets?color=feldspar&amp;bucket=spam&amp;session=$sk
GET /buckets?color=feldspar&amp;bucket=spam&amp;session=$sk
MATCH spam current color is feldspar

# Check individual bucket page for accuracy

MATCH /buckets?session=$sk&amp;showbucket=spam
GET /buckets?session=$sk&amp;showbucket=spam
MATCH Detail for <font color="feldspar">spam</font>
MATCH 12,114
MATCH (3,353 unique)
MATCH >100.00%<
MATCH <a href=/buckets?session=$sk&amp;showbucket=spam&amp;showletter=m><b>m</b></a>

GET /buckets?session=$sk&amp;showbucket=spam&amp;showletter=m
MATCH <a class="wordListLink" href="/buckets?session=$sk&amp;lookup=Lookup&amp;word=missouri#Lookup"><b>missouri</b></a>

# Check clearing of individual bucket

CLICK clearbucket
MATCH (0 unique)</td>

# Test removal of history files that are out of date (old and new style)

CODE
open TEMP, ">messages/popfile1_1.msg";
print TEMP, "1\n";
close TEMP;
open TEMP, ">messages/popfile1=1.msg";
print TEMP, "1\n";
close TEMP;
ENDCODE

SENDMSG TICKD dummy

# Check the login message

SENDMSG LOGIN iloggedin
GET /
MATCH - iloggedin)

# Check bad session key

GET /history?session=123456
MATCH POPFile Session Expired

# Get ICO, GIF, CSS, PNG, LOG and HTML file

CODE
open TEMP, ">../temp.ico";
print TEMP "10 GOTO 10\n";
close TEMP;
ENDCODE

GET /temp.ico
MATCH 10 GOTO 10

CODE
rename '../temp.ico', '../temp.gif';
ENDCODE

GET /temp.gif
MATCH 10 GOTO 10

CODE
rename '../temp.gif', '../temp.png';
ENDCODE

GET /temp.png
MATCH 10 GOTO 10

CODE
open TEMP, ">popfile1.log";
print TEMP "10 GOTO 10\n";
close TEMP;
ENDCODE

GET /popfile1.log?session=$sk
MATCH 10 GOTO 10

CODE
mkdir '../manual';
open TEMP, ">../manual/temp.html";
print TEMP "10 GOTO 10\n";
close TEMP;
ENDCODE

GET /manual/temp.html
MATCH 10 GOTO 10

GET /skins/default.css
MATCH .menuSelected

# Get a page that does not exist

GET /foo

# Check update checking

SETCONFIG html_update_check 1
SETCONFIG html_send_stats 1
SETCONFIG html_last_update_check 0
SETCONFIG GLOBAL_ecount 1
GET /
MATCH popfile_update.pl
MATCH popfile_stats.pl

# Check the operation of passwords

GET /security
INPUTIS password
CONFIGIS html_password
SETSUBMIT password secret
GET /advanced?session=123456
MATCH Enter password:
SETSUBMIT password wrong
MATCH Enter password:
MATCH Incorrect password
GET /?session=123456
MATCH Enter password:
SETSUBMIT password secret
MATCH Recent Messages
GET /advanced?session=123456&dummy=foo&dummy=bar
MATCH Enter password:
SETSUBMIT password secret
MATCH All POPFile Parameters
GET /security

# Check shutdown operation

GET /shutdown
MATCH Enter password:
SETSUBMIT password secret
MATCH POPFile shutdown  
