From: 
	=?iso-8859-1?Q?test@test.com?=
To: someone@somewhere.com
Cc: <someoneelse@somewhere.com>
Subject: 
	=?iso-8859-1?Q?test for various HTML parts?=
Reply-To: =?somecharset?Q?someotherperson@somewhere.com?=

<html>

<head>
<meta content="charset=characters">
<title>This is the title</title>
</head>

<body background="http://www.bodybackground.com/foo.gif" bgsound="http://www.bodysound.com/noise.mp3">

<img alt="image tag ALT string"><img width="123"><img height="456">

<table background="http://www.tablebackground.com/bar.gif"><tr><td background="http://www.tdbackground.com/baz.gif"></td></tr></table>

<form action="mailto:someone@outthere.com"></form>

<a href="http://0x10.0x20.0x30.0x40/"><a href="http://10.20.30.40/"><a href="http://010.020.030.040/">

</body>
</html>
