Return-Path: <hornydarla3553qqoe1@free.fr>
Delivered-To: myrealemailaddress@domain
Received: (qmail 26261 invoked by uid 609); 18 Jan 2003 06:22:49 -0000
Delivered-To: spam-address-ccbill@domain
Received: (qmail 26258 invoked by uid 421); 18 Jan 2003 06:22:49 -0000 blah blah
by ekardia with Microsoft SMTPSVC(5.0.2122.2262);
Sat, 18 Jan 2003 15:26:39 +0900
Date: Sat, 18 Jan 2003 06:25:35 GMT
From: "Acaynya"<hornydarla3553qqoe1@free.fr>
X-Priority: 3
To: spamaddy@domain
Subject: spamaddy,what ?
Mime-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
Message-ID: <EKARDIAX6Mmasdf78970016@ekardia>
X-OriginalArrivalTime: 18 Jan 2003 06:26:40.0656 (UTC)
FILETIME=[8FDC2900:01BAAAABA]

I think you answered my ad longtime ago if it was not you I am sorry.
If it was I could not answer
you because my Eudora died and I could not get it to work but my friend got
the emails address out for me ..:)
I hope it was you and you are still interested,
as I realize lots of time has past.
I really don't know where to start ....
Maybe you can tell me little more about yourself since I lost your first email
,
what you look like,age,and are you still looking ?
If you are interested learning more about me, I have a profile at :

http://www.hiddenmatch.com

I am NOT a Porn Chick ..:-)
I just chose it because you don't have to pay,
And they allow any pictures I want .:).
Oh yea , My username is darla1792 .
Don't really know what else to say for now I hope this is the right address .
Let me know if you are interested, And I hope
you don't run when you see my picture :-)

Bye ..... D
