MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
X-MIME-Autoconverted: from 8bit to quoted-printable by mail.datasync.com id h1KNLSI27579


# Identify the language and character set used for the interface
LanguageCode                            da
LanguageCharset                         ISO-8859-1

# This is used to get the appropriate subdirectory for the manual
ManualLanguage                          en

# Common words that are used on their own all over the interface
Apply                                   Anvend
On                                      On
Off                                     Off
TurnOn                                  T=E6nd
TurnOff                                 Sluk
Add                                     Tilf=F8j
Remove                                  Fjern
Previous                                Forrige
Next                                    N=E6ste
From                                    Fra
Subject                                 Emne
Classification                          Klassifikation
Reclassify                              Genklassificering
Undo                                    Fortryd
Close                                   Luk
Find                                    S=F8g
Filter                                  Filter
Yes                                     Ja
No                                      Nej
ChangeToYes                             Skift til Ja
ChangeToNo                              skift til Nej
Bucket                                  Spand
Magnet                                  Magnet
Delete                                  Slet
Create                                  Opret
To                                      Til
Total                                   Total
Rename                                  Omd=F8b
Frequency                               Frekvens
Probability                             Sandsynlighed
Score                                   Resultat
Lookup                                  Sl=E5 op

# The header and footer that appear on every UI page
Header_Title                            POPFile Kontrol Center
Header_Shutdown                         Luk
Header_History                          Historie
Header_Buckets                          Spande
Header_Configuration                    Konfiguration
Header_Advanced                         Avanceret
Header_Security                         Sikkerhed
Header_Magnets                          Magneter

Footer_HomePage                         POPFile Hjemmeside
Footer_Manual                           Manual
Footer_Forums                           Forumer
Footer_FeedMe                           Mad Tak!
Footer_RequestFeature                   Forspurgte funktioner
Footer_MailingList                      Mailing Liste

Configuration_Error1                    Det adskildene tegn skal v=E6re e=
t enkelt tegn
Configuration_Error2                    Brugerfladens port skal v=E6re et=
 nummer imellem 1 og 65535
Configuration_Error3                    POP3 porten skal v=E6re et nummer=
 imellem 1 og 65535
Configuration_Error4                    Siden st=F8relse skal v=E6re imel=
lem 1 og 1000
Configuration_Error5                    Antal dage i historie skal v=E6re=
 et tal imellem 1 og 366
Configuration_Error6                    TCP timeouten skal v=E6re et tal =
imellem 10 og 300
Configuration_POP3Port                  POP3 Porten
Configuration_POP3Update                Opdaterede Porten til %s; Denne =E6=
ndring vil ikke tr=E6de i kraft f=F8r det er at POPFile er genstartet
Configuration_Separator                 Adskelligelses tegn
Configuration_SepUpdate                 Opdaterede det adskildene tegn ti=
l %s
Configuration_UI                        Brugerfladens web port
Configuration_UIUpdate                  Updaterede Brugerfladens web port=
 til %s; denne =E6ndring vil ikke tr=E6de i kraft f=F8r det er at POPFile=
 er genstartet
Configuration_History                   Antal emails pr. side
Configuration_HistoryUpdate             Updaterede antal emails pr. side =
til %s
Configuration_Days                      Antal dage historien skal beholde=
s
Configuration_DaysUpdate                Updaterede antal dage historien s=
kal beholdes til %s
Configuration_UserInterface             Brugerfladen
Configuration_Skins                     Skins
Configuration_SkinsChoose               V=E6lg skin
Configuration_Language                  Sprog
Configuration_LanguageChoose            V=E6lg sprog
Configuration_ListenPorts               POP3 porten
Configuration_HistoryView               Historie view
Configuration_TCPTimeout                TCP forbindelses timeout
Configuration_TCPTimeoutSecs            TCP forbindelses timeout i sekund=
er
Configuration_TCPTimeoutUpdate          Updatere TCP forbindelses timeout=
 til %s
Configuration_ClassificationInsertion   Classification Insertion
Configuration_SubjectLine               Emne linie modifikation
Configuration_XTCInsertion              X-Text-Classification inds=E6tnin=
g
Configuration_XPLInsertion              X-POPFile-Link inds=E6tning
Configuration_Logging                   Logging
Configuration_None                      Ingen
Configuration_ToScreen                  Til Sk=E6rm
Configuration_ToFile                    Til Fil
Configuration_ToScreenFile              Til Sk=E6rm og Fil
Configuration_LoggerOutput              Logger output

Advanced_Error1                         '%s' Er allrede i Stop ords liste=
n
Advanced_Error2                         Stop ord kan kun indeholde Alfanu=
meristike, ., _, -, eller @ tegn
Advanced_Error3                         '%s' er tilf=F8jet til stop ords =
listen
Advanced_Error4                         '%s' er ikke i stop ords listen
Advanced_Error5                         '%s' er fjernet fra stop ords lis=
ten
Advanced_StopWords                      Stop ord
Advanced_Message1                       De efterf=F8lgene ord er alle ign=
oret fra alle klasifikationer pga. af at de fremkommer meget ofte.
Advanced_AddWord                        Tilf=F8j ord
Advanced_RemoveWord                     fjern ord

History_Filter                          &nbsp;(vis kun spanden <font colo=
r=3D"%s">%s</font>)
History_FilterBy                        Filter By
History_Search                          &nbsp;(s=F8g emne for %s)
History_Title                           seneste beskeder
History_Jump                            Spring til besked
History_ShowAll                         Vis alle
History_ShouldBe                        skulle v=E6re
History_NoFrom                          igen fra linie
History_NoSubject                       igen Emne linie
History_ClassifyAs                      klassificeret som
History_MagnetUsed                      Magnet brugt
History_ChangedTo                       skilft til <font color=3D"%s">%s
History_Already                         Allrede genklassificeret som <fon=
t color=3D"%s">%s</font>
History_RemoveAll                       Fjern alle
History_RemovePage                      Fjern side
History_Remove                          for at fjerne tilf=F8jelser i his=
torien tryk
History_SearchMessage                   S=F8g Emne
History_NoMessages                      Igen beskeder

Password_Title                          Kodeord
Password_Enter                          Indtast kodeord
Password_Go                             Go!
Password_Error1                         forkert kodeord

Security_Error1                         Den sikkere port skal v=E6re et t=
al imellem 1 og 65535
Security_Stealth                        Stealth Mode/Server Operation
Security_NoStealthMode                  Nej (Stealth Mode)
Security_ExplainStats                   (Med denne funktion Sender POPFil=
e engang per dag de efterf=F8lgene tre v=E6rdier til et script hos wwwu.s=
ethesource.com: bc ( det totale antal spande du har ) mc ( den hele antal=
 i beskeder at POPFile har klassificeret ) og ec ( det totale antal klass=
ificeringsfejl ). Disse blive lageret i en fil og Jeg vil bruge disse dat=
a til at bekendtg=F8re noget statistik omkring hvordan folk bruger POPFil=
e og hvor godt POPFile virker. Min web server beholder denne log fil for =
omkring 5 dage og s=E5 bliver de slettet; Jeg gemmer igen forbindelse ime=
llem statistikken og individ IP adresser.)
Security_ExplainUpdate                  (Med denne funktion Sender POPFil=
e engang per dag de efterf=F8lgene tre v=E6rdier til et script hos wwwu.s=
ethesource.com: ma (det major version number af din installeret POPFile),=
 mi (det minor version number af din installeret POPFile) and bn (buildt =
number af din installeret POPFile). POPFile modtager et svar i form af et=
 stykke grafik som vises i toppen af siden, hvis en ny version er tilr=E5=
dighed. Min web server beholder denne log fil for omkring 5 dage og s=E5 =
bliver de slettet; Jeg gemmer igen forbindelse imellem statistikken og in=
divid IP adresser.)
Security_PasswordTitle                  Brugerfladens Kodeord
Security_Password                       Kodeord
Security_PasswordUpdate                 Opdater kodeord til %s
Security_AUTHTitle                      Godkendelse af sikker adgangskode
Security_SecureServer                   Sikker Server
Security_SecureServerUpdate             Opdaterede sikker server til %s; =
denne =E6ndring vil ikke tr=E6de i kraft f=F8r det er at POPFile er genst=
artet
Security_SecurePort                     Sikker port
Security_SecurePortUpdate               Opdaterede porten til %s; denne =E6=
ndring vil ikke tr=E6de i kraft f=F8r det er at POPFile er genstartet
Security_POP3                           Acceptere POP3 tilslutninger fra =
fjernmaskiner
Security_UI                             Acceptere HTTP ( Brugerflade ) ti=
lslutninger fra fjernmaskiner
Security_UpdateTitle                    Automatisk Updaterings Tjeck
Security_Update                         Tjeck dagligt efter updateringer =
af POPFile
Security_StatsTitle                     Statestik Reportering
Security_Stats                          Send statestikkerne tilbage til J=
ohn dagligt

Magnet_Error1                           Magneten '%s' eksistere allrede i=
 spanden '%s'=20
Magnet_Error2                           Den nye magnet '%s' konfligter me=
d magneten '%s' i spanden '%s' og kunne skabe flertydige resultater. Den =
nye magnet er ikke tilf=F8jet.
Magnet_Error3                           Skabte den nye magnet '%s' i span=
den '%s'
Magnet_CurrentMagnets                   Aktuele Magneter
Magnet_Message1                         The following magnets cause mail =
to always be classified into the specified bucket.
Magnet_CreateNew                        Skab Nye Magnet
Magnet_Explanation                      Tre typer magneter er tilr=E5dige=
: <ul><li>Fra adressen eller navn:</b> For eksempel: john@firma.dk for at=
 matche en specifik adresse, <br />firma.dk for at matche alle der sender=
 fra firma.dk, <br />John Doe for at matche en specifik person, John for =
at matche alle Johns</li><li><b>Til adresse eller navn:</b> Lige som en F=
ra: Magnet men bare for Til: Adressen i en email</li><li><b>Emne ord:</b>=
 For eksempel: hej for at matche alle beskeder med ordet hej i emnet</li>=
</ul>
Magnet_MagnetType                       Magnet typer
Magnet_Value                            V=E6rdier
Magnet_Always                           Tilh=F8re alttid spanden

Bucket_Error1                           Spandenes navne kan kun indholde =
bogstaverne a til z med sm=E5 bogstaver samt - og _
Bucket_Error2                           Spanden med navnet %s eksistere a=
llrede
Bucket_Error3                           Opret Spanden med navnet %s
Bucket_Error4                           Skriv venligst et ikke tomt ord
Bucket_Error5                           Omd=F8b spanden %s til %s
Bucket_Error6                           Slet spanden %s
Bucket_Title                            oversigt
Bucket_BucketName                       Spandenes navne
Bucket_WordCount                        Ord t=E6lling
Bucket_WordCounts                       Ord fordeling
Bucket_UniqueWords                      Unique Ord
Bucket_SubjectModification              Emne Modifikationer
Bucket_ChangeColor                      Skift farve
Bucket_NotEnoughData                    Ikke nok data
Bucket_ClassificationAccuracy           Klasifikations N=F8jagtighed
Bucket_EmailsClassified                 Emails klasifiseret
Bucket_EmailsClassifiedUpper            Emails klasifiseret
Bucket_ClassificationErrors             Klasifiserings fejl
Bucket_Accuracy                         n=F8jagtighed
Bucket_ClassificationCount              Klasifiserings t=E6lling
Bucket_ResetStatistics                  Nulstil Statistikerene
Bucket_LastReset                        Sidst nulstillet
Bucket_CurrentColor                     %s aktuele farve er %s
Bucket_SetColorTo                       S=E6t %s farven til %s
Bucket_Maintenance                      Vedligeholdelse
Bucket_CreateBucket                     Opret spanden med navnet
Bucket_DeleteBucket                     Slet spanden med navnet
Bucket_RenameBucket                     omd=F8b spanden med navnet
Bucket_Lookup                           Sl=E5 op
Bucket_LookupMessage                    Sl=E5 ord op i spandene
Bucket_LookupMessage2                   Opslags resultatet for
Bucket_LookupMostLikely                 Det er mest sansynlig at <b>%s</b=
> fremkommer i <font color=3D"%s">%s</font>
Bucket_DoesNotAppear                    <p><b>%s</b> fremkommer ikke i no=
gle af spandene
Bucket_DisabledGlobally                 Deaktiveret globalt

SingleBucket_Title                      Detalier for %s
SingleBucket_WordCount                  Total antal ord i spanden
SingleBucket_TotalWordCount             Totale antal ord
SingleBucket_Percentage                 Procentdelen af totalen
SingleBucket_WordTable                  Ord tabel for %s
SingleBucket_Message1                   Markeret (*) ord er blevet brugt =
til at klasifisere i denne POPFile session. Tryk p=E5 hvilket som helst o=
rd for at sl=E5 dens sansynlighed op for alle spandene.
SingleBucket_Unique                     %s unique
