MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
X-MIME-Autoconverted: from 8bit to quoted-printable by mail.datasync.com id h1KNLSI27579


# Identify the language and character set used for the interface
LanguageCode                            de
LanguageCharset                         ISO-8859-1

# This is used to get the appropriate subdirectory for the manual
ManualLanguage                          de

# Common words that are used on their own all over the interface
Apply                                   Anwenden
On                                      Ein
Off                                     Aus
TurnOn                                  Einschalten
TurnOff                                 Ausschalten
Add                                     Hinzuf=FCgen
Remove                                  Entfernen
Previous                                Zur=FCck
Next                                    Weiter
From                                    Absender
Subject                                 Betreff
Classification                          Einstufung
Reclassify                              Neu einstufen
Undo                                    widerrufen
Close                                   Schlie=DFen
Find                                    Suchen
Filter                                  Filter
Yes                                     Ja
No                                      Nein
ChangeToYes                             =C4ndern in Ja
ChangeToNo                              =C4ndern in Nein
Bucket                                  Kategorie
Magnet                                  Magnet
Delete                                  L=F6schen
Create                                  Erstellen
To                                      Empf=E4nger
Total                                   Insgesamt
Rename                                  Umbenennen
Frequency                               H=E4ufigkeit
Probability                             Wahrscheinlichkeit
Score                                   Auswertung
Lookup                                  Nachschlagen

# The header and footer that appear on every UI page
Header_Title                            POPFile Kontrollzentrum
Header_Shutdown                         Herunterfahren
Header_History                          Verlauf
Header_Buckets                          Kategorie
Header_Configuration                    Konfiguration
Header_Advanced                         Erweitert
Header_Security                         Sicherheit
Header_Magnets                          Magnete

Footer_HomePage                         POPFile Homepage
Footer_Manual                           Handbuch
Footer_Forums                           Foren
Footer_FeedMe                           Spenden
Footer_RequestFeature                   Funktionalit=E4t vorschlagen
Footer_MailingList                      Mailing Liste

Configuration_Error1                    Das Trennzeichen mu=DF ein einzel=
nes Zeichen sein.
Configuration_Error2                    Der Port f=FCr das Kontrollzentru=
m mu=DF zwischen 1 und 65535 liegen.
Configuration_Error3                    Der POP3 Port mu=DF zwischen 1 un=
d 65535 liegen.
Configuration_Error4                    Die Seitengr=F6=DFe mu=DF zwische=
n 1 und 1000 liegen.
Configuration_Error5                    Die Anzahl der Tage im Verlauf mu=
=DF zwischen 1 und 366 liegen.
Configuration_Error6                    Der TCP Timeout mu=DF zwischen 10=
 und 300 liegen.
Configuration_POP3Port                  POP3 Port
Configuration_POP3Update                Neuer POP3 Port: %s; Diese =C4nde=
rung wird erst nach einem Neustart von POPFile wirksam.
Configuration_Separator                 Trennzeichen
Configuration_SepUpdate                 Neues Trennzeichen: %s
Configuration_UI                        Web Port f=FCr Kontrollzentrum
Configuration_UIUpdate                  Neuer Web Port f=FCr Kontrollzent=
rum: %s; Dieser =C4nderung wird erst nach einem Neustart von POPFile wirk=
sam.
Configuration_History                   Anzahl Emails pro Seite
Configuration_HistoryUpdate             Neue Anzahl Emails pro Seite: %s
Configuration_Days                      Emails x Tage im Verlauf speicher=
n
Configuration_DaysUpdate                Emails werden nun %s im Verlauf g=
espeichert
Configuration_UserInterface             Benutzeroberfl=E4che
Configuration_Skins                     Skins
Configuration_SkinsChoose               Skin ausw=E4hlen
Configuration_Language                  Sprache
Configuration_LanguageChoose            Sprache ausw=E4hlen
Configuration_ListenPorts               Porteinstellungen
Configuration_HistoryView               Verlaufsansicht
Configuration_TCPTimeout                TCP Verbindungstimeout
Configuration_TCPTimeoutSecs            TCP Verbindungstimeout in Sekunde=
n
Configuration_TCPTimeoutUpdate          Neuer TCP Verbidungstimeout: %s
Configuration_ClassificationInsertion   Einstufung anzeigen
Configuration_SubjectLine               Betreff-Zeile =E4ndern
Configuration_XTCInsertion              X-Text-Classification einf=FCgen
Configuration_XPLInsertion              X-POPFile-Link einf=FCgen
Configuration_Logging                   Protokollierung
Configuration_None                      Keine Ausgabe
Configuration_ToScreen                  Auf den Bildschirm
Configuration_ToFile                    In eine Datei
Configuration_ToScreenFile              Bildschirm und Datei
Configuration_LoggerOutput              Protokoll ausgeben

Advanced_Error1                         '%s' ist bereits in der Liste der=
 ignorierten W=F6rter
Advanced_Error2                         Ignorierte W=F6rtern k=F6nnen nur=
 alphanumerische, ., _, -, oder @ Zeichen enthalten
Advanced_Error3                         '%s' zu den ignorierten W=F6rtern=
 hinzugef=FCgt
Advanced_Error4                         '%s' ist nicht in der Liste der i=
gnorierten W=F6rter
Advanced_Error5                         '%s' von der Liste der ignorierte=
n W=F6rter entfernt
Advanced_StopWords                      Ignorierte W=F6rter
Advanced_Message1                       POPFile ignoriert die folgenden, =
h=E4ufig verwendeten W=F6rter:
Advanced_AddWord                        Wort hinzuf=FCgen
Advanced_RemoveWord                     Wort l=F6schen

History_Filter                          &nbsp;(zeige nur Kategorie <font =
color=3D"%s">%s</font>)
History_Search                          &nbsp;(gesuchter Absender/Betreff=
: %s)
History_Title                           Letzte Nachrichten
History_Jump                            zu Nachricht gehen
History_ShowAll                         Alle anzeigen
History_ShouldBe                        Sollte sein
History_NoFrom                          kein Absender angegeben
History_NoSubject                       kein Betreff
History_ClassifyAs                      eingestuft als
History_MagnetUsed                      Magnet benutzt
History_ChangedTo                       Ge=E4ndert: <font color=3D"%s">%s
History_Already                         Bereits neu eingestuft als <font =
color=3D"%s">%s</font>
History_RemoveAll                       Alle entfernen
History_RemovePage                      Diese Seite entfernen
History_Remove                          Um Eintr=E4ge im Verlauf zu l=F6s=
chen, klicken Sie auf
History_SearchMessage                   Nach Absender/Betreff suchen
History_NoMessages                      keine Nachrichten
History_ShowMagnet                      Magnetisiert
History_Magnet                          &nbsp;(zeige nur durch Magnet ein=
gestufte Nachrichten)
History_ResetSearch                     Zur=FCcksetzen

Password_Title                          Pa=DFwort
Password_Enter                          Pa=DFwort eingeben
Password_Go                             Anmelden
Password_Error1                         Falsches Pa=DFwort

Security_Error1                         Der sichere Port mu=DF zwischen 1=
 und 65535 liegen.
Security_Stealth                        Stealth Modus/Serverbetrieb
Security_NoStealthMode                  Nein (Stealth Modus)
Security_ExplainStats                   (Wenn Sie diese Funktion einschal=
ten, sendet POPFile t=E4glich die drei folgenden Werte an ein Skript auf =
www.usethesource.com: bc (Anzahl von Ihnen eingerichteter Kategorien), mc=
 (Anzahl von POPFile eingestufter Nachrichten) und ec (Anzahl der Einstuf=
ungsfehler). Diese werden in einer Datei gespeichert und benutzt, um =F6f=
fentliche Statistiken dar=FCber zu erstellen, wie POPFile genutzt wird un=
d wie gut es dabei funktioniert. Die Daten werden etwa 5 Tage auf dem Ser=
ver gespeichert und dann gel=F6scht. Zuordnungen zwischen IP-Adressen und=
 statistischen Daten werden nicht gespeichert.)
Security_ExplainUpdate                  (Wenn Sie diese Funktion einschal=
ten, sendet POPFile t=E4glich die drei folgenden Werte an ein Skript auf =
www.usethesource.com: ma (die Hauptversionsnummer der POPFile-Installatio=
n), mi (die Nebenversionsnummer der POPFile-Installation) und bn (die bui=
ld-Nummer der POPFile-Installation). POPFile erh=E4lt die Antwort in Form=
 einer Grafik, die am Kopf einer Seite erscheint, wenn eine neue Version =
verf=FCgbar ist. Die Daten werden etwa 5 Tage auf dem Server gespeichert =
und dann gel=F6scht. Zuordnungen zwischen IP-Adressen und statistischen D=
aten werden nicht gespeichert.)
Security_PasswordTitle                  Pa=DFwort f=FCr Benutzeroberfl=E4=
che
Security_Password                       Pa=DFwort
Security_PasswordUpdate                 Neues Pa=DFwort: %s
Security_AUTHTitle                      gesicherte Kennwortauthentizierun=
g/AUTH
Security_SecureServer                   gesicherter Server
Security_SecureServerUpdate             Neuer gesicherter Server: %s; Die=
se =C4nderung wird erst nach einem Neustart von POPFile wirksam.
Security_SecurePort                     gesicherter Port
Security_SecurePortUpdate               Neuer gesicherter Port %s; Diese =
=C4nderung wird erst nach einem Neustart von POPFile wirksam.
Security_POP3                           POP3 Verbindungen von fremden Rec=
hnern erlauben (erfordert Neustart von POPFile)
Security_UI                             HTTP (Benutzeroberfl=E4che) Verbi=
ndungen von fremden Rechnern erlauben (erfordert Neustart von POPFile)
Security_UpdateTitle                    Automatisch auf Updates pr=FCfen
Security_Update                         T=E4glich nach POPFile Updates su=
chen
Security_StatsTitle                     Statistik Report
Security_Stats                          T=E4glich Statistiken senden

Magnet_Error1                           Magnet '%s' existiert bereits in =
Kategorie '%s'
Magnet_Error2                           Neuer Magnet '%s' kollidiert mit =
Magnet '%s' in Kategorie '%s' und k=F6nnte unklare Ergebnisse verursachen=
. Magnet wurde nicht unzugef=FCgt.
Magnet_Error3                           Erstelle neuen Magnet '%s' in Kat=
egorie '%s'
Magnet_CurrentMagnets                   Aktuelle Magnete
Magnet_Message1                         Die folgenden Magnete ordnen neue=
 Post zwingend in eine angegebene Kategorie ein.
Magnet_CreateNew                        Neuen Magnet erstellen
Magnet_Explanation                      Drei Typen von Magneten sind verf=
=FCgbar: <ul><li>Absenderadresse oder -name:</b> z.B.: hans@firma.de, um =
eine bestimmte Adresse zu erfassen, <br />firma.de, um jeden zu erfassen,=
 der von firma.de sendet, <br />Hans Mustermann, um eine bestimmte Person=
 zu erfassen; Hans erfa=DFt jeden Hans</li><li><b>Empf=E4ngeradresse oder=
 -name:</b> Wie beim Absender-Magnet nur f=FCr die Empf=E4ngeradresse in =
der Email.</li><li><b>W=F6rter im Betreff:</b> z.B.: "Hallo", um alle Nac=
hrichten mit "Hallo" im Betreff zu erfassen</li></ul>
Magnet_MagnetType                       Typ des Magnets
Magnet_Value                            Wert
Magnet_Always                           Immer dieser Kategorie zuordnen

Bucket_Error1                           Kategorienamen k=F6nnen nur Klein=
buchstaben von a bis z, - oder _ enthalten
Bucket_Error2                           Kategoriename %s existiert bereit=
s
Bucket_Error3                           Kategorie %s erstellt
Bucket_Error4                           Bitte geben Sie ein nicht-leeres =
Wort ein
Bucket_Error5                           Kategorie %s in %s umbenannt
Bucket_Error6                           Kategorie %s gel=F6scht
Bucket_Title                            Zusammenfassung
Bucket_BucketName                       Kategoriename
Bucket_WordCount                        Wortanzahl
Bucket_WordCounts                       Wortanzahl
Bucket_UniqueWords                      verschiedene W=F6rter
Bucket_SubjectModification              Betreff =E4ndern
Bucket_ChangeColor                      Farbe =E4ndern
Bucket_NotEnoughData                    Nicht gen=FCgend Daten
Bucket_ClassificationAccuracy           Genauigkeit
Bucket_EmailsClassified                 Emails klassifiziert
Bucket_EmailsClassifiedUpper            Emails klassifiziert
Bucket_ClassificationErrors             Einstufungsfehler
Bucket_Accuracy                         Genauigkeit
Bucket_ClassificationCount              Anzahl Einstufungen
Bucket_ResetStatistics                  Statistiken zur=FCcksetzen
Bucket_LastReset                        L=E4uft seit
Bucket_CurrentColor                     Derzeitige Farbe von %s ist %s
Bucket_SetColorTo                       Setze Farbe von %s auf %s
Bucket_Maintenance                      Verwaltung
Bucket_CreateBucket                     Erstelle Kategorie
Bucket_DeleteBucket                     L=F6sche Kategorie
Bucket_RenameBucket                     Benenne Kategorie um
Bucket_Lookup                           Nachschlagen
Bucket_LookupMessage                    Wort in Kategorie nachschlagen
Bucket_LookupMessage2                   Ergebnis f=FCr
Bucket_LookupMostLikely                 <b>%s</b> erscheint am wahrschein=
lichsten in <font color=3D"%s">%s</font>
Bucket_DoesNotAppear                    <p><b>%s</b> erscheint in keiner =
Kategorie
Bucket_DisabledGlobally                 Global deaktiviert
Bucket_To                               in
Bucket_Quarantine                       Quarant=E4ne

SingleBucket_Title                      Details f=FCr %s
SingleBucket_WordCount                  Anzahl Worte in dieser Kategorie
SingleBucket_TotalWordCount             Anzahl Worte insgesamt
SingleBucket_Percentage                 Anteil an der Gesamtzahl
SingleBucket_WordTable                  Worttabelle f=FCr %s
SingleBucket_Message1                   Mit (*) gekennzeichnete W=F6rter =
wurden in dieser POPFile Sitzung zur Sortierung benutzt. Klicken Sie auf =
ein beliebiges Wort, um die Wahrscheinlichkeit seines Erscheinens f=FCr a=
lle Kategorien anzusehen.
SingleBucket_Unique                     %s verschiedene

Session_Title                           POPFile Sitzung abgelaufen
Session_Error                           Ihre POPFile-Sitzung ist abgelauf=
en. Dies k=F6nnte dadurch verursacht worden sein, da=DF Sie POPFile neu g=
estartet haben, das Kontrollzentrum aber noch im Browser ge=F6ffnet war. =
Bitte klicken Sie auf einen der oben angezeigten Verweise, um mit der Ben=
utzung von POPFile weitermachen zu k=F6nnen.
