MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
X-MIME-Autoconverted: from 8bit to quoted-printable by mail.datasync.com id h1KNLSI27579


# Identify the language and character set used for the interface
LanguageCode                            fr
LanguageCharset                         ISO-8859-1

# This is used to get the appropriate subdirectory for the manual
ManualLanguage                          fr

# Common words that are used on their own all over the interface
Apply                                   Appliquer
On                                      Actif
Off                                     Inactif
TurnOn                                  Activer
TurnOff                                 D=E9sactiver
Add                                     Ajouter
Remove                                  Retirer
Previous                                Pr=E9c=E9dent
Next                                    Suivant
From                                    De
Subject                                 Sujet
Classification                          Classification
Reclassify                              Reclassifier
Undo                                    Annuler
Close                                   Fermer
Find                                    Chercher
Filter                                  Filtrer
Yes                                     Oui
No                                      Non
ChangeToYes                             Passer =E0 Oui
ChangeToNo                              Passer =E0 Non
Bucket                                  Cat=E9gorie
Magnet                                  Aimant
Delete                                  Supprimer
Create                                  Cr=E9er
To                                      A
Total                                   Total
Rename                                  Renommer
Frequency                               Fr=E9quence
Probability                             Probabilit=E9
Score                                   Score
Lookup                                  Consulter

# The header and footer that appear on every UI page
Header_Title                            Centre de Commande de POPFile
Header_Shutdown                         Arr=EAter POPFile
Header_History                          Historique
Header_Buckets                          Cat=E9gories
Header_Configuration                    Configuration
Header_Advanced                         Avanc=E9
Header_Security                         S=E9curit=E9
Header_Magnets                          Aimants

Footer_HomePage                         Site web de POPFile
Footer_Manual                           Manuel
Footer_Forums                           Forums
Footer_FeedMe                           Encouragez-moi!
Footer_RequestFeature                   Demande d'=E9volution
Footer_MailingList                      Liste de diffusion

Configuration_Error1                    Le caract=E8re s=E9parateur doit =
=EAtre un unique caract=E8re
Configuration_Error2                    Le port de l'interface utilisateu=
r doit =EAtre un nombre compris entre 1 et 65535
Configuration_Error3                    Le port d'=E9coute POP3 doit =EAt=
re un nombre compris entre 1 et 65535
Configuration_Error4                    La taille de page doit =EAtre un =
nombre compris entre 1 et 1000
Configuration_Error5                    Le nombre de jours d'historique d=
oit =EAtre un nombre compris entre 1 et 366
Configuration_Error6                    Le d=E9lai d'expiration TCP doit =
=EAtre un nombre compris entre 10 et 300
Configuration_POP3Port                  Port d'=E9coute POP3
Configuration_POP3Update                Port pass=E9 =E0 %s; ce changemen=
t ne prendra effet qu'au prochain red=E9marrage de POPFile
Configuration_Separator                 S=E9parateur
Configuration_SepUpdate                 S=E9parateur chang=E9 en %s
Configuration_UI                        Port web d'interface utilisateur
Configuration_UIUpdate                  Port web d'interface utilisateur =
pass=E9 =E0 %s; ce changement ne prendra effet qu'au prochain red=E9marra=
ge de POPFile
Configuration_History                   Nombre de messages par page
Configuration_HistoryUpdate             Nombre de messages par page pass=E9=
 =E0 %s
Configuration_Days                      Nombre de jours d'historique =E0 =
conserver
Configuration_DaysUpdate                Nombre de jours d'historique pass=
=E9 =E0 %s
Configuration_UserInterface             Interface Utilisateur
Configuration_Skins                     Apparences
Configuration_SkinsChoose               Choisir une apparence
Configuration_Language                  Langue
Configuration_LanguageChoose            Choisir une langue
Configuration_ListenPorts               Ports d'Ecoute
Configuration_HistoryView               Pages d'Historique
Configuration_TCPTimeout                D=E9lai d'Expiration de Connexion=
 TCP
Configuration_TCPTimeoutSecs            D=E9lai d'expiration de connexion=
 TCP en secondes
Configuration_TCPTimeoutUpdate          D=E9lai d'expiration de connexion=
 TCP pass=E9 =E0 %s
Configuration_ClassificationInsertion   Informations de Classification
Configuration_SubjectLine               Modification de la ligne Sujet
Configuration_XTCInsertion              Insertion de X-Text-Classificatio=
n
Configuration_XPLInsertion              Insertion de X-POPFile-Link
Configuration_Logging                   Journalisation
Configuration_None                      auncune
Configuration_ToScreen                  =E0 l'=E9cran
Configuration_ToFile                    dans un fichier
Configuration_ToScreenFile              =E9cran et fichier
Configuration_LoggerOutput              Sortie

Advanced_Error1                         '%s' est d=E9j=E0 dans la liste d=
es mots ignor=E9s
Advanced_Error2                         Les mots ignor=E9s ne peuvent con=
tenir que des caract=E8res alphanum=E9riques ou ., _, -, @
Advanced_Error3                         '%s' ajout=E9 =E0 la liste des mo=
ts ignor=E9s
Advanced_Error4                         '%s' n'est pas dans la liste des =
mots ignor=E9s
Advanced_Error5                         '%s' retir=E9 de la liste des mot=
s ignor=E9s
Advanced_StopWords                      Mots ignor=E9s
Advanced_Message1                       Les mots suivants sont ignor=E9s =
dans toutes les classifications comme ils apparaissent tr=E8s souvent.
Advanced_AddWord                        Ajouter un mot
Advanced_RemoveWord                     Retirer un mot

History_Filter                          &nbsp;(ne montrant que la cat=E9g=
orie <font color=3D"%s">%s</font>)
History_FilterBy                        Filter By
History_Search                          &nbsp;(recherche du sujet %s)
History_Title                           Messages r=E9cents
History_Jump                            Aller au message
History_ShowAll                         Tout afficher
History_ShouldBe                        Devrait =EAtre
History_NoFrom                          pas de ligne De
History_NoSubject                       pas de ligne Sujet
History_ClassifyAs                      Classifi=E9 comme
History_MagnetUsed                      Aimant utilis=E9
History_ChangedTo                       Chang=E9 en <font color=3D"%s">%s
History_Already                         D=E9j=E0 reclassifi=E9 comme <fon=
t color=3D"%s">%s</font>
History_RemoveAll                       Supprimer tout
History_RemovePage                      Supprimer page
History_Remove                          Pour supprimer des entr=E9es dans=
 l'historique cliquez
History_SearchMessage                   Chercher De/Sujet
History_NoMessages                      Pas de messages
History_ShowMagnet                      Aimant=E9
History_Magnet                          &nbsp;(ne montrant que les messag=
es classifi=E9s par aimant)
History_ResetSearch                     Initialiser

Password_Title                          Mot de Passe
Password_Enter                          Entrez le mot de passe
Password_Go                             Continuer
Password_Error1                         Mot de passe incorrect

Security_Error1                         Le port s=E9curis=E9 doit =EAtre =
un nombre compris entre 1 et 65535
Security_Stealth                        Mode Furtif/Fonctionnement du Ser=
veur
Security_NoStealthMode                  Non (Mode Furtif)
Security_ExplainStats                   (Quand ceci est activ=E9 POPFile =
envoie une fois par jour les trois valeurs suivantes =E0 un script =E0 ww=
w.usethesource.com: bc (le nombre total de vos cat=E9gories), mc (le nomb=
re total de messages classifi=E9s par POPFile) et ec (le nombre total d'e=
rreurs de classification).  Elles sont alors stock=E9es dans un fichier q=
ue j'utiliserai pour publier quelques statistiques sur comment les gens u=
tilisent POPFile et si =E7a marche bien.  Mon serveur web conserve ses fi=
chiers log pendant environ 5 jours puis les efface; je ne recueille aucun=
 lien entre les statisques et les adresses IP individuelles.)
Security_ExplainUpdate                  (Quand ceci est activ=E9 POPFile =
envoie une fois par jour les trois valeurs suivantes =E0 un script =E0 ww=
w.usethesource.com: ma (le num=E9ro de version principal de votre POPFile=
), mi (le num=E9ro de version secondaire de votre POPFile) et bn (le num=E9=
ro de compilation de votre POPFile).  POPFile re=E7oit une r=E9ponse sous=
 la forme d'un graphique qui appara=EEt en haut de la page si une version=
 plus r=E9cente est disponible.  Mon serveur web conserve ses fichiers lo=
g pendant environ 5 jours puis les efface; je ne recueille aucun lien ent=
re les contr=F4les de mise =E0 jour et les adresses IP individuelles.)
Security_PasswordTitle                  Mot de passe de l'interface utili=
sateur
Security_Password                       Mot de passe
Security_PasswordUpdate                 Mot de passe chang=E9 en %s
Security_AUTHTitle                      Authentification par mot de passe=
 s=E9curis=E9/AUTH
Security_SecureServer                   Serveur s=E9curis=E9
Security_SecureServerUpdate             Serveur s=E9curis=E9 pass=E9 =E0 =
%s; ce changement ne prendra effet qu'au prochain red=E9marrage de POPFil=
e
Security_SecurePort                     Port s=E9curis=E9
Security_SecurePortUpdate               Port s=E9curis=E9 pass=E9 =E0 %s;=
 ce changement ne prendra effet qu'au prochain red=E9marrage de POPFile
Security_POP3                           Accepter les connexions POP3 de m=
achines distantes
Security_UI                             Accepter les connexions HTTP (Int=
erface Utilisateur) de machines distantes
Security_UpdateTitle                    Contr=F4le automatique de mise =E0=
 jour
Security_Update                         V=E9rifier quotidiennement les mi=
ses =E0 jour de POPFile
Security_StatsTitle                     Compte-rendu de statistiques
Security_Stats                          Envoyer quotidiennement des stati=
stiques =E0 John

Magnet_Error1                           L'aimant '%s' existe d=E9j=E0 pou=
r la cat=E9gorie '%s'
Magnet_Error2                           Le nouvel aimant '%s' interf=E8re=
 avec l'aimant '%s' de la cat=E9gorie '%s' et pourrait causer des r=E9sul=
tats ambig=FCes.  Le nouvel aimant n'est pas ajout=E9.
Magnet_Error3                           Nouvel aimant '%s' cr=E9=E9 pour =
la cat=E9gorie '%s'
Magnet_CurrentMagnets                   Aimants actuels
Magnet_Message1                         Les aimants suivants entrainent l=
a classification syst=E9matique d'un message dans la cat=E9gorie sp=E9cif=
i=E9e.
Magnet_CreateNew                        Cr=E9er un nouvel aimant
Magnet_Explanation                      Trois types d'aimants sont dispon=
ibles:</b> <ul><li><b>Adresse ou nom de l'exp=E9diteur:</b> Par exemple: =
john@company.com pour capter une adresse sp=E9cifique, <br />company.com =
pour capter les messages de tous les exp=E9diteurs de company.com, <br />=
John Doe pour capter une personne en particulier, John pour capter tous l=
es John</li><li><b>Adresse ou nom du destinataire:</b> Comme un aimant De=
: mais pour l'adresse du destinataire du message</li><li><b>Mots du sujet=
:</b> Par exemple: bonjour pour capter tous les messages avec bonjour dan=
s le sujet</li></ul>
Magnet_MagnetType                       Type d'aimant
Magnet_Value                            Valeur
Magnet_Always                           Toujours envoyer dans la cat=E9go=
rie

Bucket_Error1                           Les noms de cat=E9gories ne peuve=
nt contenir que les minuscules de a to z ainsi que - and _
Bucket_Error2                           La cat=E9gorie nomm=E9e %s existe=
 d=E9j=E0
Bucket_Error3                           Cat=E9gorie nomm=E9e %s cr=E9=E9e
Bucket_Error4                           Veuillez entrer un mot non blanc
Bucket_Error5                           Cat=E9gorie %s renomm=E9e en %s
Bucket_Error6                           Cat=E9gorie %s effac=E9e
Bucket_Title                            R=E9sum=E9
Bucket_BucketName                       Nom de cat=E9gorie
Bucket_WordCount                        Nombre de mots
Bucket_WordCounts                       Nombres de Mots
Bucket_UniqueWords                      Mots distincts
Bucket_SubjectModification              Modification du sujet
Bucket_ChangeColor                      Changer la couleur
Bucket_NotEnoughData                    Pas assez de donn=E9es
Bucket_ClassificationAccuracy           Performance de Classification
Bucket_EmailsClassified                 Messages classifi=E9s
Bucket_EmailsClassifiedUpper            Messages Classifi=E9s
Bucket_ClassificationErrors             Erreurs de classification
Bucket_Accuracy                         Performance
Bucket_ClassificationCount              Nombre de classifications
Bucket_ResetStatistics                  Initialiser les statisques
Bucket_LastReset                        Derni=E8re initialisation
Bucket_CurrentColor                     La couleur actuelle de %s est %s
Bucket_SetColorTo                       Changer la couleur de %s en %s
Bucket_Maintenance                      Maintenance
Bucket_CreateBucket                     Cr=E9er une cat=E9gorie nomm=E9e
Bucket_DeleteBucket                     Effacer la cat=E9gorie nomm=E9e
Bucket_RenameBucket                     Renommer la cat=E9gorie nomm=E9e
Bucket_Lookup                           Examiner
Bucket_LookupMessage                    Examiner le mot dans les cat=E9go=
ries
Bucket_LookupMessage2                   Examiner le r=E9sultat pour
Bucket_LookupMostLikely                 <b>%s</b> a le plus de chance d'a=
ppara=EEtre dans <font color=3D"%s">%s</font>
Bucket_DoesNotAppear                    <p><b>%s</b> n'appara=EEt dans au=
cune cat=E9gorie
Bucket_DisabledGlobally                 D=E9sactiv=E9 globalement
Bucket_To                               en
Bucket_Quarantine                       Mise en quarantaine

SingleBucket_Title                      D=E9tail pour %s
SingleBucket_WordCount                  Nombre de mots de la cat=E9gorie
SingleBucket_TotalWordCount             Nombre total de mots
SingleBucket_Percentage                 Pourcentage du total
SingleBucket_WordTable                  Table des mots pour %s
SingleBucket_Message1                   Les mots signal=E9s (*) ont =E9t=E9=
 utilis=E9s pour la classification dans cette session POPFile.  Cliquez s=
ur un mot pour examiner sa probabilit=E9 pour tous les cat=E9gories.
SingleBucket_Unique                     %s seul

Session_Title                           Session POPFile expir=E9e
Session_Error                           Votre session POPFile a expir=E9.=
  Cela peut =EAtre d=FB =E0 un arr=EAt/relance de POPFile alors que le na=
vigateur est rest=E9 ouvert.  Veuillez cliquer sur l'un des liens ci-dess=
us pour continuer =E0 utiliser POPFile.
