# Copyright (c) 2001-2003 John Graham-Cumming

LanguageCode                            en
LanguageCharset                         ISO-8859-1
ManualLanguage                          en
Apply                                   4pply
On                                      0n
Off                                     0ff
TurnOn                                  Turn 0n
TurnOff                                 Turn 0ff
Add                                     4dd
Remove                                  R3m0v3
Previous                                Pr3v10u5
Next                                    N3xt
From                                    Fr0m
Subject                                 5ubj3ct
Classification                          Cl4s51f1c4t10n
Reclassify                              R3cl4s51fy
Undo                                    Und0
Close                                   Cl053
Find                                    F1nd
Filter                                  F1lt3r
Yes                                     Y35
No                                      N0
ChangeToYes                             Ch4ng3 t0 Y35
ChangeToNo                              Ch4ng3 t0 N0
Bucket                                  Buck3t
Magnet                                  M4gn3t
Delete                                  D3l3t3
Create                                  Cr34t3
To                                      T0
Total                                   T0t4l
Rename                                  R3n4m3
Frequency                               Fr3qu3ncy
Probability                             Pr0b4b1l1ty
Score                                   5c0r3
Lookup                                  L00kup

Header_Title                            P0PF1l3 C0ntr0l C3nt3r
Header_Shutdown                         5hutd0wn
Header_History                          H15t0ry
Header_Buckets                          Buck3t5
Header_Configuration                    C0nf1gur4t10n
Header_Advanced                         4dv4nc3d
Header_Security                         53cur1ty
Header_Magnets                          M4gn3t5

Footer_HomePage                         P0PF1l3 H0m3 P4g3
Footer_Manual                           M4nu4l
Footer_Forums                           F0rum5
Footer_FeedMe                           F33d M3!
Footer_FeatureRequest                   R3qu35t F34tur3
Footer_MailingList                      M41l1ng L15t

Configuration_Error1                    Th3 53p4r4t0r ch4r4ct3r mu5t b3 4 51ngl3 ch4r4ct3r
Configuration_Error2                    Th3 u53r 1nt3rf4c3 p0rt mu5t b3 4 numb3r b3tw33n 1 4nd 65535
Configuration_Error3                    Th3 P0P3 l15t3n p0rt mu5t b3 4 numb3r b3tw33n 1 4nd 65535
Configuration_Error4                    Th3 p4g3 51z3 mu5t b3 4 numb3r b3tw33n 1 4nd 1000
Configuration_Error5                    Th3 numb3r 0f d4y5 1n th3 h15t0ry mu5t b3 4 numb3r b3tw33n 1 4nd 366
Configuration_Error6                    Th3 TCP t1m30ut mu5t b3 4 numb3r b3tw33n 10 4nd 300
Configuration_POP3Port                  P0P3 l15t3n p0rt
Configuration_POP3Update                Upd4t3d p0rt t0 %s; th15 ch4ng3 w1ll n0t t4k3 4ff3ct unt1l y0u r35t4rt P0PF1l3
Configuration_Separator                 53p4r4t0r ch4r4ct3r
Configuration_SepUpdate                 Upd4t3d 53p4r4t0r t0 %s
Configuration_UI                        U53r 1nt3rf4c3 w3b p0rt
Configuration_UIUpdate                  Upd4t3d u53r 1nt3rf4c3 w3b p0rt t0 %s; th15 ch4ng3 w1ll n0t t4k3 4ff3ct unt1l y0u r35t4rt P0PF1l3
Configuration_History                   Numb3r 0f 3m41l5 p3r p4g3
Configuration_HistoryUpdate             Upd4t3d numb3r 0f 3m41l5 p3r p4g3 t0 %s
Configuration_Days                      Numb3r 0f d4y5 0f h15t0ry t0 k33p
Configuration_DaysUpdate                Upd4t3d numb3r 0f d4y5 0f h15t0ry t0 %s
Configuration_UserInterface             U53r 1nt3rf4c3
Configuration_Skins                     Sk1n5
Configuration_SkinsChoose               Ch0053 5k1n
Configuration_Language                  L4ngu4g3
Configuration_LanguageChoose            Ch0053 l4ngu4g3
Configuration_ListenPorts               L15t3n P0rt5
Configuration_HistoryView               H15t0ry V13w
Configuration_TCPTimeout                TCP C0nn3ct10n T1m30ut
Configuration_TCPTimeoutSecs            TCP c0nn3ct10n t1m30ut 1n s3c0nd5
Configuration_TCPTimeoutUpdate          Upd4t3d TCP c0nn3ct10n t1m30ut t0 %s
Configuration_ClassificationInsertion   Cl4s51f1c4t10n 1n53rt10n
Configuration_SubjectLine               5ubj3ct l1n3 m0d1f1c4t10n
Configuration_XTCInsertion              X-T3xt-Cl4s51f1c4t10n 1n53rt10n
Configuration_XPLInsertion              X-P0PF1l3-L1nk 1n53rt10n
Configuration_Logging                   L0gg1ng
Configuration_None                      N0n3
Configuration_ToScreen                  T0 5cr33n
Configuration_ToFile                    T0 F1l3
Configuration_ToScreenFile              T0 5cr33n 4nd F1l3
Configuration_LoggerOutput              L0gg3r 0utput
Configuration_GeneralSkins              Skins
Configuration_SmallSkins                Small Skins
Configuration_TinySkins                 Tiny Skins

Advanced_Error1                         '%s' 4lr34dy 1n th3 5t0p w0rd l15t
Advanced_Error2                         5t0p w0rd5 c4n 0nly c0nt41n5 4lph4num3r1c, ., _, -, 0r @ ch4r4ct3r5
Advanced_Error3                         '%s' 4dd3d t0 th3 5t0p w0rd l15t
Advanced_Error4                         '%s' 15 n0t 1n th3 5t0p w0rd l15t
Advanced_Error5                         '%s' r3m0v3d fr0m th3 5t0p w0rd l15t
Advanced_StopWords                      5t0p W0rd5
Advanced_Message1                       Th3 f0ll0w1ng w0rd5 4r3 1gn0r3d fr0m 4ll cl4ss1f1c4t10n5 45 th3y 0ccur v3ry fr3qu3ntly.
Advanced_AddWord                        4dd w0rd
Advanced_RemoveWord                     R3m0v3 w0rd

History_Filter                          &nbsp;(ju5t 5h0w1ng buck3t <font color="%s">%s</font>)
History_FilterBy                        F1lt3r By
History_Search                          &nbsp;(534rch3d f0r 5ubj3ct %s)
History_Title                           R3c3nt M3ss4g35
History_Jump                            Jump t0 m3s54g3
History_ShowAll                         5h0w 4ll
History_ShouldBe                        5h0uld b3
History_NoFrom                          n0 fr0m l1n3
History_NoSubject                       n0 5ubj3ct l1n3
History_ClassifyAs                      Cl4s51fy 45
History_MagnetUsed                      M4gn3t u53d
History_ChangedTo                       Ch4ng3d t0 <font color="%s">%s
History_Already                         4lr34dy r3cl4s51f13d 45 <font color="%s">%s</font>
History_RemoveAll                       R3m0v3 4ll
History_RemovePage                      R3m0v3 P4g3
History_Remove                          T0 r3m0v3 3ntr135 1n th3 h15t0ry cl1ck
History_SearchMessage                   534rch 5ubj3ct
History_NoMessages                      N0 m3ss4g35

Password_Title                          P4s5w0rd
Password_Enter                          3nt3r p4s5w0rd
Password_Go                             G0!
Password_Error1                         1nc0rr3ct p4s5w0rd

Security_Error1                         Th3 53cur3 p0rt mu5t b3 4 numb3r b3tw33n 1 4nd 65535
Security_Stealth                        5t34lth M0d3/53rv3r 0p3r4t10n
Security_NoStealthMode                  N0 (5t34lth M0d3)
Security_ExplainStats                   (W1th th15 turn3d 0n P0PF1l3 s3nd5 0nc3 p3r d4y th3 f0ll0w1ng thr33 v4lu35 t0 4 5cr1pt 0n www.us3th350urc3.c0m: bc (th3 t0t4l numb3r 0f buck3t5 th4t y0u h4v3), mc (th3 t0t4l numb3r 0f m3ss4g35 th4t P0PF1l3 h45 cl4s51f13d) 4nd 3c (th3 t0t4l numb3r 0f cl4s51f1c4t10n 3rr0r5).  Th353 g3t 5t0r3d 1n 4 f1l3 4nd 1 w1ll u53 th15 t0 publ15h 50m3 st4t1st1c5 4b0ut h0w p30pl3 u53 P0PF1l3 4nd h0w w3ll 1t w0rk5.  My w3b 53rv3r k33p5 1t5 l0g f1l35 f0r 4b0ut 5 d4y5 4nd th3n th3y g3t d3l3t3d; 1 4m n0t 5t0r1ng 4ny c0nn3ct10n b3tw33n th3 st4t1st1c5 4nd 1nd1v1du4l 1P 4ddr3ss35.)
Security_ExplainUpdate                  (W1th th15 turn3d 0n P0PF1l3 s3nd5 0nc3 p3r d4y th3 f0ll0w1ng thr33 v4lu35 t0 4 5cr1pt 0n www.us3th350urc3.c0m: m4 (th3 m4j0r v3r510n numb3r 0f y0ur 1n5t4ll3d P0PF1l3), m1 (th3 m1n0r v3r510n numb3r 0f y0ur 1n5t4ll3d P0PF1l3) 4nd bn (th3 bu1ld numb3r 0f y0ur 1n5t4ll3d P0PF1l3).  P0PF1l3 r3c31v35 4 r3sp0n53 1n th3 f0rm 0f 4 gr4ph1c th4t 4pp34r5 4t th3 t0p 0f th3 p4g3 1f 4 n3w v3r510n 15 4v41l4bl3.  My w3b 53rv3r k33p5 1t5 l0g f1l35 f0r 4b0ut 5 d4y5 4nd th3n th3y g3t d3l3t3d; 1 4m n0t 5t0r1ng 4ny c0nn3ct10n b3tw33n th3 upd4t3 ch3ck5 4nd 1nd1v1du4l 1P 4ddr3ss35.)
Security_PasswordTitle                  U53r 1nt3rf4c3 P4s5w0rd
Security_Password                       P4s5w0rd
Security_PasswordUpdate                 Upd4t3d p4s5w0rd t0 %s
Security_AUTHTitle                      53cur3 P4s5w0rd 4uth3nt1c4t10n/4UTH
Security_SecureServer                   53cur3 53rv3r
Security_SecureServerUpdate             Upd4t3d 53cur3 53rv3r t0 %s; th15 ch4ng3 w1ll n0t t4k3 4ff3ct unt1l y0u r35t4rt P0PF1l3
Security_SecurePort                     53cur3 p0rt
Security_SecurePortUpdate               Upd4t3d p0rt t0 %s; th15 ch4ng3 w1ll n0t t4k3 4ff3ct unt1l y0u r35t4rt P0PF1l3
Security_POP3                           4cc3pt P0P3 c0nn3ct10n5 fr0m r3m0t3 m4ch1n35
Security_UI                             4cc3pt HTTP (U53r 1nt3rf4c3) c0nn3ct10n5 fr0m r3m0t3 m4ch1n35
Security_UpdateTitle                    4ut0m4t1c Upd4t3 Ch3ck1ng
Security_Update                         Ch3ck d41ly f0r upd4t35 t0 P0PF1l3
Security_StatsTitle                     R3p0rt1ng St4t1st1c5
Security_Stats                          53nd st4t1st1c5 b4ck t0 J0hn d41ly

Magnet_Error1                           M4gn3t '%s' 4lr34dy 3x1st5 1n buck3t '%s'
Magnet_Error2                           N3w m4gn3t '%s' cl4sh35 w1th m4gn3t '%s' 1n buck3t '%s' 4nd c0uld c4u53 4mb1gu0u5 r3sult5.  N3w m4gn3t w45 n0t 4dd3d.
Magnet_Error3                           Cr34t3 n3w m4gn3t '%s' 1n buck3t '%s'
Magnet_CurrentMagnets                   Curr3nt M4gn3t5
Magnet_Message1                         Th3 f0ll0w1ng m4gn3t5 c4u53 m41l t0 4lw4y5 b3 cl4s51f13d 1nt0 th3 5p3c1f13d buck3t.
Magnet_CreateNew                        Cr34t3 N3w M4gn3t
Magnet_Explanation                      Thr33 typ35 0f m4gn3t5 4r3 4v41l4bl3: </b> <ul><li><b>Fr0m 4ddr3s5 0r n4m3:</b> F0r 3x4mpl3: john\@c0mp4ny.c0m t0 m4tch 4 5p3c1f1c 4ddr3s5, <br />c0mp4ny.c0m t0 m4tch 3v3ry0n3 wh0 s3nd5 fr0m c0mp4ny.c0m, <br />J0hn D03 t0 m4tch 4 5p3c1f1c p3r50n, J0hn t0 m4tch 4ll J0hn5</li><li><b>T0 4ddr3s5 0r n4m3:</b> L1k3 4 Fr0m: m4gn3t but f0r th3 T0: 4ddr3s5 1n 4n 3m41l</li><li><b>5ubj3ct w0rd5:</b> F0r 3x4mpl3: h3ll0 t0 m4tch 4ll m3ss4g35 w1th h3ll0 1n th3 5ubj3ct</li></ul>
Magnet_MagnetType                       M4gn3t typ3
Magnet_Value                            V4lu3
Magnet_Always                           4lw4y5 g035 t0 buck3t

Bucket_Error1                           Buck3t n4m35 c4n 0nly c0nt41n th3 l3tt3r5 4 t0 z 1n l0w3r c453 plu5 - 4nd _
Bucket_Error2                           Buck3t n4m3d %s 4lr34dy 3x1st5
Bucket_Error3                           Cr34t3d buck3t n4m3d %s
Bucket_Error4                           Pl3453 3nt3r 4 n0n-bl4nk w0rd
Bucket_Error5                           R3n4m3d buck3t %s t0 %s
Bucket_Error6                           D3l3t3d buck3t %s
Bucket_Title                            5umm4ry
Bucket_BucketName                       Buck3t N4m3
Bucket_WordCount                        W0rd C0unt
Bucket_WordCounts                       W0rd C0unt5
Bucket_UniqueWords                      Un1qu3 W0rd5
Bucket_SubjectModification              5ubj3ct M0d1f1c4t10n
Bucket_ChangeColor                      Ch4ng3 C0l0r
Bucket_NotEnoughData                    N0t 3n0ugh d4t4
Bucket_ClassificationAccuracy           Cl4s51f1c4t10n 4ccur4cy
Bucket_EmailsClassified                 3m41l5 cl4s51f13d
Bucket_EmailsClassifiedUpper            3m41l5 Cl4s51f13d
Bucket_ClassificationErrors             Cl4s51f1c4t10n 3rr0r5
Bucket_Accuracy                         4ccur4cy
Bucket_ClassificationCount              Cl4s51f1c4t10n C0unt
Bucket_ResetStatistics                  R353t St4t1st1c5
Bucket_LastReset                        L45t R353t
Bucket_CurrentColor                     %s curr3nt c0l0r 15 %s
Bucket_SetColorTo                       53t %s c0l0r t0 %s
Bucket_Maintenance                      M41nt3n4nc3
Bucket_CreateBucket                     Cr34t3 buck3t w1th n4m3
Bucket_DeleteBucket                     D3l3t3 buck3t n4m3d
Bucket_RenameBucket                     R3n4m3 buck3t n4m3d
Bucket_Lookup                           L00kup
Bucket_LookupMessage                    L00kup w0rd 1n buck3t5
Bucket_LookupMessage2                   L00kup r35ult f0r
Bucket_LookupMostLikely                 <b>%s</b> 15 m05t l1k3ly t0 4pp34r 1n <font color="%s">%s</font>
Bucket_DoesNotAppear                    <p><b>%s</b> d035 n0t 4pp34r 1n 4ny 0f th3 buck3t5
Bucket_DisabledGlobally                 D154bl3d gl0b4lly

SingleBucket_Title                      D3t41l f0r %s
SingleBucket_WordCount                  Buck3t w0rd c0unt
SingleBucket_TotalWordCount             T0t4l w0rd c0unt
SingleBucket_Percentage                 P3rc3nt4g3 0f t0t4l
SingleBucket_WordTable                  W0rd T4bl3 f0r %s
SingleBucket_Message1                   5t4rr3d (*) w0rd5 h4v3 b33n u53d f0r cl4s51f1c4t10n 1n th15 P0PF1l3 s3s510n.  Cl1ck 4ny w0rd t0 l00kup 1t5 pr0b4b1l1ty f0r 4ll buck3t5.
SingleBucket_Unique                     %s un1qu3

Header_MenuSummary                      This table is the navigation menu which allows access to each of the different pages of the control center.
History_MainTableSummary                This table shows the sender and subject of recently received messages and allows them to be reviewed and reclassified.  Clicking on the subject line will show the full message text, along with information about why it was classified as it was.  The 'Should be' column allows you to specify which bucket the message belongs in, or to undo that change.  The 'Delete' column allows you to delete specific messages from the history if you don't need them anymore.
History_OpenMessageSummary              This table contains the full text of an email message, with the words that are used for classification highlighted according to the bucket that was most relevant for each.
Bucket_MainTableSummary                 This table provides an overview of the classification buckets.  Each row shows the bucket name, the word count total for that bucket, the actual number of individual words in each bucket, whether the email's subject line will be modified when it gets classified to that bucket, whether to quarantine the messages received in that bucket, and a table to pick the color used in displaying anything related to that bucket in the control center.
Bucket_StatisticsTableSummary           This table provides three sets of statistics on the overall performance of PopFile.  The first is how accurate its classification is, the second is how many emails have been classified, and to which buckets, and the third is how many words are in each bucket, and what their relative percentages are.
Bucket_MaintenanceTableSummary          This table contains forms that allow you to create, delete or rename buckets, and to lookup a word in all of the buckets to see its relative probabilities.
Bucket_AccuracyChartSummary             This table graphically represents the accuracy of the email classification.
Bucket_BarChartSummary                  This table graphically represents a percentage allocation for each of the different buckets.  It is used for both number of emails classified, and total word counts.
Bucket_LookupResultsSummary             This table shows the probabilities associated with any given word of the corpus.  For each bucket, it shows the frequency that that word occurs, the probability that it will occur in that bucket, and the overall effect on the score of the bucket if that word exists in an email.
Bucket_WordListTableSummary             This table provides a listing of all the words for a particular bucket, organized by common first letter for each row.
Magnet_MainTableSummary                 This table shows the list of magnets that are used to automatically classify email according to fixed rules.  Each row shows how the magnet is defined, what bucket it is intended for, and a button to delete the magnet.
Configuration_MainTableSummary          This table contains a number of forms to allow you to control the configuration of PopFile.
Configuration_InsertionTableSummary     This table contains buttons that determine whether or not certain modifications are made to the headers or subject line of the email before it is passed on to the email client.
Security_MainTableSummary               This table provides sets of controls that affect the security of the overall configuration of PopFile, whether it should automatically check for updates to the program, and whether statistics about PopFile's performance should be sent to the central datastore of the program's author for general information.
Advanced_MainTableSummary               This table provides a list of words that PopFile ignores when classifying email due to their relative frequency in email in general.  They are organized per row according to the first letter of the words.

