# -------------------------------------------------------------------------------
#
# POPFile Email Filter App		|	Copyright (c) 2001-2003 John Graham-Cumming
# Klingon Language dictionary 	|	Translation Beta v1.0 by Ryan Allen (kxmode@yahoo.com)
#
# -------------------------------------------------------------------------------



# IDENTIFY LANGUAGE AND CHARACTER SET USED IN INTERFACE
# -------------------------------------------------------------------------------
LanguageCode                            en
LanguageCharset                         ISO-8859-1



# USED TO GET APPROPRIATE SUBDIRECTORY FOR MANUAL
# -------------------------------------------------------------------------------
ManualLanguage                          en



# COMMON WORDS USED IN THE U.I.
# -------------------------------------------------------------------------------
Apply                               	moq
On                                  	ghaj
Off                                 	Hutlh
TurnOn                              	ghaj HoS
TurnOff                             	Hutlh HoS 
Add                                 	boq
Remove                              	teq
Previous                            	'och
Next                                	veb
From                                	Daq
Subject                             	buS
Classification                      	Segh
Reclassify                          	ngep Segh
Undo                                	tI'
Close                               	SoQmoH
Find                                	tu'
Filter                              	Segh
Yes                                 	HIja'
No                                  	pagh
ChangeToYes                         	choH' HIja'
ChangeToNo                          	choH' pagh
Bucket                              	ngaS
Magnet                              	peQ
Delete                              	Huv
Create                              	chenmoH
To                                  	choH'
Total                               	Qav
Rename                              	chu' pong
Request Feature							tlhob DuH
Frequency                           	'Ij yaH
Probability                         	DIch
Score                               	pe''egh
Lookup                              	nej
ID								    	ngu'
RequestFeure							ghel DuH



# HEADER
# -------------------------------------------------------------------------------
Header_Title                        	POP-teywI' SeHlaw (<a href="http://www.google.com/search?sourceid=navclient&ie=UTF-8&oe=UTF-8&q=klingon+translation" target="_blank">translation search on Google</a>)
Header_Shutdown                     	tlhe' DoH
Header_History                        	qun
Header_Buckets                      	ngaS
Header_Configuration                  	cher
Header_Advanced                     	veb cher
Header_Security                   		Hung
Header_Magnets                      	peQ



# FOOTER
# -------------------------------------------------------------------------------
Footer_HomePage                     	POP-teywI' juH nav
Footer_Manual                       	potlh teywI'
Footer_Forums                       	ghom ja'chuq
Footer_FeedMe                       	je' jeQ 
Footer_RequestFeature                 	ghel DuH
Footer_MailingList                   	ngoqDe' ghom



# CONFIGURATION
# -------------------------------------------------------------------------------
Configuration_Error1                	chev I lu' y'el nIteb nuv
Configuration_Error2                	SeHlaw cher Daq lu' mI' joj 1 'ej 65535
Configuration_Error3                	POP3 'Ij Daq lu' mI' joj 1 'ej 65535
Configuration_Error4                	nav ngI' lu' mI' joj 1 'ej 1000
Configuration_Error5                	mI' Hu' 'el leS lu' mI' joj 1 'ej 366
Configuration_Error6                	TCP poH luj lu' mI' joj 10 'ej 300
Configuration_POP3Port              	POP3 'Ij Daq
Configuration_POP3Update            	chu' POP3 Daq %s; choH luj qaS ghorgh SoH juS tagh POP-teywI'
Configuration_Separator             	mob I
Configuration_SepUpdate             	choH' wav %s
Configuration_UI                    	SeHlaw cher rar Daq
Configuration_UIUpdate              	choH' SeHlaw cher rar Daq %s; choH luj qaS ghorgh SoH juS tagh POP-teywI'
Configuration_History               	mI' 'el nav
Configuration_HistoryUpdate         	mI' 'el nav %s
Configuration_Days                  	mI' leS qun pol
Configuration_DaysUpdate            	choH' mI' leS qun %s
Configuration_UserInterface         	SeHlaw cher
Configuration_Skins                 	yuvtlhe'
Configuration_SkinsChoose           	woH yuvtlhe'
Configuration_Language              	Hol
Configuration_LanguageChoose        	woH Hol
Configuration_ListenPorts           	'Ij Daq
Configuration_HistoryView           	qun tu'
Configuration_TCPTimeout            	TCP rar poH luj
Configuration_TCPTimeoutSecs        	TCP rar poH luj lup
Configuration_TCPTimeoutUpdate      	choH' TCP rar poH luj %s
Configuration_ClassificationInsertion   'el ghItlh boq
Configuration_SubjectLine            	buS choH
Configuration_XTCInsertion          	X-Text-Classification Header
Configuration_XPLInsertion          	X-POPFile-Link Header
Configuration_Logging                  	QonoS
Configuration_None                    	chIm
Configuration_ToScreen                	HaSta
Configuration_ToFile            		teywI'
Configuration_ToScreenFile       		HaSta 'ej teywI'
Configuration_LoggerOutput            	'agh QonoS
Configuration_GeneralSkins           	yuvtlhe'
Configuration_SmallSkins            	mach yuvtlhe'
Configuration_TinySkins           		moch mach yuvtlhe'
Configuration_MainTableSummary          raS ngaS mI' ghel nav nob chaw' tlhIH nob SeH choH POP-teywI'.
Configuration_InsertionTableSummary     raS ngaS SeH 'e' wIv vogh na' Hutlh choH chenmoH nob Dung QIn lurgh ghom'a' 'ul ngoqDe' pupfe chaw' nob 'ul ngoqDe' vay'.



# ADVANCED ERRORS MESSAGES
# -------------------------------------------------------------------------------
Advanced_Error1                     	'%s' 'och qImHa' mu' tetlh
Advanced_Error2                     	'och mu' vang neH ngaS mu' 'ej mI', _, -, @ Doch
Advanced_Error3                     	'%s' boq qImHa' mu' tetlh
Advanced_Error4                     	'%s' pagh qImHa' mu' tetlh
Advanced_Error5                     	'%s' teq Daq pagh mu' tetlh
Advanced_StopWords                  	pagh mu'
Advanced_Message1                   	POP-teywI' pagh pIj-lo' mu':
Advanced_AddWord                    	boq mu'
Advanced_RemoveWord                 	teq mu'



# HISTORY
# -------------------------------------------------------------------------------
History_Filter                        	&nbsp;(neH 'ang ngaS <font color="%s">%s</font>)
History_FilterBy                      	Segh
History_Search                        	&nbsp;(nej Daq/buS %s)
History_Title                      		SaH 'el
History_Jump                          	ghoS 'el
History_ShowAll                       	'agh Hoch
History_ShouldBe                      	qIt
History_NoFrom                        	Hutlh Daq tlhegh
History_NoSubject                     	Hutlh buS tlhegh
History_ClassifyAs                     	Segh
History_MagnetBecause                  	peQ lo'
History_ChangedTo                     	choH <font color="%s">%s
History_Already                       	SaH Segh <font color="%s">%s</font>
History_RemoveAll                     	teq Hoch
History_RemovePage                    	teq nav
History_Remove                        	teq ngoqDe' qun 'uy
History_SearchMessage                 	nej Daq/buS
History_NoMessages                    	Hutlh 'el
History_ShowMagnet                   	peQ
History_Magnet                        	&nbsp;(nIteb 'agh peQ Segh 'el)
History_ResetSearch                   	Huv
History_MainTableSummary                raS 'ang HIjwI' 'ej lurgh qen Hev QIn 'ej chaw' nob tagh nej 'ej rebuv. tagh lurgh ghom'a' lu' 'ang naQ QIn mu', ngagh De' buS qatlh Hu' buv Hu'. teq pup' tut chaw' tlhIH nob per ngaS QIn pup' qoD,  nob undo 'e' choH. 'HoH' tut chaw' tlhIH nob HoH Hum QIn nob qun tlhIH luj neH 'op.
History_OpenMessageSummary              raS ngaS naQ mu' 'ul ngoqDe' QIn, mu' 'e' lo' Segh highlighted rom nob ngaS 'e' Hu' tIn potlh.



# PASSWORD
# -------------------------------------------------------------------------------
PassWord_Title                     		'el mu' 
PassWord_Enter                      	ghItlh 'el mu'
PassWord_Go                         	tagh!
PassWord_Error1                     	Hutlh lugh 'el mu'



# SECURITY
# -------------------------------------------------------------------------------
Security_Error1                   		Hung Daq lu' mI' joj 1 'ej 65535
Security_Stealth                  		So' Segh/Daq yo'SeH yaHnIv
Security_NoStealthMode            		ghItlh (So' Segh)
Security_ExplainStats             		(chegh POP-teywI' ngeH wa' bem jaj pab wej lo'laHghach nob ghItlh www.usesource.com: bc (Qav mI' ngaS 'e' tlhIH ghaj), mc (Qav mI' 'el 'e' POP-teywI' buv) 'ej ec (Qav mI' Segh  Qagh). se Suq 'el teywI' 'ej I lu' lo' nob lIng 'op boS De' buS bey ghom'a' lo' POP-teywI' 'ej bey majQa' Doch Qap. tlhIl Daq Dochs QonoS teywI's nej buS 5 leS 'ej n y Suq teq; I Qotlh yer law' rar joj boS De' 'ej 'eldividual IP Daq.)
Security_ExplainUpdate             		(chegh POP-teywI' ngeH wa' bem jaj pab wej lo'laHghach nob ghItlh www.usesource.com: ma ( tIn puq poH mI' Hutlh tlhIl 'elstalled POP-teywI'), mI' ( m'elor puq poH mI' Hutlh tlhIl 'elstalled POP-teywI') 'ej bn ( chen mI' Hutlh tlhIl 'elstalled POP-teywI'). POP-teywI' Hev jang 'el nejm HaSta 'e' nargh yor nav chu' puq poH SaH. tlhIl Daq Dochs QonoS teywI's nej buS 5 leS 'ej n y Suq teq; I Qotlh yer law' rar joj chu' nej 'ej 'eldividual IP Daq.)
Security_PasswordTitle           		SeHlaw 'el mu'
Security_Password                  		'el mu'
Security_PasswordUpdate              	chu' 'el mu' nob %s
Security_AUTHTitle                 		Hung 'el mu' 'ol/AUTH
Security_SecureServer              		Hung Daq
Security_SecureServerUpdate          	chu' Hung Daq nob %s; choH lu' Hutlh chen vang loS tlhIH tagh POP-teywI'
Security_SecurePort                		Hung Daq
Security_SecurePortUpdate            	chu' Daq nob %s; choH lu' Hutlh chen vang loS tlhIH tagh POP-teywI'
Security_POP3                      		Qochbe' POP3 rars qang Hop mach'eles (poQ POP-teywI' tagh)
Security_UI                     		Qochbe' HTTP (SeHlaw) rars qang Hop mach'eles  (poQ POP-teywI' tagh)
Security_UpdateTitle               		jeQ tagh chu' nej 'elg
Security_Update                      	nej Hoch DaHjaj nej chu' nob POP-teywI'
Security_StatsTitle                     lI' togh De'
Security_Stats                          ngeH boS De' Hoch DaHjaj
Security_MainTableSummary               raS nob chenmoH SeH 'e' choH Hung natlh choH POP-teywI', vogh neH ra' Hutlh nej chu' nob ghun, 'ej vogh boS De' buS POP-teywI' vang lI' nob Daq HovpoH ghun's ngup Sa' De'.



# MAGNETS
# -------------------------------------------------------------------------------
Magnet_Error1                        	peQ '%s' DaH latlh 'el ngaS '%s'
Magnet_Error2                        	chu' peQ '%s' clashes peQ '%s' 'el ngaS '%s' 'ej calo' Hon ngoQ. chu' peQ Hutlh boq.
Magnet_Error3                        	chenmoH chu' peQ '%s' 'el ngaS '%s'
Magnet_CurrentMagnets                	SaH peQ
Magnet_Message1                      	pab peQ lo' QIn nob reH buv 'elto chuH ngaS.
Magnet_CreateNew                       	chenmoH chu' peQ
Magnet_Explanation                     	wej Segh peQ are SaH:</b> <ul><li><b>qang Daq pong:</b> vaj: john@company.com nob 'Iq le'be' Daq, <br />company.com nob 'Iq Hoch who ngeH qang company.com, <br />John Doe nob 'Iq le'be' ghot, John nob 'Iq all Johns</li><li><b>nob Daq pong:</b> Like qang: peQ but nej nob: Daq 'el 'ul ngoqDe'</li> <li><b>lut ghItlh:</b> vaj: ghom nob 'Iq all 'el ghom 'el lut</li></ul>
Magnet_MagnetType                    	peQ Segh
Magnet_Value                         	lo'laHghach
Magnet_Always                        	Qeq nob ngaS
Magnet_MainTableSummary                 raS 'ang tetlh peQ 'e' lo' nob ra' Hutlh Segh 'ul ngoqDe' rom nob chut. 'ang 'ar peQ buv, ngaS Hech, 'ej SeH nob HoH peQ.



# BUCKETS
# -------------------------------------------------------------------------------
Bucket_Error1                        	ngaS pong ngaS ta'el mu' A nob Z 'el mu' latlh - 'ej _
Bucket_Error2                        	ngaS pong %s DaH latlh
Bucket_Error3                        	chenmoH ngaS pong %s
Bucket_Error4                        	ghItlh non-blank mu'
Bucket_Error5                        	chu' pong ngaS %s nob %s
Bucket_Error6                        	nguv ngaS %s
Bucket_Title	                       	qum tu'
Bucket_BucketName                    	ngaS pong
Bucket_WordCount                     	mu' togh
Bucket_WordCounts                    	mu' Qav
Bucket_UniqueWords                   	Hutlh mung nIteb mu'
Bucket_SubjectModification              buS choH
Bucket_ChangeColor                   	choH rItlh
Bucket_NotEnoughData                    Hutlh yap da
Bucket_ClassificationAccuracy           Segh DoS
Bucket_EmailsClassified                 'ul ngoqDe' buv
Bucket_EmailsClassifiedUpper           	'ul ngoqDe' Qum
Bucket_ClassificationErrors             Segh Qagh
Bucket_Accuracy                      	DoS
Bucket_ClassificationCount              Segh Qav
Bucket_ResetStatistics                  Huv Dotlh
Bucket_LastReset                     	ret Huv
Bucket_CurrentColor                  	%s SaH rItlh %s
Bucket_SetColorTo                    	Set %s rItlh nob %s
Bucket_Maintenance                      leH
Bucket_CreateBucket                    	chenmoH ngaS tlhej pong
Bucket_DeleteBucket                  	Huv ngaS pong
Bucket_RenameBucket                  	choH ngaS pong
Bucket_Lookup                        	nej
Bucket_LookupMessage                 	nej mu' ngaS
Bucket_LookupMessage2                	nej result nej
Bucket_LookupMostLikely              	<b>%s</b> tlhoS ghaytan nob nargh 'el <font color="%s">%s</font>
Bucket_DoesNotAppear                 	<p><b>%s</b> Hutlh nargh 'el law' ngaS
Bucket_DisabledGlobally                 Hutlh Qap 
Bucket_To                            	nob
Bucket_Quarantine                       nIteb 'ay' 
Bucket_MainTableSummary                 raS nob nej Segh ngaS. 'ang ngaS pong, mu' togh Qav 'e' ngaS, teH mI' QIn qoD ngaS, vogh 'ul ngoqDe''s lurgh ghom'a' lu' choH ghorgh Suqs buv nob 'e' ngaS, vogh nob nID teq jav DoH ghom'a' QIn Hev qoD 'e' ngaS, 'ej raS nob woH col lo' qoD HaSta vay' rap nob 'e' ngaS qoD SeH botlh.
Bucket_StatisticsTableSummary           raS nob wej Daq boS De' natlh vang POP-teywI'. wa'Dich 'ar qar Segh, cha'Dich 'ar togh 'ul ngoqDe's ghaj pupen buv, 'ej nob ngaS, 'ej  wejDich 'ar togh mu' qoD ngaS, 'ej nuq ghaytan Qav.
Bucket_MaintenanceTableSummary          raS ngaS ghel nav 'e' chaw' tlhIH nob chenmoH, HoH ngep pong ngaS, 'ej nob nej mu' qoD Hoch ngaS nob legh ghaytan DuH.
Bucket_AccuracyChartSummary             raS HaSta ghaytan DoS 'ul ngoqDe' Segh.
Bucket_BarChartSummary                  raS HaSta ghaytan Qav 'ay' pIm ngaS. Doch lo' both mI' 'ul ngoqDe's buv, 'ej Qav mu' toghs.
Bucket_LookupResultsSummary             raS 'ang 'ay' ngu' vay' nob mu' corpus.  ngaS, 'ang nargh 'e' mu' qaS, ghaytan 'e' lu' qaS qoD 'e' ngaS, 'ej  natlh ngoQ pe''egh ngaS 'e' mu' yIn qoD 'ul ngoqDe'.
Bucket_WordListTableSummary             raS nob tetlh Hoch  mu' 'ay' ngaS, 'obe' motlh wa'Dich mu'.

SingleBucket_Title                		Detail nej %s
SingleBucket_WordCount              	ngaS mu' togh
SingleBucket_TotalWordCount         	Qav mu' togh
SingleBucket_Percentage             	tlhoS Qav
SingleBucket_WordTable              	mu' Doch nej %s
SingleBucket_Message1               	Hov (*) ghItlh ghaj lo'd nej Segh 'el POP-teywI' Dotlh. 'uy law' mu' nob nej ghaytan Dochs nej Hoch ngaS.
SingleBucket_Unique                 	%s Hutlh mung



# SESSION INFO
# -------------------------------------------------------------------------------
Session_Title                      		POP-teywI' Dotlh Hegh
Session_Error                        	POP-teywI' Dotlh Hegh. ghaj calo'd tagh 'ej mev POP-teywI' wej mej Hutlh tlhIl browser Qap. 'uy wa' l'elks Dung nob Qap POP-teywI'.



# MISC.
# -------------------------------------------------------------------------------
Header_MenuSummary                      raS chIj HIDjolev chaw' naw' nob pIm nav SeH botlh.
Advanced_MainTableSummary               raS nob tetlh mu' 'e' POP-teywI' buSHa' ghorgh Segh 'ul ngoqDe' nob ghaytan qaS qoD 'ul ngoqDe' qoD Sa'. Segh pupm rom nob wa'Dich mu'.