MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
X-MIME-Autoconverted: from 8bit to quoted-printable by mail.datasync.com id h1KNLSI27579


# Identify the language and character set used for the interface
LanguageCode                            no
LanguageCharset                         ISO-8859-1

# This is used to get the appropriate subdirectory for the manual
ManualLanguage                          no

# Common words that are used on their own all over the interface
Apply                                   Bruk
On                                      P=E5
Off                                     Av
TurnOn                                  Sl=E5 p=E5
TurnOff                                 Sl=E5 av
Add                                     Legg til
Remove                                  Fjern
Previous                                Forrige
Next                                    Neste
From                                    Fra
Subject                                 Emne
Classification                          Klassifisering
Reclassify                              Re-klassifisering
Undo                                    Angre
Close                                   Lukk
Find                                    S=F8k
Filter                                  Filtrer
Yes                                     Ja
No                                      Nei
ChangeToYes                             Skift til Ja
ChangeToNo                              Skift til Nei
Bucket                                  B=F8tte
Magnet                                  Magnet
Delete                                  Slett
Create                                  Opprett
To                                      Til
Total                                   Total
Rename                                  Omd=F8p
Frequency                               Frekvens
Probability                             Sannsynlighet
Score                                   Resultat
Lookup                                  S=F8k etter

# The header and footer that appear on every UI page
Header_Title                            POPFile Kontrollsenter
Header_Shutdown                         Lukk POPFile
Header_History                          Logg
Header_Buckets                          B=F8tter
Header_Configuration                    Konfigurering
Header_Advanced                         Avansert
Header_Security                         Sikkerhet
Header_Magnets                          Magneter

Footer_HomePage                         POPFile Hjemmeside
Footer_Manual                           Manual
Footer_Forums                           Diskusjonsforum
Footer_FeedMe                           Mat meg!
Footer_RequestFeature                   Ettersp=F8r funksjoner
Footer_MailingList                      Mailingliste

Configuration_Error1                    Skilletegnet skal v=E6re ett enke=
lt tegn
Configuration_Error2                    Brukergrensesnittets port skal v=E6=
re et nummer mellom 1 og 65535
Configuration_Error3                    POP3-porten skal v=E6re et nummer=
 mellom 1 og 65535
Configuration_Error4                    Sidens st=F8rrelse skal v=E6re me=
llom 1 og 1000
Configuration_Error5                    Antall dager i loggen skal v=E6re=
 et tall mellom 1 og 366
Configuration_Error6                    TCP-tidsavbrudd skal v=E6re et ta=
ll mellom 10 og 300
Configuration_POP3Port                  POP3-porten
Configuration_POP3Update                Oppdaterte porten til %s; Denne e=
ndringen vil ikke tre i kraft f=F8r POPFile er startet p=E5 nytt
Configuration_Separator                 Skilletegn
Configuration_SepUpdate                 Oppdaterte skilletegnet til %s
Configuration_UI                        Brukergrensesnittets web-port
Configuration_UIUpdate                  Oppdaterte Brukergrensesnittets w=
eb-port til %s; endringen vil ikke tre i kraft f=F8r POPFile startes p=E5=
 nytt
Configuration_History                   Antall e-post pr. side
Configuration_HistoryUpdate             Oppdaterte antall e-post pr. side=
 til %s
Configuration_Days                      Antall dager oppf=F8ringer i logg=
en skal beholdes
Configuration_DaysUpdate                Oppdaterte antall dager oppf=F8ri=
nger i loggen skal beholdes til %s
Configuration_UserInterface             Brukergrensesnittet
Configuration_Skins                     Skins
Configuration_SkinsChoose               Velg skin
Configuration_Language                  Spr=E5k
Configuration_LanguageChoose            Velg spr=E5k
Configuration_ListenPorts               POP3-porten
Configuration_HistoryView               Logg-visning
Configuration_TCPTimeout                TCP-forbindelsens tidsavbrudd
Configuration_TCPTimeoutSecs            TCP-forbindelsens tidsavbrudd i s=
ekunder
Configuration_TCPTimeoutUpdate          Oppdaterte TCP-forbindelsens tids=
avbrudd til %s
Configuration_ClassificationInsertion   Klassifikasjonsm=E5ter (innsettin=
g)
Configuration_SubjectLine               Emnelinje-innsetting
Configuration_XTCInsertion              X-Text-Classification innsetting
Configuration_XPLInsertion              X-POPFile-Link innsetting
Configuration_Logging                   Logging
Configuration_None                      Ingen
Configuration_ToScreen                  Til Skjerm
Configuration_ToFile                    Til Fil
Configuration_ToScreenFile              Til Skjerm og Fil
Configuration_LoggerOutput              Logger output

Advanced_Error1                         '%s' Er allerede i Stoppordlisten
Advanced_Error2                         Stoppord kan kun inneholde Alfanu=
meriske tegn, ., _, -, eller @ tegn
Advanced_Error3                         '%s' er lagt til i stoppordlisten
Advanced_Error4                         '%s' er ikke i stoppordlisten
Advanced_Error5                         '%s' er fjernet fra stoppordliste=
n
Advanced_StopWords                      Stoppord
Advanced_Message1                       Disse ordene blir ignorert fra al=
l klassifisering fordi de forekommer meget ofte.
Advanced_AddWord                        Legg til ord
Advanced_RemoveWord                     Fjern ord

History_Filter                          &nbsp;(vis kun b=F8tten<font colo=
r=3D"%s">%s</font>)
History_FilterBy                        Filter By
History_Search                          &nbsp;(s=F8k emne for %s)
History_Title                           Siste meldinger
History_Jump                            Hopp til melding
History_ShowAll                         Vis alle
History_ShouldBe                        Skulle v=E6re
History_NoFrom                          ingen Fra-linje
History_NoSubject                       ingen Emne-linje
History_ClassifyAs                      klassifisert som
History_MagnetUsed                      Magnet brukt
History_ChangedTo                       Endret til <font color=3D"%s">%s
History_Already                         Re-klassifisert som <font color=3D=
"%s">%s</font>
History_RemoveAll                       Fjern alle
History_RemovePage                      Fjern side
History_Remove                          For =E5 fjerne oppf=F8ringer i lo=
ggen, klikk
History_SearchMessage                   S=F8k Emne
History_NoMessages                      Ingen meldinger

Password_Title                          Passord
Password_Enter                          Skriv inn passord
Password_Go                             OK!
Password_Error1                         Feil passord

Security_Error1                         Den sikre porten skal v=E6re et t=
all mellom 1 og 65535
Security_Stealth                        Stealth Mode/Server Operation
Security_NoStealthMode                  Nei (Stealth Mode)
Security_ExplainStats                   (Denne funksjonen sender en gang =
per dag de etterf=F8lgene tre verdiene til et script hos wwwu.sethesource=
.com: bc (det totale antall b=F8tter du har) mc (det totale antall i meld=
inger som POPFile har klassifisert ) og ec (det totale antall klassifiser=
ingsfeil). Disse blir lageret i en fil og jeg vil bruke disse data til =E5=
 offentligj=F8re statistikk omkring hvordan folk bruker POPFile og hvor g=
odt POPFile virker. Min web-server beholder denne log-filen omtrent 5 dag=
er og blir s=E5 slettet; Jeg lagrer ingen forbindelse mellom statistikken=
 og individuelle IP-adresser.)
Security_ExplainUpdate                  (Denne funksjonen sender en gang =
per dag de  etterf=F8lgene tre verdiene til et script hos wwwu.sethesourc=
e.com: ma (hovedversjonsnummeret p=E5 din installerte POPFile), mi (under=
-versjonsnummeret p=E5 din installerte POPFile) og bn (build nummer p=E5 =
din installerte POPFile). POPFile mottar et svar i form av et stykke graf=
ikk som vises i toppen av siden, hvis en ny version er tilgjengelig. Min =
web-server tar vare p=E5 denne log-filen omtrent 5 dager og de blir s=E5 =
slettet; Jeg lagrer ingen forbindelse mellom statistikken og individuelle=
 IP-adresser.)
Security_PasswordTitle                  Brukergrensesnittets Passord
Security_Password                       Passord
Security_PasswordUpdate                 Oppdater passord til %s
Security_AUTHTitle                      Godkjenning av sikkert passord
Security_SecureServer                   Sikker Server
Security_SecureServerUpdate             Opdaterte sikker server til %s; d=
enne endringen vil ikke tre i kraft f=F8r omstart av POPFile
Security_SecurePort                     Sikker port
Security_SecurePortUpdate               Opdaterte porten til %s; denne en=
dringen vil ikke tre i kraft f=F8r omstart av POPFile
Security_POP3                           Godta POP3-tilkoblinger fra andre=
 maskiner
Security_UI                             Godta HTTP (Brukergrensesnitt) ti=
lkoblinger fra andre maskiner
Security_UpdateTitle                    Automatisk Oppdaterings-kontroll
Security_Update                         Kontroller daglig om det finnes o=
ppdateringer til POPFile
Security_StatsTitle                     Statistikk-rapportering
Security_Stats                          Send statistikk tilbake til John =
daglig

Magnet_Error1                           Magneten '%s' finnes allrede i b=F8=
tten'%s'=20
Magnet_Error2                           Den nye magneten '%s' er i konfli=
kt med magneten '%s' i b=F8tten '%s' og kan gi flertydige resultater. Den=
 nye magneten ble ikke tilf=F8yd.
Magnet_Error3                           Opprettet den nye magneten '%s' i=
 b=F8tten '%s'
Magnet_CurrentMagnets                   N=E5v=E6rende Magneter
Magnet_Message1                         De f=F8lgende magnetene gj=F8r at=
 e-post alltid blir klassifisert til den spesifiserte b=F8tten.
Magnet_CreateNew                        Opprett Ny Magnet
Magnet_Explanation                      Tre typer magneter er anbefalt: <=
ul><li>Fra adressen eller navn:</b> For eksempel: john@firma.dk for =E5 m=
atche en spesifikk adresse, <br />firma.dk for =E5 matche alle som sender=
 fra firma.dk, <br />John Doe for =E5 matche en spesifikk person, John fo=
r =E5 matche alle John'er</li><li><b>Til adresse eller navn:</b> Samme so=
m en Fra: Magnet men bare for Til: Adressen i en e-post</li><li><b>Emne-o=
rd:</b> For eksempel: hei for =E5 matche alle meldinger med ordet hei i e=
mnet</li></ul>
Magnet_MagnetType                       Magnettyper
Magnet_Value                            Verdier
Magnet_Always                           Tilh=F8rer alltid b=F8tten

Bucket_Error1                           B=F8ttenes navn kan kun inneholde=
 bokstavene a til z med sm=E5 bokstaver, samt - og _
Bucket_Error2                           B=F8tten med navnet %s eksisterer=
 allerede
Bucket_Error3                           Opprett b=F8tten med navnet %s
Bucket_Error4                           Skriv venligst ikke et tomt ord
Bucket_Error5                           Omd=F8p b=F8tten %s til %s
Bucket_Error6                           Slett b=F8tten %s
Bucket_Title                            Oversikt
Bucket_BucketName                       B=F8ttenes navn
Bucket_WordCount                        Ordtelling
Bucket_WordCounts                       Ordfordeling
Bucket_UniqueWords                      Unike ord
Bucket_SubjectModification              Emne-modifisering
Bucket_ChangeColor                      Skift farge
Bucket_NotEnoughData                    Ikke nok data
Bucket_ClassificationAccuracy           Klassifikasjons-n=F8yaktighet
Bucket_EmailsClassified                 Antall e-post klassifisert
Bucket_EmailsClassifiedUpper            Antall e-post klassifisert
Bucket_ClassificationErrors             Klassifiseringsfeil
Bucket_Accuracy                         N=F8yaktighet
Bucket_ClassificationCount              Klassifiseringstelling
Bucket_ResetStatistics                  Nullstill Statistikkene
Bucket_LastReset                        Sist nullstilt
Bucket_CurrentColor                     %s N=E5v=E6rende farge er %s
Bucket_SetColorTo                       Sett %s fargen til %s
Bucket_Maintenance                      Vedlikehold
Bucket_CreateBucket                     Oppret b=F8tten med navnet
Bucket_DeleteBucket                     Slett b=F8tten med navnet
Bucket_RenameBucket                     Omd=F8p b=F8tten med navnet
Bucket_Lookup                           S=F8k etter
Bucket_LookupMessage                    S=F8k etter ord i b=F8ttene
Bucket_LookupMessage2                   S=F8keresultatet for
Bucket_LookupMostLikely                 Det er mest sannsynlig at <b>%s</=
b> forekommer i <font color=3D"%s">%s</font>
Bucket_DoesNotAppear                    <p><b>%s</b> forekommer ikke i no=
en av b=F8ttene
Bucket_DisabledGlobally                 Deaktivert globalt
Bucket_To                               til
Bucket_Quarantine                       Karantene

SingleBucket_Title                      Detaljer for %s
SingleBucket_WordCount                  Totalt antall ord i b=F8tten
SingleBucket_TotalWordCount             Totalt antall ord
SingleBucket_Percentage                 Prosentandelen av totalen
SingleBucket_WordTable                  Ord tabell for %s
SingleBucket_Message1                   Markerte (*) ord er blitt brukt t=
il =E5 klassifisere i denne POPFile-sesjonen. Trykk p=E5 hvilket som hels=
t ord for =E5 sl=E5 opp dens sannsynlighet for alle b=F8ttene.
SingleBucket_Unique                     %s unike
