MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
X-MIME-Autoconverted: from 8bit to quoted-printable by mail.datasync.com id h1KNLSI27579


# Identify the language and character set used for the interface
LanguageCode                            br
LanguageCharset                         ISO-8859-1

# This is used to get the appropriate subdirectory for the manual
ManualLanguage                          br
=20
# Common words that are used on their own all over the interface
Apply                                   Aplicar
On                                      Ligado
Off                                     Desligado
TurnOn                                  Ligar
TurnOff                                 Desligar
Add                                     Adicionar
Remove                                  Remover
Previous                                Anterior
Next                                    Pr=F3ximo
From                                    De
Subject                                 Assunto
Classification                          Classifica=E7=E3o
Reclassify                              Reclassificar
Undo                                    Desfazer
Close                                   Fechar
Find                                    Procurar
Filter                                  Filtrar
Yes                                     Sim
No                                      N=E3o
ChangeToYes                             Trocar para Sim
ChangeToNo                              Trocar para N=E3o
Bucket                                  Bucket
Magnet                                  =CDm=E3
Delete                                  Deletar
Create                                  Criar
To                                      Para
Total                                   Total
Rename                                  Renomear
Frequency                               Freq=FC=EAncia
Probability                             Probabilidade
Score                                   Pontua=E7=E3o
Lookup                                  Procurar

# The header and footer that appear on every UI page
Header_Title                            Centro de Controle POPFile
Header_Shutdown                         Desligar
Header_History                          Hist=F3rico
Header_Buckets                          Buckets
Header_Configuration                    Configura=E7=E3o
Header_Advanced                         Avan=E7ado
Header_Security                         Securan=E7a
Header_Magnets                          =CDm=E3s

Footer_HomePage                         POPFile Home Page
Footer_Manual                           Manual
Footer_Forums                           Forums
Footer_FeedMe                           Me Mantenha!
Footer_RequestFeature                   Pedir uma Caracter=EDstica
Footer_MailingList                      Lista de Email

Configuration_Error1                    O caracter separador deve ser um =
=FAnico caracter
Configuration_Error2                    O porta da interface de usu=E1rio=
 deve ser um n=FAmero entre 1 e 65535
Configuration_Error3                    A porta de escuta POP3 deve ser u=
m n=FAmero entre 1 e 65535
Configuration_Error4                    O tamanho da p=E1gina deve ser um=
 n=FAmero entre 1 e 1000
Configuration_Error5                    O n=FAmero de dias no hist=F3rico=
 deve ser um n=FAmero entre 1 e 366
Configuration_Error6                    O tempo limite TCP deve ser um n=FA=
mero entre 10 e 300
Configuration_POP3Port                  Porta de escuta POP3
Configuration_POP3Update                Alterada a porta para %s; esta al=
tera=E7=E3o n=E3o ter=E1 efeito at=E9 que voc=EA reinicie o POPFile
Configuration_Separator                 Caracter separador
Configuration_SepUpdate                 Alterado o separador para %s
Configuration_UI                        Porta da interface web de usu=E1r=
io
Configuration_UIUpdate                  Alterada a porta da interface web=
 de usu=E1rio para %s; esta altera=E7=E3o n=E3o ter=E1 efeito at=E9 que v=
oc=EA reinicie o POPFile
Configuration_History                   N=FAmero de emails por p=E1gina
Configuration_HistoryUpdate             Alterado o n=FAmero de emails por=
 p=E1gina para %s
Configuration_Days  `                   N=FAmero de dias para manter no h=
ist=F3rico
Configuration_DaysUpdate                Alterado o n=FAmero de dias para =
manter no hist=F3rico para %s
Configuration_UserInterface             Interface de Usu=E1rio
Configuration_Skins                     Skins
Configuration_SkinsChoose               Escolha o skin
Configuration_Language                  Linguagem
Configuration_LanguageChoose            Escolha a linguagem
Configuration_ListenPorts               Portas de Escuta
Configuration_HistoryView               Exibir Hist=F3rico
Configuration_TCPTimeout                Tempo Limite de Conex=E3o TCP
Configuration_TCPTimeoutSecs            Tempo limite de conex=E3o TCP em =
segundos
Configuration_TCPTimeoutUpdate          Alterado o tempo limite de conex=E3=
o TCP para %s
Configuration_ClassificationInsertion   Inser=E7=E3o de Classifica=E7=E3o
Configuration_SubjectLine               Modifica=E7=E3o de linha de assun=
to
Configuration_XTCInsertion              Inser=E7=E3o de X-Text-Classifica=
tion
Configuration_XPLInsertion              Inser=E7=E3o de X-POPFile-Link
Configuration_Logging                   Logging
Configuration_None                      Nada
Configuration_ToScreen                  Na Tela
Configuration_ToFile                    Em Arquivo
Configuration_ToScreenFile              Na Tela e em Arquivo
Configuration_LoggerOutput              Sa=EDda do Logger

Advanced_Error1                         '%s' j=E1 est=E1 na lista de pala=
vras ignoradas
Advanced_Error2                         Palavras ignoradas podem somente =
conter caracteres alfanum=E9ricos, ., _, -, ou @
Advanced_Error3                         '%s' adicionado na lista de palav=
ras ignoradas
Advanced_Error4                         '%s' n=E3o est=E3 na lista de pal=
avras ignoradas
Advanced_Error5                         '%s' removido da lista de palavra=
s ignoradas
Advanced_StopWords                      Palavras Ignoradas
Advanced_Message1                       As seguintes palavras s=E3o ignor=
adas de todas as classifica=E7=F5es porque ocorrem muito freq=FCentemente.
Advanced_AddWord                        Adicionar palavra
Advanced_RemoveWord                     Remover palavra

History_Filter                          &nbsp;(apenas mostrando o bucket =
<font color=3D"%s">%s</font>)
History_FilterBy                        Filter By
History_Search                          &nbsp;(procurado pelo assunto %s)
History_Title                           Mensagens Recentes
History_Jump                            Ir para a mensagem
History_ShowAll                         Exibir Tudo
History_ShouldBe                        Deveria ser
History_NoFrom                          sem linha de
History_NoSubject                       sem linha de assunto
History_ClassifyAs                      Classificar como
History_MagnetUsed                      =CDma usado
History_ChangedTo                       Alterado para <font color=3D"%s">=
%s
History_Already                         J=E1 reclassificado como <font co=
lor=3D"%s">%s</font>
History_RemoveAll                       Remover Tudo
History_RemovePage                      Remover a P=E1gina
History_Remove                          Para remover entradas do hist=F3r=
ico clique
History_SearchMessage                   Procurar Assunto
History_NoMessages                      Nenhuma mensagem
History_ShowMagnet                      Magnetizado
History_Magnet                          &nbsp;(apenas mostrando mensagens=
 classificadas por =EDma)

Password_Title                          Senha
Password_Enter                          Digite a senha
Password_Go                             Ir!
Password_Error1                         Senha incorreta

Security_Error1                         A porta segura deve ser um n=FAme=
ro entre 1 e 65535
Security_Stealth                        Modo Stealth/Opera=E7=E3o Servido=
r
Security_NoStealthMode                  N=E3oo (Modo Stealth)
Security_ExplainStats                   (Com isto ligado o POPFile envia =
uma vez por dia os seguintes tr=EAs valores para um script em www.usethes=
ource.com: bc (o n=FAmero total de buckets que voc=EA tem), mc (o n=FAmer=
o total de mensagens que o POPFile classificou) e ec (o n=FAmero total de=
 erros de classifica=E7=E3o).  Isto fica guardado em um arquivo e eu vou =
usar para publicar algumas estat=EDsticas sobre como as pessoas usam o PO=
PFile e o qu=E3o bem ele funciona.  Meu servidor web mant=E9m seus arquiv=
os de log por mais ou menos 5 dias e ent=E3o os deleta; Eu n=E3o estou gu=
ardando nenhuma conex=E3o entre as estat=EDstcas e os endere=E7os IP de c=
ada um.)
Security_ExplainUpdate                  (Com isto ligado o POPFile envia =
uma vez por dia os seguintes tr=EAs valores para um script em www.usethes=
ource.com: ma (o n=FAmero maior da vers=E3o do seu POPFile), mi (o n=FAme=
ro menor da vers=E3o do seu POPFile) and bn (o n=FAmero do build da sua v=
ers=E3o do POPFile). O POPFile recebe uma resposta na forma de um gr=E1fi=
co que aparece no topo da p=E1gina se uma nova vers=E3o estiver dispon=ED=
vel.  Meu servidor web mant=E9m seus arquivos de log por mais ou menos 5 =
dias e ent=E3o os deleta; Eu n=E3o estou guardando nenhuma conex=E3o entr=
e as verifica=E7=F5es de vers=E3o e os endere=E7os IP de cada um.)
Security_PasswordTitle                  Senha da Interface de Usu=E1rio
Security_Password                       Senha
Security_PasswordUpdate                 Alterada a senha para %s
Security_AUTHTitle                      Autentica=E7=E3o Segura de Senha/=
AUTH
Security_SecureServer                   Servidor Seguro
Security_SecureServerUpdate             Alterado o servidor seguro para %=
s; esta altera=E7=E3o n=E3o ter=E1 efeito at=E9 que voc=EA reinicie o POP=
File
Security_SecurePort                     Porta segura
Security_SecurePortUpdate               Alterada a porta para %s; esta al=
tera=E7=E3o n=E3o ter=E1 efeito at=E9 que voc=EA reinicie o POPFile
Security_POP3                           Aceitar conex=F5es POP3 de m=E1qu=
inas remotas
Security_UI                             Aceitar conex=F5es HTTP (Interfac=
e de Usu=E1rio) de m=E1quinas remotas
Security_UpdateTitle                    Verifica=E7=E3o Autom=E1tica de A=
tualiza=E7=E3o
Security_Update                         Verificar diariamente atualiza=E7=
=F5es para o POPFile
Security_StatsTitle                     Reportar Estat=EDsticas
Security_Stats                          Enviar estat=EDsticas para o John=
 diariamente

Magnet_Error1                           =CDm=E3 '%s' j=E1 existe no bucke=
t '%s'
Magnet_Error2                           O novo =EDm=E3 '%s' conflita com =
o =EDm=E3 '%s' no bucket '%s' e pode causar resultados amb=EDguos.  O nov=
o =EDm=E3 n=E3o foi adicionado.
Magnet_Error3                           Criar novo =EDm=E3 '%s' no bucket=
 '%s'
Magnet_CurrentMagnets                   =CDm=E3s Atuais
Magnet_Message1                         Os seguintes =EDm=E3s fazem os em=
ails serem sempre classificados no bucket especificado.
Magnet_CreateNew                        Criar Novo =CDm=E3
Magnet_Explanation                      Tr=EAs tipos de =EDma est=E3o dis=
pon=EDveis: <ul><li>De um endere=E7o ou nome:</b> Por exemplo: adriano@co=
mpanhia.com para pegar um endere=E7o espec=EDfico, <br />companhia.com pa=
ra pegar todo mundo que manda email de companhia.com, <br />Adriano Gomes=
 para pegar uma pessoa espec=EDfica, Adriano para pegar todos os Adrianos=
</li><li><b>Para um endere=E7o ou nome:</b> Como um =EDm=E3 De: mas para =
o endere=E7o Para: de um email</li><li><b>Palavras no assunto:</b> Por ex=
emplo: ol=E1 para pegar todas as mensagens com ol=E1 no assunto</li></ul>
Magnet_MagnetType                       Tipo do =EDm=E3
Magnet_Value                            Valor
Magnet_Always                           Sempre vai para o bucket

Bucket_Error1                           Nomes de buckets somente podem co=
nter as letras de a at=E9 z min=FAsculas mais - e _
Bucket_Error2                           O bucket %s j=E1 existe
Bucket_Error3                           Criado o bucket %s
Bucket_Error4                           Por favor digite uma palavra que =
n=E3o seja em branco
Bucket_Error5                           Renomeado o bucket %s para %s
Bucket_Error6                           Deletado o bucket %s
Bucket_Title                            Sum=E1rio
Bucket_BucketName                       Nome do Bucket
Bucket_WordCount                        Contagem de Palavras
Bucket_WordCounts                       Contagens de Palavras
Bucket_UniqueWords                      Palavras =DAnicas
Bucket_SubjectModification              Modifica=E7=E3o do Assunto
Bucket_ChangeColor                      Trocar Cor
Bucket_NotEnoughData                    Dados insuficientes
Bucket_ClassificationAccuracy           Precis=E3o da Classifica=E7=E3o
Bucket_EmailsClassified                 Emails classificados
Bucket_EmailsClassifiedUpper            Emails Classificados
Bucket_ClassificationErrors             Erros de classifica=E7=E3o
Bucket_Accuracy                         Precis=E3o
Bucket_ClassificationCount              Contagem da Classifica=E7=E3o
Bucket_ResetStatistics                  Zerar Estat=EDsticas
Bucket_LastReset                        =DAltima Zeragem
Bucket_CurrentColor                     A cor atual de %s =E9 %s
Bucket_SetColorTo                       Ajustar a cor de %s para %s
Bucket_Maintenance                      Manuten=E7=E3o
Bucket_CreateBucket                     Criar bucket com o nome
Bucket_DeleteBucket                     Deletar o bucket chamado
Bucket_RenameBucket                     Renomear o bucket chamado
Bucket_Lookup                           Procurar
Bucket_LookupMessage                    Procurar por palavra nos buckets
Bucket_LookupMessage2                   Procurar no resultado por
Bucket_LookupMostLikely                 <b>%s</b> =E9 mais prov=E1vel de =
aparecer em <font color=3D"%s">%s</font>
Bucket_DoesNotAppear                    <p><b>%s</b> n=E3o aparece em nen=
hum dos buckets
Bucket_DisabledGlobally                 Desabilitado globalmente
Bucket_To                               para

SingleBucket_Title                      Detalhes para %s
SingleBucket_WordCount                  Contagem de palavras do bucket
SingleBucket_TotalWordCount             Contagem total de palavras
SingleBucket_Percentage                 Percentual do total
SingleBucket_WordTable                  Tabela de Palavras para %s
SingleBucket_Message1                   Palavras com asterico (*) foram u=
sadas para classifica=E7=E3o durante esta sess=E3o do POPFile.  Clique em=
 qualquer palavra para procurar sua probabilidade para todos os buckets.
SingleBucket_Unique                     %s =FAnicas
