# Copyright (c) 2001-2003 John Graham-Cumming

# This is used to get the appropriate subdirectory for the manual
LanguageCode                            fi
LanguageCharset                         ISO-8859-15

# Common words that are used on their own all over the interface
Apply                                   K&auml;yt&auml;
On                                      P&auml;&auml;ll&auml;
Off                                     Pois p&auml;&auml;lt&auml;
TurnOn                                  Laita p&auml;&auml;lle
TurnOff                                 Laita pois p&auml;&auml;lt&auml;
Add                                     Lis&auml;&auml;
Remove                                  Poista
Previous                                Edellinen
Next                                    Seuraava
From                                    L&auml;hett&auml;j&auml;
Subject                                 Aihe
Classification                          Luokitus
Reclassify                              Luokittele uudelleen
Undo                                    Peru
Close                                   Sulje
Find                                    Etsi
Filter                                  Suodata
Yes                                     Kyll&auml;
No                                      Ei
ChangeToYes                             Vaihda
ChangeToNo                              Vaihda
Bucket                                  Sanko
Magnet                                  Magneetti
Delete                                  Poista
Create                                  Luo
To                                      Vastaanottaja
Total                                   Yhteens&auml;
Rename                                  Nime&auml; uudelleen
Frequency                               Esiintymistiheys
Probability                             Todenn&auml;k&ouml;isyys
Score                                   Pistem&auml;&auml;r&auml;
Lookup                                  Etsi

# The header and footer that appear on every UI page
Header_Title                            POPFile hallinta
Header_Shutdown                         Sulje POPFile
Header_History                          Viestihistoria
Header_Buckets                          Sangot
Header_Configuration                    Asetukset
Header_Advanced                         Erikoisasetukset
Header_Security                         Turvallisuusasetukset
Header_Magnets                          Magneetit

Footer_HomePage                         POPFilen kotisivu
Footer_Manual                           K&auml;ytt&ouml;ohjeet
Footer_Forums                           Keskustelualueet
Footer_FeedMe                           Ruoki minua!
Footer_RequestFeature                   Pyyd&auml; ominaisuutta
Footer_MailingList                      Postituslista

Configuration_Error1                    Erotusmerkin pit&auml;&auml; olla yksitt&auml;inen merkki
Configuration_Error2                    K&auml;ytt&ouml;liittym&auml;n porttinumero pit&auml;&auml; olla 1:n ja 65535:n v&auml;lilt&auml;
Configuration_Error3                    POP3 kuunteluportin numero pit&auml;&auml; olla 1:n ja 65535:n v&auml;lilt&auml;
Configuration_Error4                    Sivun koon pit&auml;&auml; olla 1:n ja 1000:n v&auml;lilt&auml;
Configuration_Error5                    Historian p&auml;ivien m&auml;&auml;r&auml; pit&auml;&auml; olla 1:n ja 366:n v&auml;lilt&auml;
Configuration_Error6                    TCP odotusajan pit&auml;&auml; olla 10:n ja 300:n v&auml;lilt&auml;
Configuration_POP3Port                  POP3 kuunteluportti
Configuration_POP3Update                POP3-portiksi vaihdettu %s. Muutos ei tule voimaan ennen POPFilen uudelleenk&auml;ynnistyst&auml;.
Configuration_Separator                 Erotusmerkki
Configuration_SepUpdate                 Erotusmerkiksi vaihdettu %s
Configuration_UI                        K&auml;ytt&ouml;liittym&auml;n porttinumero
Configuration_UIUpdate                  K&auml;ytt&ouml;liittym&auml;n porttinumeroksi vaihdettu %s. Muutos ei tule voimaan ennen POPFilen uudelleenk&auml;ynnistyst&auml;.
Configuration_History                   Viestien m&auml;&auml;r&auml; sivua kohti
Configuration_HistoryUpdate             Viestien m&auml;&auml;r&auml;ksi sivua kohti asetettu %s viesti&auml;
Configuration_Days                      Viestihistorian p&auml;ivien lukum&auml;&auml;r&auml;
Configuration_DaysUpdate                Viestihistorian p&auml;ivien lukum&auml;&auml;r&auml;ksi asetettu %s p&auml;iv&auml;&auml;
Configuration_UserInterface             K&auml;ytt&ouml;liittym&auml;
Configuration_Skins                     Ulkon&auml;k&ouml;asetukset
Configuration_SkinsChoose               Valitse ulkon&auml;k&ouml;
Configuration_Language                  Kieliasetukset
Configuration_LanguageChoose            Valitse kieli
Configuration_ListenPorts               Kuunnellut portit
Configuration_HistoryView               Viestihistoria
Configuration_TCPTimeout                TCP-yhteyden odotusaika
Configuration_TCPTimeoutSecs            TCP-yhteyden odotusaika sekunteina
Configuration_TCPTimeoutUpdate          TCP-yhteyden odotusajaksi asetettu %s sekuntia
Configuration_ClassificationInsertion   Luokituksen n&auml;kyvyys
Configuration_SubjectLine               Aiherivin muuttaminen
Configuration_XTCInsertion              X-Text-Classification -otsikon lis&auml;ys
Configuration_XPLInsertion              X-POPFile-Link -otsikon lis&auml;ys
Configuration_Logging                   Loki
Configuration_None                      Pois p&auml;&auml;lt&auml;
Configuration_ToScreen                  Ruudulle
Configuration_ToFile                    Tiedostoon
Configuration_ToScreenFile              Ruudulle ja tiedostoon
Configuration_LoggerOutput              Kirjaus

Advanced_Error1                         Sana '%s' on jo huomiotta j&auml;tett&auml;vien sanojen listassa
Advanced_Error2                         Huomiotta j&auml;tett&auml;v&auml;t sanat voivat sis&auml;lt&auml;&auml; vain kirjaimia ja numeroita sek&auml; seuraavia merkkej&auml;: "._-@"
Advanced_Error3                         Sana '%s' lis&auml;tty huomiotta j&auml;tett&auml;vien sanojen listaan
Advanced_Error4                         Sana '%s' ei ole huomiotta j&auml;tett&auml;vien sanojen listassa
Advanced_Error5                         Sana '%s' poistettu huomiotta j&auml;tett&auml;vien sanojen listasta
Advanced_StopWords                      Huomiotta j&auml;tett&auml;v&auml;t sanat
Advanced_Message1                       Seuraavia sanoja ei oteta huomioon viestien luokittelussa siksi koska ne esiintyv&auml;t niin usein.
Advanced_AddWord                        Lis&auml;&auml; sana
Advanced_RemoveWord                     Poista sana

History_Filter                          &nbsp;(N&auml;kyviss&auml; vain sangon <font color="%s">%s</font> sis&auml;lt&ouml;)
History_Search                          &nbsp;(Etsitty aihetta %s)
History_Title                           Viimeaikaiset viestit
History_Jump                            Siirry viestiin
History_ShowAll                         N&auml;yt&auml; kaikki
History_ShouldBe                        Pit&auml;isi olla
History_NoFrom                          Ei l&auml;hett&auml;j&auml;tietoa
History_NoSubject                       Ei aihetta
History_ClassifyAs                      Luokittele
History_MagnetUsed                      K&auml;ytetty magneettia
History_ChangedTo                       Luokitukseksi vaihdettu <font color="%s">%s
History_Already                         Viesti on jo uudelleenluokiteltu sankoon <font color="%s">%s</font>
History_RemoveAll                       Poista kaikki
History_RemovePage                      Poista sivu
History_Remove                          Paina t&auml;st&auml; poistaaksesi n&auml;m&auml; viestit viestihistoriasta
History_SearchMessage                   Etsi l&auml;hett&auml;jien ja aiheiden joukosta
History_NoMessages                      Ei viestej&auml;
History_ShowMagnet                      Magneeteilla luokitellut
History_Magnet                          &nbsp;(N&auml;kyviss&auml; vain magneeteilla luokitellut viestit)
History_ResetSearch                     Peruuta

Password_Title                          Salasana
Password_Enter                          Sy&ouml;t&auml; salasana
Password_Go                             Hyv&auml;ksy
Password_Error1                         V&auml;&auml;r&auml; salasana

Security_Error1                         Suojattun portti pit&auml;&auml; olla 1:n ja 65535:n v&auml;lilt&auml;
Security_Stealth                        Piilotila/Palvelintoiminta
Security_NoStealthMode                  Ei (Piilotila)
Security_ExplainStats                   Kun t&auml;m&auml; asetus on p&auml;&auml;ll&auml;, POPFile l&auml;hett&auml;&auml; kerran p&auml;iv&auml;ss&auml; seuraavat kolme arvoa osoitteeseen www.usetehsource.com: bc (sankojen kokonaism&auml;&auml;r&auml;), mc (POPFilen luokittelemien viestien m&auml;&auml;r&auml;) ja ec (luokitteluvirheiden m&auml;&auml;r&auml;). N&auml;it&auml; tietoja k&auml;ytet&auml;&auml;n POPFilen k&auml;ytt&ouml;tavoista ja toimintatarkkuudesta kertovien tilastojen laatimiseen. Webpalvelin s&auml;ilytt&auml;&auml; lokitiedostoja noin 5:n p&auml;iv&auml;n ajan, jonka j&auml;lkeen ne poistetaan. Mink&auml;&auml;nlaista tietoa tilastojen ja IP-osoitteiden v&auml;lill&auml; ei s&auml;ilytet&auml;.
Security_ExplainUpdate                  Kun t&auml;m&auml; asetus on p&auml;&auml;ll&auml;, POPFile l&auml;hett&auml;&auml; kerran p&auml;iv&auml;ss&auml; seuraavat kolme arvoa osoitteeseen www.usetehsource.com: ma (POPFilen iso versionumero), mi (POPFilen pieni versionumero) ja bn (POPFilen k&auml;&auml;nn&ouml;snumero). POPFile saa vastauksen kuvana, joka n&auml;kyy sivun yl&auml;laidassa, kun uusi versio on saatavilla. Webpalvelin s&auml;ilytt&auml;&auml; lokitiedostoja noin 5:n p&auml;iv&auml;n ajan, jonka j&auml;lkeen ne poistetaan. Mink&auml;&auml;nlaista tietoa p&auml;ivitystarkistusten ja IP-osoitteiden v&auml;lill&auml; ei s&auml;ilytet&auml;.
Security_PasswordTitle                  K&auml;ytt&ouml;liittym&auml;n salasana
Security_Password                       Salasana
Security_PasswordUpdate                 Salasanaksi vaihdettu %s
Security_AUTHTitle                      Suojattu tunnistus/AUTH
Security_SecureServer                   Suojattu palvelin
Security_SecureServerUpdate             Suojatuksi palvelimeksi asetettu %s. Muutos ei tule voimaan ennen POPFilen uudelleenk&auml;ynnistyst&auml;.
Security_SecurePort                     Suojattu portti
Security_SecurePortUpdate               Portiksi vaihdettu %s. Muutos ei tule voimaan ennen POPFilen uudelleenk&auml;ynnistyst&auml;.
Security_POP3                           Hyv&auml;ksy POP3-yhteydet muilta koneilta
Security_UI                             Hyv&auml;ksy HTTP-yhteydet (POPFilen hallinta) muilta koneilta
Security_UpdateTitle                    Automaattinen p&auml;ivitystarkistus
Security_Update                         Tarkista p&auml;ivitt&auml;in onko POPFilest&auml; tullut uutta versiota.
Security_StatsTitle                     Tilastotietojen raportointi
Security_Stats                          L&auml;het&auml; p&auml;ivitt&auml;in tilastotietoja Johnille.

Magnet_Error1                           Magneetti '%s' on jo sangossa '%s'
Magnet_Error2                           Uusi magneeetti '%s' on ristiriidassa magneetin '%s' kanssa sangossa '%s' ja voisi aiheuttaa ristiriitaisia tuloksia. Magneettia ei lis&auml;tty.
Magnet_Error3                           Uusi magneetti, '%s', luotu sankoon '%s'.
Magnet_CurrentMagnets                   T&auml;m&auml;nhetkiset magneetit
Magnet_Message1                         Seuraavat magneetit aiheuttavat sen, ett&auml; viestit luokitellaan aina m&auml;&auml;riteltyyn sankoon.
Magnet_CreateNew                        Luo uusi magneetti
Magnet_Explanation                      On kolmenlaisia magneetteja:</b> <ul><li><b>L&auml;hett&auml;j&auml;n osoite tai nimi:</b> esimerkiksi &quot;erkki@esimerkki.fi&quot; yksitt&auml;ist&auml; osoitetta varten, <br />&quot;esimerkki.fi&quot; kaikkia niit&auml; varten, joiden osoite p&auml;&auml;ttyy &quot;esimerkki.fi&quot;, <br />&quot;Erkki Esimerkki&quot; yksitt&auml;ist&auml; henkil&ouml;&auml; varten ja &quot;Erkki&quot; kaikkia Erkkej&auml; varten</li><li><b>Vastaanottajan osoite tai nimi:</b> Samalla tavoin kuin l&auml;hett&auml;j&auml;magneettien kanssa, mutta vastaanottajien osoitteiden kanssa</li><li><b>Sanat aiheessa:</b> esimerkiksi &quot;heipparallaa&quot; kaikkia sellaisia viestej&auml; varten, joiden aiherivill&auml; on sana &quot;heipparallaa&quot;.</li></ul>
Magnet_MagnetType                       Magneetin tyyppi
Magnet_Value                            arvo
Magnet_Always                           laitetaan aina sankoon

Bucket_Error1                           Sangon nimess&auml; saa olla ainoastaan pieni&auml; kirjaimia a:sta z:aan, sek&auml; merkkej&auml; "-" ja "_"
Bucket_Error2                           Sanko nimelt&auml; %s on jo olemassa
Bucket_Error3                           Luotiin sanko nimelt&auml; %s
Bucket_Error4                           Sangon nimess&auml; pit&auml;&auml; olla joitakin merkkej&auml;
Bucket_Error5                           Vaihdettiin sangon %s nimeksi %s
Bucket_Error6                           Poistettiin sanko %s
Bucket_Title                            Tiivistelm&auml;
Bucket_BucketName                       Sangon nimi
Bucket_WordCount                        Sanam&auml;&auml;r&auml;
Bucket_WordCounts                       Sanam&auml;&auml;r&auml;t
Bucket_UniqueWords                      Erillisi&auml; sanoja
Bucket_SubjectModification              Aiheen muutos
Bucket_ChangeColor                      Vaihda v&auml;ri&auml;
Bucket_NotEnoughData                    Ei tarpeeksi tietoa
Bucket_ClassificationAccuracy           Luokittelutarkkuus
Bucket_EmailsClassified                 Viestej&auml; luokiteltu
Bucket_EmailsClassifiedUpper            Viestej&auml; luokiteltu
Bucket_ClassificationErrors             Luokitteluvirheit&auml;
Bucket_Accuracy                         Tarkkuus
Bucket_ClassificationCount              Luokittelum&auml;&auml;r&auml;t
Bucket_ResetStatistics                  Nollaa tilastot
Bucket_LastReset                        Viime nollaus
Bucket_CurrentColor                     Sangon %s t&auml;m&auml;nhetkinen v&auml;ri on %s
Bucket_SetColorTo                       Aseta sangon %s v&auml;riksi %s
Bucket_Maintenance                      Yll&auml;pito
Bucket_CreateBucket                     Luo sanko nimelt&auml;
Bucket_DeleteBucket                     Poista sanko nimelt&auml;
Bucket_RenameBucket                     Muuta sangon
Bucket_Lookup                           Etsint&auml;
Bucket_LookupMessage                    Etsi sanaa sangoista
Bucket_LookupMessage2                   Etsint&auml;tulos sanalle
Bucket_LookupMostLikely                 Sana <b>%s</b> esiintyy suurimmalla todenn&auml;k&ouml;isyydell&auml; sangossa <font color="%s">%s</font>
Bucket_DoesNotAppear                    <p>Sana <b>%s</b> ei esiinny miss&auml;&auml;n sangossa
Bucket_DisabledGlobally                 Poistettu yleisesti k&auml;yt&ouml;st&auml;
Bucket_To                               nimeksi
Bucket_Quarantine                       Karanteeni

SingleBucket_Title                      Sangon %s tarkemmat tiedot
SingleBucket_WordCount                  Sangon sanam&auml;&auml;r&auml;
SingleBucket_TotalWordCount             Sanojen kokonaism&auml;&auml;r&auml;
SingleBucket_Percentage                 Osuus kokonaism&auml;&auml;r&auml;st&auml;
SingleBucket_WordTable                  Sanataulukko sangolle nimelt&auml; %s
SingleBucket_Message1                   T&auml;hdell&auml; (*) merkittyj&auml; sanoja on k&auml;ytetty luokitteluun t&auml;m&auml;n istunnon aikana. Napsauta sanaa n&auml;hd&auml;ksesi sen esiintymistodenn&auml;k&ouml;isyyden kaikissa sangoissa.
SingleBucket_Unique                     %s erillist&auml; sanaa

Session_Title                           POPFile-istunto vanhentunut
Session_Error                           POPFile-instuntosi on vanhentunut. T&auml;m&auml; voi johtua siit&auml;, ett&auml; olet k&auml;ynnist&auml;nyt POPFilen uudelleen niin, ett&auml; selaimesi oli p&auml;&auml;ll&auml;. Napsauta ylh&auml;&auml;ll&auml; olevia linkkej&auml; jatkaaksesi POPFilen k&auml;ytt&ouml;&auml;.
