#!/bin/sh

# Copyright (c) John Graham-Cumming
#
#   This file is part of POPFile
#
#   POPFile is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   POPFile is free software; you can redistribute it and/or modify it
#   under the terms of version 2 of the GNU General Public License as
#   published by the Free Software Foundation.
#
#   You should have received a copy of the GNU General Public License
#   along with POPFile; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

# Patch kanwadict on Intel CPU
CPU_TYPE=`/usr/bin/uname -p`
# CPU_TYPE="i386"
KANWADICT_PATH=/Library/POPFile/kakasi

case $CPU_TYPE in
	powerpc )
		echo "PowerPC";
		cat $KANWADICT_PATH/kanwadict-head_ppc $KANWADICT_PATH/kanwadict-body > $KANWADICT_PATH/kanwadict
		;;
	i386 )
		echo "Intel";
		cat $KANWADICT_PATH/kanwadict-head_i386 $KANWADICT_PATH/kanwadict-body > $KANWADICT_PATH/kanwadict
		;;
esac

rm $KANWADICT_PATH/kanwadict-head_ppc
rm $KANWADICT_PATH/kanwadict-head_i386
rm $KANWADICT_PATH/kanwadict-body

POPFILE_STARTUP=/Library/StartupItems/POPFile/POPFile

"$POPFILE_STARTUP" restart

exit 0
