#!/bin/sh

# Constants
POPFILE_STARTUP=/Library/StartupItems/POPFile/POPFile
POPFILE_DIR=/Library/POPFile
STOPWORDS_PATH="$POPFILE_DIR"/stopwords
POPFILE_DB_PATH="$POPFILE_DIR"/popfile.db
POPFILE_CFG_PATH="$POPFILE_DIR"/popfile.cfg

# Stop POPFile
if [ -e "$POPFILE_STARTUP" ]; then
	"$POPFILE_STARTUP" stop
fi

# Back up stopwords
if [ -e "$STOPWORDS_PATH" ]; then
	rm "$STOPWORDS_PATH".old
	cp "$STOPWORDS_PATH" "$STOPWORDS_PATH".old
fi

# Back up database
if [ -e "$POPFILE_DB_PATH" ]; then
	rm "$POPFILE_DB_PATH".old
	cp "$POPFILE_DB_PATH" "$POPFILE_DB_PATH".old
fi

# Back up configuration
if [ -e "$POPFILE_CFG_PATH" ]; then
	rm "$POPFILE_CFG_PATH".old
	cp "$POPFILE_CFG_PATH" "$POPFILE_CFG_PATH".old
else
	# Create a new configration file
	# Check System Language
	LANG=`echo '(ja, en)' | sed 's/.\(..\).*/\1/'`
	# echo $LANG
	
	case $LANG in
		ja)
			PFLANG='Nihongo'
			;;
		en)
			PFLANG='English'
			;;
		*)
			PFLANG='English'
			;;
	esac
	
	# echo $PFLANG
	
	echo "html_language $PFLANG" > "$POPFILE_CFG_PATH"
fi

# Remove skins folder
rm -rf "$POPFILE_DIR"/skins

exit 0
